### ISSUE TITLE
WEIXIN UI?

### ISSUE THREAD

**Issue by soulteary** [weui/weui#1]
= =..issue 一血。

**Comment by progrape** [comment]
:)

**Comment by yohnz** [comment]
地板

**Comment by Inza9hi** [comment]
official ui?

**Comment by huobazi** [comment]
同问是官方么?

**Comment by progrape** [comment]
@Inza9hi yes, provided by wechat ui team

**Comment by progrape** [comment]
@huobazi 是的，`WeUI`是由微信团队提供的，同微信原生视觉体验一致的UI组件。帮助开发者构建认知感更强、体验更佳的Web服务 :)

**Comment by huobazi** [comment]
@progrape  :+1:

**Comment by qinshou** [comment]
![895](https://cloud.githubusercontent.com/assets/1736244/10389076/8a54562e-6ea1-11e5-9f5c-6fba40c9ce51.jpg)

**Comment by simongfxu** [comment]
:+1:

**Comment by HerringtonDarkholme** [comment]
![LGTM](http://lgtm.in/p/seAXj2noq)

**Comment by wzshuang** [comment]
是否有design guidelines供参考？单纯的ui感觉其实没太大用处

**Comment by a-lian123** [comment]
里面的div布局使用了position:absolute; top:0； left:0;  right:0; bottom:0; 实现了全屏，并且超出容器的内容还可以滚动，就算第二屏的内容高度比第一屏高度低，也不会出现第二屏覆盖不了第一屏的情况，略神奇啊，能讲讲这个布局方法么？

**Comment by agileago** [comment]
已经冲上榜单了👍

**Comment by think2011** [comment]
同问 @a-lian123 的问题

**Comment by progrape** [comment]
@a-lian123 @think2011 感谢关注我们的demo页 :smile:

- 为什么内容高度超出了容器还可以滚动？

因为父容器设置了`overflow-y: auto`属性，这样内容超出的时候就可以滚动了。为了在iOS下保持流畅的滑动效果，追加了`-webkit-overflow-scrolling: touch`属性。

- 为什么第二屏内容高度比第一屏低，也不会出现第二屏覆盖不了第一屏的情况？

其实第二屏和第一屏的容器都设置了全屏，并且都设置了背景色，所以只有层级关系的问题。因为第二屏的DOM是在后面的，所以第二屏就在上面，盖住了第一屏，当然，也可以通过`z-index`属性来改变层级关系。

**Comment by think2011** [comment]
@progrape (⊙o⊙)哦

**Comment by a-lian123** [comment]
@progrape 感谢回复。忘记是在微信的内置浏览器环境下了。。 是因为微信支持overflow-y所以可以直接使用这个属性实现滚动对吧，我记得一些机型下的浏览器overflow-y会有问题，所以平时都尽量避免，微信支持那就没问题了

**Comment by yhhwpp** [comment]
这个与腾讯的frozenUI不是一样的吗

**Comment by wangscu** [comment]
留名。

**Comment by progrape** [comment]
@yhhwpp 当然不一样。frozenUI是应用在手Q里面的，而WeUI是应用在微信里面的，两者的UI风格、用户习惯不相同

**Comment by gumutianqi** [comment]
目前的版本跟frozenUI还差很远，希望可以追上frozenUI，做出更适合微信的WebUI框架

**Comment by gumutianqi** [comment]
能结合微信公众平台的JSSDK封装插件就更好了

**Comment by progrape** [comment]
WeUI和FrozenUI并非竞争关系，两者的应用场景不同，也就不存在追赶的问题了。我们现在在努力开发和完善WeUI组件库，来提升微信内的Web应用的体验～


至于你说的结合JSSDK封装成插件，不知具体设想是什么？微信公众平台有提供封装的jssdk，详情可见[http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html](http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html)开发者引入之后即可调用jssdk功能～
