### ISSUE TITLE
ios微信客户端中打开页面，时间插件点不开，Android的没有问题

### ISSUE THREAD

**Issue by kylinshaw** [weui/weui#101]
ios微信客户端中打开页面，时间插件点不开，就像加了一个disabled属性一样。Android的微信客户端中打开页面没有问题，这个和系统有关系吗？
然后我将连接复制到浏览器中：
Android    UC浏览器
iOS  自带的Safari浏览器
两者都能点开时间插件，但是样式风格完全不一样(好像是和系统有关)
不知道你们有没有遇到过这样子的情况

**Comment by progrape** [comment]
请问系统版本和微信客户端版本分别是多少？是必现还是偶现？
