### ISSUE TITLE
对 Bower 不友好，用Bower下载出一堆文件出来。

### ISSUE THREAD

**Issue by Samlv9** [weui/weui#102]
如题，实际需要的只要 Style 目录的文件就好了。可是用 Bower 直接下载了整个 Git 仓库。

**Comment by wtser** [comment]
bower 的机制就是下载完整的代码不是吗

**Comment by progrape** [comment]
使用的时候确实只需要`dist/style/weui.css`，不过下载完整的文件也无妨，因为在使用的过程中，也可能会去看看example、less源码。

**Comment by Samlv9** [comment]
@wtser 不是的，这个项目应该配置一个 bower.json。现在这样准确的说，是不支持 bower的！

**Comment by Samlv9** [comment]
@progrape 下载这个源码的话，我的 sass/less 中使用的路径就很长了。比如我需要使用 `button` 就需要 
```sass
@import "src/style/widget/weui_button/weui_button";
```

**Comment by progrape** [comment]
通过bower下载下来，我们推荐直接使用`dist/style/weui.css`文件，不建议自己引用源码，因为从WeUI源码到产出的css文件，有WeUI自己的构建过程，比如`autoprefixer`。自己引用的话，可能会遗漏一些步骤，产生一些bug。

还有你说的“不支持bower”，并不对。如果不支持bower，你用命令`bower install weui`能下载下来吗？

**Comment by Samlv9** [comment]
@progrape 如果直接引用编译后的文件的话，那不是就算我的页面只使用了一个按钮，也需要导入整个编译后的css的43kb？

**Comment by Samlv9** [comment]
@progrape 另外补充一下（构建过程），假设我的 autoprefixer 需要 `autoprefixer({ "browsers": "> 1%" })`，就是我可能需要尽可能的支持更多的浏览器，所以我觉得用源码会好点。。。

**Comment by progrape** [comment]
你需要使用源码，那现在bower不就是正好帮你下载了源码么？

**Comment by Samlv9** [comment]
:joy:
