### ISSUE TITLE
IIS中如何配WEUI,怎么配都没有样式

### ISSUE THREAD

**Issue by haterbj** [weui/weui#104]
IIS中如何配WEUI,怎么配都没有样式出来
把LESS转成CSS,还是不出来
最后把LESS加到MIME中,引入less.js
也不出来样式,CHROME环境中报 406 (Not Acceptable) 错
谢谢

**Comment by haterbj** [comment]
配好了.网上说加MIME为TEXT/CSS不对,应当是text/less

**Comment by progrape** [comment]
可以close了不？

**Comment by Samlv9** [comment]
:joy: 没看明白~~~这个跟WEUI有什么关系？
