### ISSUE TITLE
这个有 Psd/AI 文件么？

### ISSUE THREAD

**Issue by Samlv9** [weui/weui#108]
能否提供下 Psd/AI 文件？这样做产品原型的时候方便很多。。。

**Comment by progrape** [comment]
抱歉，这个不能提供，设计稿不开源 :joy:

**Comment by Samlv9** [comment]
:joy: 好吧~

**Comment by progrape** [comment]
@Samlv9 有热心网友已经整理出sketch文件 [https://github.com/ZTfer/weui-sketch](https://github.com/ZTfer/weui-sketch)，可以使用这个来只做原型。感谢 @ZTfer

**Comment by Samlv9** [comment]
@progrape 666 非常感谢~~

**Comment by ZTfer** [comment]
正在做
