### ISSUE TITLE
缺表单验证的方法？

### ISSUE THREAD

**Issue by mysean** [weui/weui#112]
看UI的话应该是有的，自己写的话太累了，希望能加上

**Comment by moyus** [comment]
验证表单很多jQuery插件的

**Comment by mysean** [comment]
首先，weui里面貌似不能引用jquery（报错），其次weui表单验证和web页面不太一样，用jquery插件绕了一大圈个人感觉不太合适。还是希望能使用官方验证方法，早日完善。

**Comment by penghaozhong** [comment]
jquery使用没有问题啊，

**Comment by progrape** [comment]
https://github.com/progrape/weui.js/wiki/form
