### ISSUE TITLE
建议按下背景色使用lighten darken 

### ISSUE THREAD

**Issue by WoeOm** [weui/weui#118]
建议按下背景色使用lighten darken

**Comment by progrape** [comment]
@WoeOm 谢谢反馈，咨询了设计师，参照微信客户端的颜色，弹框按钮的active态颜色值设置为`#EEEEEE`

![active_dialog](https://cloud.githubusercontent.com/assets/4652816/11679419/d43a58dc-9e8b-11e5-819b-60b410fb5935.png)
