### ISSUE TITLE
H5 history.pushState 在微信内修改url后点击用safari打开/复制链接是修改之前的页面

### ISSUE THREAD

**Issue by zrain** [weui/weui#125]
Hey, nice work guys.

看到你回答了 微信内 pushState 相关的问题，我这里做了一些小尝试

我使用 H5 history.pushState 在微信内修改url后，点击 “用safari打开”/“复制链接” 发现链接地址是修改之前的地址，不知道这种情况有没有遇到过。

**Comment by progrape** [comment]
got it~

**Comment by zrain** [comment]
补充一下：使用你的demo来看，pushState 修改了 url 在“用safari打开”时， safari里的url是修改后的url 。没有问题，但是我用 pushState 修改路径后, 在“用safari打开”时 ，safari里的url是修改前的url。使用“复制链接”功能也是如此。唯一的区别是我的url中没有“＃”号

**Comment by bruceCzK** [comment]
这个应该是微信的BUG，所以SPA里面如果用了Html5Mode，到微信支付的页面时候要刷新下才行。

**Comment by zrain** [comment]
Thx 我现在 每个页面都刷新一下 否则分享页面 复制链接 和用Safari打开都会有问题 同样感谢您的回复 祝您工作愉快 期待微信的修复

发自我的 iPhone

**Comment by wb-yangxing** [comment]
他监听的是hashchange， 不是pushState

**Comment by Hanruis** [comment]
同样遇到类似的问题，@bruceCzK 在 SPA 里面使用 hash 的，在 IOS 下，也是需要刷新了才能 config 成功。然后如果需要频繁刷新的话， SPA 就失去意义了。求解。

**Comment by bruceCzK** [comment]
@Hanruis 我现在是每个页面都重新调用接口获取签名然后 config 一次，而且安卓和 iOS 的表现还不太一样。
比如同样从 `/a` 切换到 '/b'，iOS 会认为 URL 确实变化了，需要重新注入配置信息，安卓就不需要，而且安卓上面不同机型内核还不一样，有些又是支持 pushState 的，总之挺分裂的。

**Comment by Hanruis** [comment]
@bruceCzK 确实是。
另外有一点挺矛盾的，一方面，jssdk 里面说到 config 的时候，hash 部分不需要加上。
然而用 hash 实现的 webapp， 在公众号设置的支付目录一般都是 www.mywebapp.com/#pay/ 这样的目录。使用在支付页面 config 的时候，需要把这个 hash 加上才能支付。(─.─|||，不然会报，这个 url 未注册。

然后在 IOS 下需要刷新之后，这个 config 才能成功。纠结。。

**Comment by bruceCzK** [comment]
@Hanruis 有关支付目录有个小窍门，井号前面加一个问号，目录就会只计算到问好前面最后一个斜杠，具体可以看我博文

**Comment by Hanruis** [comment]
@bruceCzK woa，感谢！

**Comment by airyland** [comment]
@bruceCzK 因为微信客户端不同平台对history, hash的处理不同而且奇怪的实现真的浪费了好多时间，本来想做一个纯粹的单页面应用，用history，折腾到最后还是算了，直接用hash然后还是跳转到新页面去支付吧。然后因为router切换而出现的JSSDK config的问题直接就记录入口页面链接，当前页面链接，然后逐个试，只要出现wx.error, 就重新调用config。累感不爱，真希望微信能开个Repo来收集一下这些问题或者给个建议的处理方式。

顺便再提个问题如果能反馈给相关的同学就更好了，web开发工具对hash做了奇怪的处理：

输入这个地址打enter
`http://localhost:6004/#!/a`
url被处理成了这个样子，简直没法用。但是在js里进行hash设定又没问题。
`http://localhost:6004/#!/%21/a`

**Comment by progrape** [comment]
@airyland Web 开发者工具的问题收到，近期修复

**Comment by J22Melody** [comment]
求问这个问题什么时候能修复？ T.T

**Comment by magicly** [comment]
http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html 里说：
所有需要使用JS-SDK的页面必须先注入配置信息，否则将无法调用（同一个url仅需调用一次，对于变化url的SPA的web app可在每次url变化时进行调用,目前Android微信客户端不支持pushState的H5新特性，所以使用pushState来实现web app的页面会导致签名失败，此问题会在Android6.2中修复）。、

但是我们测试，发现6.3还是有问题啊。 iOS也有问题， 请问这个是bug么

**Comment by lzbSun** [comment]
@magicly 我们也出现这个问题，你们解决了没有

**Comment by lzbSun** [comment]
我们IOS是正常的 @magicly 就是安卓端微信不行

**Comment by Roeis** [comment]
测试发现是x5内核就会出现pushstate问题，ios和Android都有这个问题。在X5里，url栏不会改变，微信都是6.3的版本

**Comment by duxiaofeng-github** [comment]
@Roeis +1，微信是移动端的ie6果然不是浪得虚名。

**Comment by dajbd** [comment]
我也遇到这样的问题。history 修改后，微信中使用 safari 打开，url 中的参数全部丢失了。SPA 在微信中存在如此大的问题是我从来没有想过的。

**Comment by smalin** [comment]
问题依然存在。所以 iphone 只加载一次 we.config(config)， 安卓在每次 url 变化之后重新 wx.config(config)

**Comment by zhangjiayin** [comment]
进入页面的时候config 所有需要的权限 试试？ 以后在config 的时候忽略掉错误。强行调用！wx api

**Comment by mishe** [comment]
问题依然存在，没有解决bug的期限吗？

**Comment by mishe** [comment]
6.3.31貌似解决了，但为什么最新版的还是复现了？

**Comment by fenivana** [comment]
bug又回来了，没人管吗？

**Comment by wuchangming** [comment]
iOS 微信6.5.6版本。location.reload() 会导致通过Safari打开的按钮都消失了。。。。。

**Comment by asbai** [comment]
现在最新的微信 iOS 版上确实有这个问题？何时解决？

**Comment by wuchangming** [comment]
解决方案：url参数增加随机参数

```js
function wxRefresh() {
    var replaceQueryParam = (param, newval, search) => {
        var regex = new RegExp('([?;&])' + param + '[^&;]*[;&]?');
        var query = search.replace(regex, '$1').replace(/&$/, '');

        return (query.length > 2 ? query + '&' : '?') + (newval ? param + '=' + newval : '');
    };

    window.location.replace(location.protocol +
        '//' +
        location.host +
        location.pathname +
        replaceQueryParam('_wxr_', new Date().getTime(), location.search) +
        location.hash);
};
// 执行
wxRefresh();
```

**Comment by asbai** [comment]
必须刷新页面来解决么？那 SPA 意义何在？

**Comment by dajbd** [comment]
我遇到的情况来看，这似乎不是微信 webview 的问题。好像是：ios webview 自身存在的问题。
针对此问题，我使用 location.href 跳转一次，没办法之下的解决办法。

**Comment by asbai** [comment]
应该不是 ios webview  的问题，因为在 ios 版 QQ 里分享基于 pushState  的 SPA 页面就完全正常。所以应该就是微信的 bug。

**Comment by superevanzhu** [comment]
同样遇到这个问题
（1）分享。spa分享出去的是上个页面的url。这个真没找到解决办法。
（2）支付。用location.href=url的方式跳转支付页。带支付页的页面比较少，所以用location跳转影响不到。如果能接受每个页面都location跳转，就别玩spa了。

ps：微信在官方文档告诉大家6.3.0已修复该问题，然后在某次最新的版本中又偷偷的把bug放进去了，果然是业界良心！

**Comment by realzy** [comment]
vue+webpack构建的单页面应用。在iOS WKWebview内核下，调微信的分享，上传图片，开始录音，停止录音等api时，经常调用失败，不稳定，会有少数几次调用成功情况，
个别的 上传图片，分享等刷新可以解决，但刷新又会出来分享按钮消失情况。

求问何时可以解决~~

**Comment by herrdu** [comment]
想问什么之后能够解决

**Comment by GenesisChou** [comment]
又碰到这个问题了 我的情况是有的订阅号url会跟着变 有的订阅号url不会跟着变 
mmp 服了微信了

**Comment by aizigao** [comment]
mmp 同样的问题

**Comment by PLDaily** [comment]
使用a标签跳转可以解决复制链接与用浏览器打开的问题

**Comment by jinbiaode** [comment]
狗日的微信  阿西吧

**Comment by jinbiaode** [comment]
找到解决方法了，如何改变分享给别人链接不是第一个，需要在调一下分享 wx.onMenuShareAppMessage    把当前url传给它   tmd

**Comment by TongDaDa** [comment]
两年多了，这个问题还在。总之pushState不更新url.

**Comment by limichange** [comment]
我这里，现在hash模式也不变了。不知道各位有没有碰见。

**Comment by richard1015** [comment]
@wuchangming 
您好，非常感谢，使用了您的方法，完美解决，我又稍做修改加入refresh参数，避免重复刷新，我使用的是vue-cli ，vue小伙伴可直接复制代码
`let local = {
  share(route) {
    var replaceQueryParam = (param, newval, search) => {
      var regex = new RegExp("([?;&])" + param + "[^&;]*[;&]?");
      var query = search.replace(regex, "$1").replace(/&$/, "");

      return (
        (query.length > 2 ? query + "&" : "?") +
        (newval ? param + "=" + newval : "")
      );
    };
    if (!route.query.refresh) {
      var chat = '&'
      if (!Object.keys(route.query).length) {
        chat = '?'
      }
      window.location.replace(
        location.protocol +
        "//" +
        location.host +
        location.pathname +
        replaceQueryParam("_wxr_", new Date().getTime(), location.search) +
        location.hash +
        chat + "refresh=true"
      );
    }
  }
}

export default {
  install: function (vm) {
    vm.prototype.$statistics = local
  }
}
`
组件中调用
`   //微信分享特殊处理
    this.$statistics.share(this.$route)`

**Comment by limi58** [comment]
因为这些问题几年都无法解决，所以小程序应运而生，彻底解决了已上问题

**Comment by bugparty** [comment]
ie6到现在还是没人修

**Comment by esperyong** [comment]
或者，在跳转到需要调用微信api的页面的时候，使用window.location = '目地页面的绝对url'的方式进行跳转。也可以解决该问题。其实这个和刷新当前页面的方式是一样的。

**Comment by itbdw** [comment]
目前还没解决。

**Comment by keepeye** [comment]
被微信搞死了，我用vue的，h5 history模式下ios微信出现该问题。切换到hash模式下，安卓端(新版本)又现新的问题：授权成功跳转登陆页面居然不重新请求，还用历史缓存页面，导致没办法进行下一步提交code操作。
我们甚至考虑放弃spa了……

**Comment by ovaldi** [comment]
@BearJ 是不是请微信团队解决一下这个问题，好几年了。。。。

**Comment by MontageD** [comment]
直至2018-10-17,问题还没解决。。

**Comment by zero1898** [comment]
直至2018-10-19,问题还没解决。。

**Comment by falost** [comment]
直至2018-11-01,问题还没解决。。

本来这个问题在一年前被砍掉了，就没有处理，但是最近产品又需要加上来，所以来看看大家怎么解决的

**Comment by ihipop** [comment]
> 直至2018-11-01,问题还没解决。。
> 
> 本来这个问题在一年前被砍掉了，就没有处理，但是最近产品又需要加上来，所以来看看大家怎么解决的

找马化腾把这个加KPI 分分钟就给解决了

**Comment by windhc** [comment]
直至2018-11-13, 问题还没解决
吃相太难看，仗着流量大，丝毫不在乎开发者的感受

**Comment by 5468sun** [comment]
直至2018-11-13, 问题还没解决

**Comment by janzhou** [comment]
这个问题还在，issue为什么关了？

**Comment by Naiba01** [comment]
直至2018-11-24, 问题还没解决

**Comment by janzhou** [comment]
#591 同样的问题

**Comment by s749312025** [comment]
直至2018-12-14, 问题还没解决。

**Comment by celery8911** [comment]
直至2018-12-17, 问题还没解决。

**Comment by ma-lihui** [comment]
直至2018-12-28, 问题还没解决。

**Comment by LingYanSi** [comment]
直至9102年, 问题还没解决。微信💊

**Comment by kingsily** [comment]
直至2019-1-17, 问题还没解决。

**Comment by hawtim** [comment]
直至2019-1-23, 问题还没解决。

**Comment by huangche007** [comment]
直至2019-1-28，问题还没解决

**Comment by LiangChengweb** [comment]
直至2019-1-28，问题还没解决

**Comment by LiangChengweb** [comment]
直至2019-2-26，问题还没解决

**Comment by xiongxiaobo** [comment]
直至2019-2-27，问题还没解决

**Comment by qwIvan** [comment]
直至2019-03-05，问题还没解决

**Comment by keepeye** [comment]
直至2019-03-05，问题还没解决

**Comment by qwIvan** [comment]
@keepeye 有什么好的解决办法吗？

**Comment by keepeye** [comment]
> @keepeye 有什么好的解决办法吗？

目前只能进入页面后 window.reload() 一下

**Comment by weizs** [comment]
直至2019-03-12，问题还没解决

**Comment by petersmu** [comment]
简单粗暴的解决方法：

**Comment by petersmu** [comment]
2019-03-13，遇到这个问题，综合前面的解决方法，经过几番尝试之后，得到了一个简单粗暴的方案：
1. 方法的核心是使用`location.assign('xxx')`来强行刷新页面并修改url；
2. 每次页面进入的时候，触发`location.assign('xxx?isReload=1')`，xxx为当前子路由，前面不要加斜杠，'isReload'这个参数是为了避免出现死循环刷新，判断在没有'isReload'的时候触发`location.assign('xxx?isReload=1')`，这样就只会触发一次了；
3. 后来发现这样做会有一个问题，就是触发了`location.assign('xxx?isReload=1')`之后，返回不会返回上一个页面，因为`location.assign`实际上相当于做了一次跳转，返回的还是当前页面。为了解决这个问题，我采取的是强行先做一次返回，我用的vue，在`location.assign('xxx?isReload=1')`之前调用一次`this.$router.go(-1)`，这样返回的页面就是真正的上一页了。

这个方案比较笨拙，但实际测试确实有效果，如果有什么问题欢迎大家批评指正。

**Comment by bruceCzK** [comment]
@petersmu vue的话其实不用这么麻烦，在需要刷新的路由组件上加一个 mixin 就行了
```
// mixins/require-reload.js
export default {
  beforeRouteEnter(to, from, next) {
    if (!window.isWechat || from.name === null) {
      sessionStorage.removeItem('routeReloaded')
      return next()
    }
    if (!sessionStorage.getItem('routeReloaded')) {
      console.log('Reloading')
      sessionStorage.setItem('routeReloaded', 1)
      location.href = to.fullPath
      return
    }
    sessionStorage.removeItem('routeReloaded')
    next()
  }
}
```
在路由组件里面引入 mixin
```
// route-component.js
import requireReload from './mixins/require-reload'
export default {
  name: 'someComponent',
  mixins: [requireReload]
}
```
我这里用的是 sessionStorage 存标记，用 localStorage 也是可以的，像你一样放 url 上也没问题。

**Comment by haoyi2015** [comment]
@微信APP开发大佬，
你们IOS下复制和在浏览器打开URL是上一个页面的问题什么时候能有方案

**Comment by BearJ** [comment]
统一回复下，和iOS开发提这个bug，6.3.x的版本曾修复了，后面因为安全问题又改回来，有待进一步改进。大家有啥问题可以到开发者中心提出，这里会得到更多的关注：https://developers.weixin.qq.com/

**Comment by weizs** [comment]
@BearJ 所以意思就是，问题依旧存在，大家可以去提问题，但是改不改看你们规划？

**Comment by pimkle** [comment]
2019-03-27 版本7.0.3 安卓 pushState url 会更新 iOS 不会

**Comment by panle666** [comment]
**赶紧修复啊。。**

**Comment by adams549659584** [comment]
20190426还没修复

**Comment by haoyi2015** [comment]
20190429还是没修复啊，微信开发大佬，你们都不修复吗？

**Comment by panle666** [comment]
2019-4-29，垃圾微信

**Comment by adams549659584** [comment]
快修复啊。。。。。。

**Comment by xiaoxintang** [comment]
直到2019-5-7问题还没修复

**Comment by janzhou** [comment]
iOS 小程序web-view内的问题似乎修复了？raw h5 问题还在。求验证。

**Comment by w493189140** [comment]
直到2019-5-16问题还没修复

**Comment by Johnson-huang** [comment]
直到2019-5-17问题还没修复

**Comment by jinbiaode** [comment]
直到2019-5-27问题还没修复

**Comment by 9668596818ez** [comment]
直到2019-5-29问题还没修复

**Comment by zoulux** [comment]
直到2019-6-6问题还没修复

**Comment by xiaowang1314** [comment]
2019-6-29问题依旧

**Comment by yulrosy** [comment]
2019-7-2问题依旧

**Comment by lhf168** [comment]
2019-7-3问题依旧  在ios微信“复制链接”，复制结果为初始页面链接

**Comment by lhf168** [comment]
@微信APP开发大佬

**Comment by yuwanlin** [comment]
2019.7.10 安卓9，微信7.0.4。使用pushState修改url后，在浏览器打开url上的参数会丢失。

**Comment by BruceCham** [comment]
直至2019-07-15，问题还没解决

**Comment by xs528** [comment]
直至2019-07-31，问题还没解决

**Comment by MuLoo** [comment]
直至2019-08-02，问题还没解决。

**Comment by ZyanWlayor** [comment]
直到2019-08-06，问题还没解决。

**Comment by nieyulin112** [comment]
微信授权页面，地址栏拼接了code，立即分享，分享的页面是自定义的，结果分享出去的页面也是带有code，这样新用户点进来就会报错，大家有好的解决办法吗？

**Comment by lhf168** [comment]
你应该把要分享的链接进行处理。不能直接取当前页面的url放作为分享url。------------------ 原始邮件 ------------------
发件人: "nieyulin"<notifications@github.com>
发送时间: 2019年8月7日(星期三) 上午8:45
收件人: "Tencent/weui"<weui@noreply.github.com>;
抄送: "lhf168"<1147678023@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Tencent/weui] H5 history.pushState 在微信内修改url后点击用safari打开/复制链接是修改之前的页面 (#125)



微信授权页面，地址栏拼接了code，立即分享，分享的页面是自定义的，结果分享出去的页面也是带有code，这样新用户点进来就会报错，大家有好的解决办法吗？
 
&mdash;

**Comment by nieyulin112** [comment]
> 你应该把要分享的链接进行处理。不能直接取当前页面的url放作为分享url。------------------ 原始邮件 ------------------ 发件人: "nieyulin"<notifications@github.com> 发送时间: 2019年8月7日(星期三) 上午8:45 收件人: "Tencent/weui"<weui@noreply.github.com>; 抄送: "lhf168"<1147678023@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Tencent/weui] H5 history.pushState 在微信内修改url后点击用safari打开/复制链接是修改之前的页面 (#125) 微信授权页面，地址栏拼接了code，立即分享，分享的页面是自定义的，结果分享出去的页面也是带有code，这样新用户点进来就会报错，大家有好的解决办法吗？ &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.


我删除了code还是不行，就是会自动带上code，在工具里调试是可以的，一到手机上就有问题了，分享出去的页面就是会带上code

**Comment by lhf168** [comment]
你把要分享的页面链接进行处理，处理成你想要的格式。别人点击进来，你做个重定向------------------ 原始邮件 ------------------
发件人: "nieyulin"<notifications@github.com>
发送时间: 2019年8月7日(星期三) 上午9:12
收件人: "Tencent/weui"<weui@noreply.github.com>;
抄送: "lhf168"<1147678023@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Tencent/weui] H5 history.pushState 在微信内修改url后点击用safari打开/复制链接是修改之前的页面 (#125)


 
你应该把要分享的链接进行处理。不能直接取当前页面的url放作为分享url。------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "nieyulin"notifications@github.com 发送时间: 2019年8月7日(星期三) 上午8:45 收&#x4EF6;人: "Tencent/weui"weui@noreply.github.com; 抄送: "lhf168"1147678023@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Tencent/weui] H5 history.pushState 在微信内修改url后点击用safari打开/复制链接是修改之前的页面 (#125) 微信授权页面，地址栏拼接了code，立即分享，分享的页面是自定义的，结果分享出去的页面也是带有code，这样新用户点进来就会报错，大家有好的解决办法吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
我删除了code还是不行，就是会自动带上code，在工具里调试是可以的，一到手机上就有问题了，分享出去的页面就是会带上code
 
&mdash;

**Comment by falost** [comment]
大哥们，业务型的不需要在这里讨论吧

**Comment by blinkJun** [comment]
直到2019-08-08，问题还没解决。

**Comment by Grifree** [comment]
直到2019-08-20，问题还没解决。

**Comment by xujunjie10** [comment]
直到2019-08-23，问题还没解决。

**Comment by Ivy-Pei** [comment]
直到2019-09-06，问题还没解决。

**Comment by proactivefly** [comment]
直到2019-09-10 18:30，问题还没解决

**Comment by lqfxz520** [comment]
直到2019-10-21 ，问题还没解决

**Comment by wsxgs** [comment]
直到2019-10-30 ，问题还没解决

**Comment by five6002776** [comment]
直到2019-11-7 ，问题还没解决

**Comment by yerxichen** [comment]
weui已经凉了，换其他框架吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"five6002776"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月7日(星期四) 上午10:32
收件人:&nbsp;"Tencent/weui"<weui@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/weui] H5 history.pushState 在微信内修改url后点击用safari打开/复制链接是修改之前的页面 (#125)




直到2019-11-7 ，问题还没解决

**Comment by Danielhu229** [comment]
WTF, why not reopen this issue, does the maintainer cannot see thousands of comments?

**Comment by shiyutim** [comment]
在需要 复制链接 的页面， mounted 里面，使用 `this.$router.go(0)`，就解决了。

**Comment by zengpeng123** [comment]
> 在需要 复制链接 的页面， mounted 里面，使用 `this.$router.go(0)`，就解决了。

你这无限刷新页面了

**Comment by shiyutim** [comment]
谢谢提醒，不好意思，我看了下确实会无限刷新页面。当时用ios测的时候没注意，因为没显示刷新条。我想了下，可以在第一次进去的时候url添加个参数，带参数的时候才刷新，然后重新进入下页面。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zengpeng123 <notifications@github.com>
发送时间: Thursday, November 28, 2019 11:28:33 AM
收件人: Tencent/weui <weui@noreply.github.com>
抄送: shiyu <shiyutim@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [Tencent/weui] H5 history.pushState 在微信内修改url后点击用safari打开/复制链接是修改之前的页面 (#125)


在需要 复制链接 的页面， mounted 里面，使用 this.$router.go(0)，就解决了。

你这无限刷新页面了

―

**Comment by hawtim** [comment]
2019-12-24 最新版微信 复制链接会变化了

**Comment by fakefish** [comment]
直到2020-03-23 ，部分iOS上问题还会出现

**Comment by kongxu633** [comment]
直到2020-04-19 ，部分iOS上问题还会出现

**Comment by anota** [comment]
直到2020-07-01 ，部分iOS上问题还会出现

**Comment by anota** [comment]
发现通过pushState修改然后this.$router.go(0) 确实会更新url，但是这个会触发后台的请求，也算是刷新的方式，但是对于用户确实没啥感知。

我个人的场景是想让用户进来区分二次分享
```
beforeRouteEnter(to, from, next) {
    const query = to.query;
    if (query.secondshare === '1') {
      next();
    } else {
      query.secondshare = '1';
      next({
        path: to.path',
        query: query,
        replace: true,
      });
      router.go(0);
    }
  },
```

**Comment by anota** [comment]
发现通过pushState修改然后this.$router.go(0) 确实会更新url，但是这个会触发后台的请求，也算是刷新的方式，但是对于用户确实没啥感知。

**Comment by Look-For-Chestnut** [comment]
直到2020-08-07 ，部分iOS上问题还会出现，移动端的IE6得加油了...

**Comment by shinvdu** [comment]
直至2020-10-28，问题还没解决。

**Comment by ishowman** [comment]
> 同样遇到类似的问题，@bruceCzK 在 SPA 里面使用 hash 的，在 IOS 下，也是需要刷新了才能 config 成功。然后如果需要频繁刷新的话， SPA 就失去意义了。求解。

改成使用 history 模式能解决这个问题吗？

**Comment by CatcherInSky** [comment]
现在看还是，pushState之后，复制链接还是未修改之前的。。。

**Comment by lhf168** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已收到你发的邮件，我会尽快回复你！
