### ISSUE TITLE
weui 可以在微信程序里面正确显示吗

### ISSUE THREAD

**Issue by csrgxtu** [weui/weui#129]
比如我向关注的微信用户发了一个外链接的图文消息，然后点击跳转到对应的外链接，而这个外链接是由weui做成的，但是这个页面是在微信程序里面打开的，而不是在手机浏览器中打开的，请问这种情况下weui能否正确显示。

**Comment by progrape** [comment]
@csrgxtu 可以正常显示的，请放心使用。WeUI的demo就是你说的“外链接”，在微信内打开是没问题的，不光是微信内，主流的浏览器（可能不包括IE）都没问题~

**Comment by csrgxtu** [comment]
@progrape ， tks， really helps.
