### ISSUE TITLE
IOS 9.2 滑出效果太快了 如何破？

### ISSUE THREAD

**Issue by code-geeker** [weui/weui#133]
RT

**Comment by progrape** [comment]
可否具体描述一下是什么滑动效果太快？不明白你具体指什么

**Comment by php-freelancer** [comment]
ios 9.2版本上面 没有滑动的效果  几乎瞬间展示出来   9.2之前版本没这问题    具体情况，找台设备亲测

**Comment by bruceCzK** [comment]
好像新版的微信会在内存低的时候把动画效果全部去掉，你试试别的页面会不会也这样。

**Comment by progrape** [comment]
是的，可以杀掉进程重新打开，看看还会不会重现？

**Comment by php-freelancer** [comment]
跟微信没关系 和系统版本有关  9.2系统上滑动无特效

**Comment by duelgenji** [comment]
ios9.2的版本我先加了  setTimeout 200毫秒 强行处理了

**Comment by code-geeker** [comment]
@duelgenji  Cool!

**Comment by Samlv9** [comment]
是啊，transition 用着用着就没了，只能杀掉微信进程。重启微信，动画又有了~

**Comment by guanyx** [comment]
最近做的时候就是这样，用transition做Slide切入切出。移动到还剩下一点的时候，就突然结束动画了
最后参照weui的示例用animation，由于切出要把整个Slide隐藏，但是总是在还没完全移出的时候就被隐藏了。今天早上测了一下，发现animationend触发的时间总是比设定的时间早了80ms左右。真是个天坑。不得已还是用了setTimeout
