### ISSUE TITLE
cell链接到另一个网页后，回退后cell上会有黑线。

### ISSUE THREAD

**Issue by purlintan** [weui/weui#134]
cell链接到另一个网页后，回退后cell上会有黑线。

**Comment by wlynot** [comment]
不知道是不是同一个问题，用那个cell跳转链接的时候会出现问题，.weui_cell:before设置的scaleY(0.5)没有起作用，我用a.weui_cell:before再次设置scaleY(0.5)就起到了作用,不知道为啥。
ps:前端菜鸟一只，少见多怪

**Comment by progrape** [comment]
@purlintan @wlynot 能不能提供可以访问的链接？方面我们调试问题，我们还没重现这个bug

**Comment by purlintan** [comment]
http://www.purlin.space/example/index-06.html

**Comment by progrape** [comment]
出现了，谢谢

**Comment by progrape** [comment]
这个问题已修复，详见https://github.com/weui/weui/pull/137
