### ISSUE TITLE
分享的那个弹出层能直接通过JS调出来么？

### ISSUE THREAD

**Issue by Samlv9** [weui/weui#135]
![c qlsn bo kuqdxcms3ihid](https://cloud.githubusercontent.com/assets/6926770/11912613/89ff2fde-a680-11e5-9e3e-28f0f5808afe.png)

这个有没有 JS 方法能直接弹出来？还是必须用户去点右上角？

**Comment by progrape** [comment]
并不能通过js调出来，需要用户手动点击～

**Comment by Samlv9** [comment]
哦，好的，多谢
