### ISSUE TITLE
请教大神们,为何我用weui在微信ios里面看 动画基本无效呢

### ISSUE THREAD

**Issue by ctank** [weui/weui#138]
如题
ios8.3 微信app 6.3.8
动画时间改为5s 访问之后显示3s左右 动画直接结束
uc浏览器访问没什么问题 
请问是不是微信浏览器的问题?

**Comment by progrape** [comment]
可否给出代码，或者可以访问的demo链接？方便定位问题

**Comment by ctank** [comment]
发现问题了 重装微信app后已解决 手动捂个脸

**Comment by motionlife** [comment]
@ctank weui里面发现好多问题必须要重新安装微信才能解决 不管用户是不是最新版的微信。这真是个严重的问题啊
