### ISSUE TITLE
微信内测试DEMO，单选、复选反应很慢

### ISSUE THREAD

**Issue by zxwinmain** [weui/weui#14]
大概有一秒钟的延迟才能反应完，还没看代码、不知道是故意的还是怎么的。设备是 iPhone6 + 微信最新版。

**Comment by chen-zeyu** [comment]
这个是 mobile 上面 click 事件本身的延时，和 **样式库** 本身没有关系，具体的延时原因和解决方案见 [fastclick](https://github.com/ftlabs/fastclick)

**Comment by progrape** [comment]
#85
