### ISSUE TITLE
与ionic共用时android微信中input[type=date]失效 bug

### ISSUE THREAD

**Issue by Coralma** [weui/weui#140]
在微信项目中使用ionic写微信Web时发现android版本的微信页面上input[type=date]失效。但在ios的微信版本上却能正常显示。请帮忙看一下原因。非常感谢。

使用的ionic版本为1.1.0。
确定原因是由于在html中引入了下方ionic的js文件后android版本的微信中input[type=date]就失效
< script src="lib/ionic/js/ionic.bundle.min.js" >< /script >

**Comment by Coralma** [comment]
这个应该是Android微信内部浏览器与ionic有兼容性问题，与weui无关。请关闭这个bug吧。

我采用的替代方案是使用另一个第三方的ionic日期控件，此控件可以在微信浏览器中显示。具体URL如下：https://github.com/rajeshwarpatlolla/ionic-datepicker

**Comment by zhengdewei0817** [comment]
在给input标签设置disabled属性后，弹窗可以弹出

**Comment by SeanWangDev** [comment]
@zhengdewei0817 牛炸了
