### ISSUE TITLE
我不想装Node.js，可以用微信UI吗？

### ISSUE THREAD

**Issue by Liu-xu-dong** [weui/weui#145]
我看到两种方法安装都是需要node.js,这本来就是一套UI，为什么非要和服务器扯上关系呢

**Comment by progrape** [comment]
可以的，在github主页右上角，点击“Download Zip”，下载压缩包，解压后找到`dist/style/weui.css`，在页面引入这个文件就可以使用了。`Node.js`在这里只是作为前端工具，跟服务器没啥关系~
![image](https://cloud.githubusercontent.com/assets/4652816/12106318/04766ad2-b399-11e5-8bc6-e6c696fa696d.png)

**Comment by kakaxialex** [comment]
可以啊 就是没办法及时更新 用bower 及时更新多好
