### ISSUE TITLE
jQuery WeUI 发布啦

### ISSUE THREAD

**Issue by lihongxun945** [weui/weui#148]
jQuery/Zepto 版本的WeUI初步完成，地址： http://lihongxun945.github.io/jquery-weui/

jQuery WeUI 使用官方的CSS，所有JS组件均是jQuery插件的标准写法，使用非常方便，几乎没有上手难度。
我会保持定期更新，并和WeUI作者保持联系，大家不用担心突然废弃的情况。有任何问题大家可以通过Issue提给我，或者在 官方QQ群中讨论： 478234996

目前采用jQuery是考虑到大家都比较熟，而且很多时候页面中默认就引入了。

**Comment by progrape** [comment]
方便开发使用，赞作者 :+1:

**Comment by u0x01** [comment]
感谢辛勤付出！

**Comment by netbuffer** [comment]
支持个

**Comment by lmhaoye** [comment]
辛苦作者，作者永远活在我们心中。。

**Comment by jxiaox** [comment]
给个大赞

**Comment by hboxs** [comment]
终于出来了

**Comment by qq237202698** [comment]
赞！

**Comment by macnie** [comment]
赞！希望能尽快推出扩展插件 http://www.hituyu.com 已使用。

**Comment by Javen205** [comment]
支持 太棒了

**Comment by miaoyaoyao** [comment]
支持，关注中

**Comment by MaxineCaulfield** [comment]
:+1:
