### ISSUE TITLE
weiui的bower插件，wiredep无法识别，插不进index.html

### ISSUE THREAD

**Issue by btcioner** [weui/weui#149]
我在bower.json配置好weui，其他bower安装好后wiredep会自动把css插进指定index.html，weui装好就不行。

**Comment by progrape** [comment]
@btcioner wiredep 没有自动把 css 插入到指定的 index.html 中，是因为缺少了 `bower.json` 描述文件的 `main` 属性。

> A Bower package may not specify a main property in its bower.json file.

现已由 PR #150 补充~

**Comment by btcioner** [comment]
谢谢：-）
