### ISSUE TITLE
输入法弹出会遮挡，导致无法输入

### ISSUE THREAD

**Issue by yhhwpp** [weui/weui#15]
一些文本框输入选择后，输入法弹出会遮挡，导致无法输入，这个问题怎么解决你

**Comment by progrape** [comment]
请问是什么机型、系统版本、微信客户端版本呢？必现还是偶现？

**Comment by lengziyu** [comment]
小米note MIUI:v6.7.1.0，微信：v6.2.6 必然出现

**Comment by yhhwpp** [comment]
iPhone4，ios版本7.1.2 微信6.3.1第一次输入会遮挡，取消，第二次再输入就正常了

**Comment by jimhj** [comment]
iPhone6 里面是第三方输入法会遮挡，原生输入法不会

**Comment by nelsonkuang** [comment]
**貌似问题是出在下面这里**
```
.container, .page {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
}
```
**可以试试把container样式改成这样**
```
position: relative;
width: 100%;
height: 100%;
```

**Comment by dengxiaozhen** [comment]
我的安卓都会出现（机型：红米note 1，android 4.4.4 微信：6.3.9）

**Comment by cnyyk** [comment]
同样问题
![8 pic](https://cloud.githubusercontent.com/assets/275233/14066025/f1763042-f471-11e5-8e74-4efb38f2a2e4.jpg)

**Comment by cnyyk** [comment]
pro5手机，android 5.1 系统, 微信最新版

**Comment by mlyknown** [comment]
小米有问题啊0.0.0

**Comment by mlyknown** [comment]
这个问题demo改了吗？小米平板还是有问题。。
