### ISSUE TITLE
weui支持pull么？

### ISSUE THREAD

**Issue by callmesoul** [weui/weui#155]
weui组件还比较少，想贡献点代码，不知道支不支持pull，还是只微信团队自己开发？

**Comment by progrape** [comment]
@callmesoul 感谢关注，WeUI 是欢迎 PR 的，欢迎给 WeUI 贡献代码/意见建议。WeUI 目前是根据视觉设计稿来出组件的，新增组件的话需要先有视觉稿，所以一开始是微信团队开发新组件，社区同学参与改进/bugfix 等。我们近期会释放出视觉稿源文件，后续可以考虑新组件先给出视觉稿，然后有开源社区共同参与新组件的开发。
