### ISSUE TITLE
请问weui有没有开放的CDN可以使用?

### ISSUE THREAD

**Issue by wodenwang** [weui/weui#158]
RT

**Comment by songjinghe** [comment]
+1

**Comment by miaoyaoyao** [comment]
+2

**Comment by haycco** [comment]
+3

**Comment by henghome** [comment]
+4

**Comment by dengxiaozhen** [comment]
:heavy_plus_sign::one: :new_moon_with_face::new_moon_with_face:

**Comment by jonxx** [comment]
一般类似的项目都有CDN，移动网络带宽毕竟有限，如果能加速访问对用户体验提升比pc web效果更明显

现在很多第三方的微信H5页面加载速度也是相对app的一个软肋，体验很不好

**Comment by pkkgu** [comment]
版本还没有固化，这么快就CDN没有意义

**Comment by Wkan** [comment]
cdnjs已有: https://cdnjs.com/libraries/weui

**Comment by songjinghe** [comment]
cdnjs在国内的访问速度有时候不是很好，建议提交到七牛的CDN，方法见：http://staticfile.org/about.html
或者腾讯自家的CDN也可以。

**Comment by progrape** [comment]
https://github.com/weui/weui/wiki#cdn

**Comment by csersoft** [comment]
https://weui.io/weui.css
这个不行吗
