### ISSUE TITLE
dist 文件夹中 css 信息不正确

### ISSUE THREAD

**Issue by ZoomZhao** [weui/weui#159]
当前的 version 是 0.2.3，但是在 commit [Merge branch 'remotes/origin/develop'](https://github.com/weui/weui/commit/a9e0fa63621513b27773feeefc60918e98c8ca7f)  中，dist 文件夹中的 css 文件被修改为 0.2.2

**Comment by progrape** [comment]
谢谢反馈，我修复一下~

**Comment by progrape** [comment]
已修正 #165
