### ISSUE TITLE
缺少 TAB

### ISSUE THREAD

**Issue by chonchoi** [weui/weui#160]
虽然双 TAB 不是很好看，但没有的话不满足一些需求，需要自己再做。

**Comment by chonchoi** [comment]
希望加入的 tab 不是底部 tab，因为在微信的环境里，如果一个 webapp 继续使用底部 tab 是很糟糕的表现，应该使用顶部 tab。
![image](https://cloud.githubusercontent.com/assets/7456582/12528884/b09873aa-c1e0-11e5-849f-7f5579a9939f.png)

**Comment by progrape** [comment]
#176

**Comment by progrape** [comment]
tabbar和navbar在 0.4.0 的版本已加入~
