### ISSUE TITLE
关于contribution

### ISSUE THREAD

**Issue by yjcxy12** [weui/weui#163]
请问有contribution guideline么？ 希望可以给react-webui贡献。

**Comment by progrape** [comment]
@yjcxy12 感谢关注，react-weui 项目有一份[CONTRIBUTING](https://github.com/weui/react-weui/blob/master/CONTRIBUTING.md) ，里面列了一些约定，欢迎遵循里面的约定贡献代码。

react-weui 的组件跟着 weui 这边走，目前 react-weui 尚欠缺的是表单组件，欢迎参与表单组件的贡献。不过建议先开 issue 说明一下思路/使用者如何调用。

---

weui 昨天更新到了 v0.3 ，新增了上传组件（可以归属到表单）和九宫格，这两个组件也可以接受 PR ~
