### ISSUE TITLE
Loading Toast 的实现

### ISSUE THREAD

**Issue by yjcxy12** [weui/weui#167]
看到源码实现是12个leaf，给每个leaf设animation。
是否可以定下每个leaf的opacity，然后给parent设置rotating animation 并使用step function。

**Comment by progrape** [comment]
@yjcxy12 这个实现巧妙，但是实测菊花转动的过程中会抖动，看能不能解决这个问题？

**Comment by yjcxy12** [comment]
请问是在哪个浏览器出现这种问题？

**Comment by progrape** [comment]
PC 的 Chrome、iPhone 6 测试效果也会有抖动的情况，可能是 transform-origin 位置的问题

**Comment by yjcxy12** [comment]
使用 transform-origin: left 1px 0; 效果最好，和 .weui_loading_leaf 的 top: -1px 有关。
