### ISSUE TITLE
能不能把前缀 weui_统统去掉

### ISSUE THREAD

**Issue by foolishwang** [weui/weui#171]
weui_

**Comment by wtser** [comment]
@foolishwang 请说说你的理由

**Comment by progrape** [comment]
因为 CSS 都是页面全局起作用的，设置前缀是为了不侵入页面其他的代码。例如页面当中，取 `title`、`button`、`input`、`icon` 这样的名字会很常见，如果 WeUI 也取这样的名字，就会有相互覆盖的问题，开发者使用 WeUI 时，需要了解 WeUI 用过了哪些名字，谨慎的避开，一不小心就重名了。所以我们加上前缀来区分，不侵入开发者自己写的代码。

**Comment by duruitang** [comment]
不建议去掉，建议短一点，改成wu_

**Comment by gaomd** [comment]
不建议改成 `wu_` 前缀，`weui_` 足够短了。

倒是 https://github.com/weui/weui/issues/10 提到的连字符，建议采用 `-` 替代 `_` 连字符，用 `_` 连字符已经与世界前端的主流思路脱轨了，以微信的影响力，难免会阻碍国内前端行业的进步。

**Comment by n7best** [comment]
可以参考BEM的命名方式

**Comment by alexlee002** [comment]
这是一个无奈的现实。按道理，这个应该按通行的变量命名方式，也就是_做连接，但目前的现实是，前端都喜欢用-

发自我的 iPhone

**Comment by csk83** [comment]
其实这个我也比较奇怪，看了这个CSS，感觉 forzenui.github.io 做的事情差不多，而且没有forzenui的组件多。
forzenui是腾讯手Q官方的，这个是微信官方的么？

**Comment by jymusic0663** [comment]
腾讯内部有矛盾吗？ QQ和微信

**Comment by muzuiget** [comment]
前缀还是要的，不过我投 `weui-` 一票，用 `xxx-` 格式做前缀提高辨识了，毕竟很多框架都这么做了，至于后边的单词连字符，也就没所谓了，例如 `weui-grid_icon` 可以接受，前缀分隔和单词连字容易区分开来。

**Comment by qianduan** [comment]
用 `-` 还是 `_` ，两者均有优劣，也不能说大部分都用某一种它就是最优的，既然选择任何一种都是ok的，那就没有必要再讨论了，有兴趣可以去看看西乔的那几篇『圣战』的[公众号文章](http://blog.xiqiao.info/2015/03/31/1515)。

另外手机QQ和微信的产品形态和设计风格和体验都不一样，这也是为什么鹅厂有两套开源UI库的原因。

考虑到题主的问题已经解答，这里关贴了～～

**Comment by justqyx** [comment]
我感觉 `weui-` 后面带着 `__` 极其恶心，我所见过的国外的开源项目都是 dash case，即 `a-b-c`，从来没有见过 `a-b_c`、`a_b__c` 这一类的恶心写法。
