### ISSUE TITLE
请问为什么按钮要加一个伪类来完成样式呢？

### ISSUE THREAD

**Issue by hq5544** [weui/weui#175]
请问为什么按钮要加一个伪类来完成样式呢？

我注意到按钮是用a标签完成的，为什么还要用伪类完成边框呢？而且用了scale，求指教。

补充：不仅仅按钮，很多边框都是使用的伪类完成的。

**Comment by jcpplus** [comment]
scale是为了满足在高清屏上实现1px的效果吧。

> ps,还未看过代码

**Comment by hq5544** [comment]
好巧妙啊！谢谢。

**Comment by progrape** [comment]
@hq5544 如 @jcpplus 同学所言，是为了实现 retina 屏幕下1像素线。实现方式有多种，可以搜索一下看看~

**Comment by hq5544** [comment]
@progrape 好巧妙的实现方法，谢谢。
