### ISSUE TITLE
系统增加底部导航和顶部导航

### ISSUE THREAD

**Issue by zbcdj2008** [weui/weui#176]
底部导航可以设置2-4个的导航信息，顶部导航也可以设置2-3个标签的那种。
![qq 20160125175733](https://cloud.githubusercontent.com/assets/1982308/12547787/32ce5ddc-c38d-11e5-8b20-7d64b44ceb59.png)
![qq 20160125175811](https://cloud.githubusercontent.com/assets/1982308/12547792/3de93d9a-c38d-11e5-84d0-a76276d27d56.png)

**Comment by zbcdj2008** [comment]
突然发现好像和 #160 重复了

**Comment by chonchoi** [comment]
不建议增加底部 tab，这加重了轻应用的原则，建议最多使用顶部 tab

**Comment by pkkgu** [comment]
@chonchoi 底部导航才重要，微信浏览器与顶部导航重叠，误点几率很高！

**Comment by zbcdj2008** [comment]
我觉得底部和顶部都比较重要，底部一般是做导航，现在的APP应用基本都有导航，要不就是类似9宫格的导航，微信内嵌的html应用我觉得底部导航是不可缺少的功能，而顶部导航正常使用的话误点几率基本没有的，我觉得大部分人都是顶部用来做分类，底部做导航，貌似没有反过来搞的吧，不过轻应用东西确实比较少。weui既然已经在微信的开发文档都增加目录了，这两个功能最好还是要有的比较好

**Comment by chonchoi** [comment]
@zbcdj2008 不听不听！

**Comment by wychurry** [comment]
我觉得是说服微信团队把内置浏览器的x5内核搞好，跟上标准，不要做移动端的ie6。这些重复轮子的事情没意义

**Comment by qianyuchang** [comment]
@wychurry  +1，每次调兼容都恶心的想死

**Comment by easykoo** [comment]
@wychurry +1，每次调兼容都恶心的想死

**Comment by Jonexuan** [comment]
@wychurry +1，每次调兼容都恶心的想死

**Comment by 3952781A46522CA889CEF1E85EFFFB6A** [comment]
@wychurry →_→ 移动端的兼容问题一点也不比PC端少 还很难调试 好烦

**Comment by zhoudaqing** [comment]
底部导航需求+1

**Comment by miaoyaoyao** [comment]
底部导航需求+1

**Comment by kevenwuwu** [comment]
底部导航需求+1

**Comment by superboy724** [comment]
@wychurry +1，每次调兼容都恶心的想死

**Comment by BearJ** [comment]
![Uploading 579658789037567463.jpg…]()

**Comment by progrape** [comment]
navbar 和 tabbar 已经随 0.4.0 发布，欢迎使用~
