### ISSUE TITLE
建议更改MASK的z-index级别

### ISSUE THREAD

**Issue by RunningCoderLee** [weui/weui#182]
建议把mask的z-index级别调高一点，现在是1，有时候容易覆盖不全整个屏幕

**Comment by uxsi** [comment]
@RunningCoderLee 是什么场景下呢

**Comment by RunningCoderLee** [comment]
@uxsi 就比如我要添加一个底部的tabbar，如果我把tabbar的z-index值设为1或者比1大的值，那么mask就覆盖不了底部的tabbar

**Comment by graysheeep** [comment]
我也遇到了，后来自己强行改成了999
