### ISSUE TITLE
weiui有没有在列表展现方面推荐的做法？

### ISSUE THREAD

**Issue by kevenwuwu** [weui/weui#187]
![image](https://cloud.githubusercontent.com/assets/16933899/12638984/2a052aea-c5dc-11e5-9d22-50f270f5ffa5.png)

如图，在查询结果需要列表展示的时候，只能用weui_cells，感觉不同记录之间的区分度不太够，整体感觉不好。是不是可以增加点这方面的样式？

**Comment by progrape** [comment]
@kevenwuwu 如果你觉得某个字段比较重要，可以将该字段的值设置成别的颜色。例如你截图中的“当前状态”字段，“处理完毕”可以设置成绿色，“未完成”可以设置成红色。当然，这只是我的个人意见，不代表 WeUI 官方意见。专业的意见应该由设计师给出建议~
