### ISSUE TITLE
页面一触碰就总是闪屏 滑动条怎么都去不掉

### ISSUE THREAD

**Issue by motionlife** [weui/weui#188]
页面一触碰就总是闪屏 有时闪成白屏 滑动条怎么都去不掉 试过各种方法
在华为和小米手机上都是同样的问题

**Comment by motionlife** [comment]
手机浏览器中很完美 就是在微信内置浏览器中会出现这个问题。。。。

**Comment by motionlife** [comment]
用户必须重装微信才能解决 这个问题 为什么尼？有什么解决办法吗 总不能让人家重新安装微信吧。

**Comment by qianduan** [comment]
重装微信？那应该不是weui的问题了。帮忙定位下：1.重装后正常的情况下，下拉页面，看是否有X5的那两行文案。 2.闪屏时，清空一下微信的缓存//如果是测试机的话，清空缓存应该没有啥问题吧。3.QQ浏览器有个插件可以debug微信里面的页面，具体可以看 http://blog.qqbrowser.cc/ 看能否定位到问题所在。

**Comment by motionlife** [comment]
今天一共实验三台机器 华为MATE7 小米4 和小米NOTE 都是同样的问题 ，各种手机游览器中都正常，唯独在微信内置游览器中tap时明显有粘滞感 时不时会白屏，页面右侧滑条无法去掉。清内存重启机器都是一样效果，但是重装微信后一切问题都没有了。MATE7 小米4 之前安装的都是最新版微信，我现在还有一台机器没重装，因为在找问题根源

**Comment by motionlife** [comment]
@qianduan

**Comment by motionlife** [comment]
@qianduan 微信webview如果用QQ浏览器X5内核的都会出现这个问题。真不是我代码问题跑weui官方demo也是一样的问题，如果weui_grids 超过整屏更明显，

**Comment by progrape** [comment]
@motionlife 有 demo 可以访问吗？方便定位问题

**Comment by motionlife** [comment]
@qianduan 麻烦帮我找一下这个页面问题在哪这个 [页面](http://iot.sg-z.com/smartkey)
就是简单的增加了官方demo gridview的个数，如果用X5内核微信的进去就不正常了。
哎 前端经验少 一晚上都没解决 还请帮忙看下 谢谢

**Comment by motionlife** [comment]
@progrape 麻烦帮我找一下这个页面问题在哪，这个[ 页面](http://iot.sg-z.com/smartkey)
只是简单的增加了官方demo gridview的item个数，如果用X5内核微信的进去就不正常了。
哎 前端经验少 一晚上都没解决 还请帮忙看下 谢谢

**Comment by motionlife** [comment]
@qianduan 在开发的微信公众号是 iotsgcc ，您有空能进来帮我看一下吗

**Comment by motionlife** [comment]
@progrape 在开发的微信公众号是 iotsgcc ，您有空能进来帮我看一下吗 感激不尽啊

**Comment by xxiyj** [comment]
@progrape 官方的demo cell 滑动 会出现闪屏

**Comment by xxiyj** [comment]
@progrape 安卓

**Comment by hlizard** [comment]
为什么下拉页面划不出任何文字了，我记得微信内置浏览器之前是可以的啊，猜想是不是这个demo改变了
X5的什么设置，或者X5被他搞残了，我android 4.1的手机玩demo也闪屏白屏

**Comment by motionlife** [comment]
@hlizard QQ X5就是移动 界的IE6！当之无愧

**Comment by opendever** [comment]
@progrape 微信6.3.13 安卓闪屏，有时页面会显示不全，被截断。

**Comment by motionlife** [comment]
再反馈一下：已经十分确信问题的根源就是内嵌X5内核引起的了。官方example如果在内嵌X5内核的微信和手机QQ客户端中打开的话，就会出现同样的触摸下拉闪屏问题！而如果微信和QQ的webview如果不是X5的话就没有这个问题。严重的是现在好多android客户的微信webview都是X5内核。。。到底example.css要怎么该才好啊

**Comment by motionlife** [comment]
@progrape 再反馈一下：已经十分确信问题的根源就是内嵌X5内核引起的了。官方example如果在内嵌X5内核的微信和手机QQ客户端中打开的话，就会出现同样的触摸下拉闪屏问题！而如果微信和QQ的webview如果不是X5的话就没有这个问题。严重的是现在好多android客户的微信webview都是X5内核。。。到底example.css要怎么该才好啊

**Comment by progrape** [comment]
@motionlife 等 X5 更新，快了

**Comment by progrape** [comment]
X5 blink 已全量升级

**Comment by zhyzhy782** [comment]
Hey, 

Have you seen that new stuff? It'is  really nice, and think you'll  be interested,  just take a look <http://tendency.mylakeshoredental.com/e7ake/507>

Sincerely yours, zhyzhy782
