### ISSUE TITLE
页面引入cell样式后向左边一划页面右边会出现一条10%左右的竖的白边

### ISSUE THREAD

**Issue by Shawn-Aaron** [weui/weui#189]
查找之后发现将.weui_cell:before 中的width设为96%而不是原来的100%的时候白边消失，不知道是不是我引入有问题。

**Comment by progrape** [comment]
@Shawn-Aaron WeUI 中的 Cell 组件，1px 线的宽度是设成 100% 的。你改成 100% 看看还会不会出现你描述的问题？

**Comment by Shawn-Aaron** [comment]
@progrape 是这个样式
.weui_cell:before {
    content: " ";
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 1px;
    border-top: 1px solid #d9d9d9;
    color: #d9d9d9;
    -webkit-transform-origin: 0 0;
    transform-origin: 0 0;
    -webkit-transform: scaleY(.5);
    transform: scaleY(.5);
    left: 15px;
}
里面那个宽度吗？就是这个是100%的时候会有这个问题。

**Comment by jerryyan1990** [comment]
overflow:hidden;就没有了 我也遇到了
