### ISSUE TITLE
weui_dialog

### ISSUE THREAD

**Issue by lobtao** [weui/weui#19]
.weui_dialog {
    position: fixed;
    z-index: 13;
    width: 85%;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    -webkit-transform:translate(-50%,-50%);/*需要加上这行，QQ和微信里才能显示居中*/
    background-color: @weuiDialogBackgroudColor;
    text-align: center;
    border-radius: 3px;
    .weui_dialog_confirm & {
        .weui_dialog_hd {
            text-align: left;
            padding: 1.2em 20px .5em;
        }
        .weui_dialog_bd {
            text-align: left;
        }
    }
}

**Comment by kevyu** [comment]
-webkit 在运行gulp的时候会通过autoprefixer自动添加的。https://github.com/weui/weui/blob/master/dist/style/weui.css#L687

**Comment by progrape** [comment]
是的，跑构建脚本的时候会[gulp-autoprefixer](https://github.com/sindresorhus/gulp-autoprefixer)插件自动补全私有前缀
