### ISSUE TITLE
WEUI如何进行表单提交

### ISSUE THREAD

**Issue by yarving** [weui/weui#190]
我试了下官方提供的cell的demo，点了下“确定”（至少看起来他和submit一样），修改了href，但是表单数据，如radio button选择的信息并没有被传递。怎么办？

**Comment by progrape** [comment]
@yarving 单选组件也就是 `<input type="radio" name="xxx" />` ，跟普通的表单字段一样。你没有提供示例代码，不能帮你定位为什么没有提交。如果是用 `$( "form" ).serialize()` 序列化，记得单选框的 input 也要放在 `form` 里面。

这里写了表单提交的一个示例：
http://s.codepen.io/progrape/debug/XXYaqz
http://codepen.io/progrape/pen/XXYaqz

**Comment by yarving** [comment]
@progrape Thanks very much. I've find a way to solve this issue.

**Comment by yarving** [comment]
@progrape BTW，看到你给我的Demo地址是codepen的，以前我听说过codepen，这次看了之后挺感兴趣的，您有时间的话能稍微介绍下这个东西吗？没时间的话我就自己去找相关资料，不耽误您，多谢。

**Comment by progrape** [comment]
@yarving 可以看看 Flask 的文档，在哪里存放第三方库比较合适；或者直接引用 [CDN地址](https://github.com/weui/weui/wiki#cdn)，就不用在本地存放了。

关于 codepen ，我觉得它的代码编辑体验做很不错，而且 HTML、JS 和 CSS 都支持常用的预编译语言，尤其是 CSS，还支持 autoprefixer。更多的其他功能你可以去发掘~ 官方的博客也有很多介绍 http://blog.codepen.io

比较大的缺点是打开速度比较慢。

**Comment by yarving** [comment]
@progrape Thanks, 我放在一个可读取的位置，CDN这种方式我倒是没想过，谢谢提醒，茅塞顿开。

Copdepen，我阅读下你的资料。多谢。
