### ISSUE TITLE
可筛选的选择菜单

### ISSUE THREAD

**Issue by wwy94621** [weui/weui#191]
请问weui里是否支持可筛选的选择菜单？有时候会遇到待选项特别多的情况，不能筛选很难用。

**Comment by baixuer2013** [comment]
支持，官网这段代码就是筛选的吧，我正在用。不知道你问的是不是这个问题。
  <div class="weui_cell weui_cell_select weui_select_after">
                <div class="weui_cell_hd">
                    国家/地区
                </div>
                <div class="weui_cell_bd weui_cell_primary">
                    <select class="weui_select" name="select2">
                        <option value="1">中国</option>
                        <option value="2">美国</option>
                        <option value="3">英国</option>
                    </select>
                </div>
            </div>

**Comment by baixuer2013** [comment]
view-source:http://weui.github.io/weui/#icons

**Comment by wwy94621** [comment]
这个是没有筛选功能的吧？只有三个备选项。我的意思是比如有几十个备选项，可以通过输入字母或汉字来缩小备选项的范围。就像在通讯录里找人那样

**Comment by progrape** [comment]
@wwy94621 你指的搜索？ 最新版本已经加入

![image](https://cloud.githubusercontent.com/assets/4652816/13521984/94e2c93c-e227-11e5-84da-48b3af5fbe06.png)
