### ISSUE TITLE
样例中的showActionSheet方法会多次绑定事件

### ISSUE THREAD

**Issue by xjsylhl** [weui/weui#195]
'#showActionSheet': {
                click: function () {
                    。。。
                    mask.show().addClass('weui_fade_toggle').click(function () {
                        hideActionSheet(weuiActionsheet, mask);
                    });
                    $('#actionsheet_cancel').click(function () {
                        hideActionSheet(weuiActionsheet, mask);
                    });
                   。。。
                }
            }

这里的两个 .click(function() {} 应该改成：
.one('click',function (){}

**Comment by progrape** [comment]
谢谢指出~
