### ISSUE TITLE
微信样式库的组件可以做到交互

### ISSUE THREAD

**Issue by baixuer2013** [weui/weui#198]
我想问一下，微信样式库中，只要输入字段的组件（例：textbox），这个字段能不能提取出来，作为2次查询的字段。功能实现就像直接在微信客户端与企业号交互一样，输入关键字A0989，然后中转网站拦截到消息，从数据库查询出有效数据，返回给客户端。

**Comment by sklthegoodman** [comment]
weui是样式库，没有规定使用表单的逻辑，如果有需要，可以自己写监听逻辑。
