### ISSUE TITLE
关于布局方式

### ISSUE THREAD

**Issue by mlyknown** [weui/weui#199]
weui的布局方式是怎么考虑的呢？里面大部分都没有用到flex布局，但是有些地方又用到了，兼容性方面怎么考虑的，基于什么考虑的呢？（经验？）

**Comment by jszsj** [comment]
我也想知道，Grid只有九宫格，如何实现复杂一点的grid呢？

**Comment by mlyknown** [comment]
同问  0.0

**Comment by progrape** [comment]
目前的 x5 内核支持部分 flex 特性，而且是旧的写法，所以现在 weui 是有限制的使用。等它完整支持的时候，我们会改成 flex。

@jsw0528 Grid 设计时就是九宫格的组件，不是用作布局的。后面如果需求大的话，可以考虑加入专门做布局的组件。

**Comment by jsw0528** [comment]
咦？关我什么事？

**Comment by progrape** [comment]
@ 错认了，so sorry :joy:
