### ISSUE TITLE
“微信JSAPI”那篇 wiki 有过时之处，如 addContact 添加好友已禁用

### ISSUE THREAD

**Issue by SnowOnion** [weui/weui#2]
“[微信JSAPI](https://github.com/weui/weui/wiki/%E5%BE%AE%E4%BF%A1JSAPI)”那篇 wiki 有过时之处，
譬如通过 ```WeixinJSBridge.invoke('addContact',... ) ```添加好友已禁用。
（ref: http://mp.weixin.qq.com/qa/7/66fb98d5261259cb083a9f475382a237.html）

**Comment by BearJ** [comment]
谢谢，文中已加上JSAPI新版的链接

**Comment by SnowOnion** [comment]
赞 ：）
