### ISSUE TITLE
新手请教一个问题

### ISSUE THREAD

**Issue by Smile-dan** [weui/weui#207]
直接引入css，不用bower和npm安装可以使用吗？我是eclipse开发java，不知道怎么安装。。。

**Comment by progrape** [comment]
可以的，只要能获取到 weui.css 文件就行。你可以直接引用我们的 CDN 路径，在 [wiki](https://github.com/weui/weui/wiki#cdn) 上可以查到地址；也可以在 [release](https://github.com/weui/weui/releases) 下载最新发布的 zip 包，解压之后引用 `weui/dist/style/weui.min.css` 这个文件。
