### ISSUE TITLE
建议:cell支持多行描述

### ISSUE THREAD

**Issue by airyland** [weui/weui#210]
如图：

![image](https://cloud.githubusercontent.com/assets/559179/13066739/fb4d5200-d4a3-11e5-86bf-f001f419adb9.png)

**Comment by uxsi** [comment]
@airyland 这个效果现在的cell是支持的，需要自己手动加上多行提示。不同业务里面多行显示的文本样式不同，所以取舍之下并没有加上，只提供通用的结构哈

**Comment by airyland** [comment]
@uxsi 明白。不过在很多场景下这确实也是个通用结构。
