### ISSUE TITLE
建议：修改weui_card_access以支持a标签

### ISSUE THREAD

**Issue by adcentury** [weui/weui#213]
当使用`weui_card_access`时，一般会考虑添加在`<a>`标签上（实现类似微信图文消息的效果），建议增加支持。

**Comment by adcentury** [comment]
另外貌似现在也没有点击高亮的效果，同样建议增加 :)

**Comment by uxsi** [comment]
a标签下个提交会带上，现在card的内容以及所支持的场景还在讨论，这一两周会确定，也欢迎大家提议哈

**Comment by adcentury** [comment]
@uxsi 回复好快，哈哈，赞一个

类似于这种效果：
![tap-highlight](https://cloud.githubusercontent.com/assets/1651946/13071199/e3c6bfe4-d4cc-11e5-8505-78b9ee00ffa3.gif)

一种可能的是实现方式：
https://github.com/adcentury/weui/blob/adcentury/card-access/src/style/widget/weui_card/weui_card.less

供参考 ^ ^
