### ISSUE TITLE
时间控件

### ISSUE THREAD

**Issue by shijianchao** [weui/weui#215]
可以加入一些时间日期选择控件

**Comment by Javen205** [comment]
时间日期控件能灵活设置范围那就更好了   比如 工作日（周六周日不让选择）

**Comment by liniu** [comment]
时间控件可以参考SUI-Mobile的日期时间控件，感觉这样的操作方式挺方便的

**Comment by logoove** [comment]
http://weixin.yoby123.cn/weui/ 参考我的

**Comment by sklthegoodman** [comment]
日期控件在开发中，感谢关注。
