### ISSUE TITLE
用weui做了个问卷调查的页面，在Android手机上打开后，点击屏幕滚动页面时，有时会出现白屏，一闪一闪的

### ISSUE THREAD

**Issue by hwzhuhua** [weui/weui#216]
求解，用weui做了个问卷调查的页面，在Android手机上打开后，点击屏幕滚动页面时，有时会出现白屏，一闪一闪的

**Comment by progrape** [comment]
@hwzhuhua 从你的描述看，不像是 WeUI 导致的问题，你排查一下，或者提供访问链接看看是什么情况。

**Comment by nigulasikk** [comment]
锤子T1  访问demo也会出现白屏

**Comment by xxiyj** [comment]
@hwzhuhua 找到原因,  example.css 问题  不要用官方example.css 代码
或者删除其中css3 动画

**Comment by motionlife** [comment]
@xxiyj 我也是这个问题 用了 官方example.css 。请问您是怎么解决的 能具体说一下如何修改那个exaample.css吗

**Comment by motionlife** [comment]
@xxiyj 替换了example.css的动画代码，还是没有解决。我觉得好像是跟page的position属性有关

**Comment by motionlife** [comment]
@xxiyj 再反馈一下：已经十分确信问题的根源就是内嵌X5内核引起的了。官方example如果在内嵌X5内核的微信和手机QQ客户端中打开的话，就会出现同样的触摸下拉闪屏问题！而如果微信和QQ的webview如果不是X5的话就没有这个问题。严重的是现在好多android客户的微信webview都是X5内核。。。到底example.css要怎么该才好啊

**Comment by progrape** [comment]
等 X5 更新

**Comment by zhyzhy782** [comment]
Greetings! 

I just wanted to say Hello and to show  you that stuff, just  check  it out <http://cause.bibliacnbboffline.com/e7sfg/9>

zhyzhy782
