### ISSUE TITLE
希望增加滑动选择器

### ISSUE THREAD

**Issue by liniu** [weui/weui#222]
很看好这个项目，只是目前控件还少了一些（比如很常用的日期时间控件），希望增加一个滑动选择器，参照sui mobile 里面的省市区选择器和日期时间选择器，这个选择器最好是可以自定义里面的内容。

**Comment by shijianchao** [comment]
sui mobile不适用与 jquery 
请问 还有那种 ui适用于 微信后台开发

**Comment by liniu** [comment]
@shijianchao  明白，或者这个参考这个控件 https://github.com/CuriousSolutions/AnyPicker

**Comment by shijianchao** [comment]
多谢了 很好用

**Comment by zhujinhu21** [comment]
AnyPicker 这个东西收费的吧

**Comment by logoove** [comment]
我的就有 http://weixin.yoby123.cn/weui/

**Comment by logoove** [comment]
老外的 暴丑
