### ISSUE TITLE
commit 9e113e1 导致js_container中default page 被 append 两次

### ISSUE THREAD

**Issue by xalexec** [weui/weui#224]
example.js 42行
-if((url === '#' + self._defaultPage) || !page){
+if((url === '#' + self._defaultPage) || (url === '#') || !page){
不提交pr了

**Comment by xalexec** [comment]
<img width="385" alt="2016-02-19 12 34 32" src="https://cloud.githubusercontent.com/assets/3349091/13150397/93d914f2-d6a0-11e5-931d-842e92be327c.png">

**Comment by progrape** [comment]
thanks~

**Comment by progrape** [comment]
#223
