### ISSUE TITLE
点击延迟问题

### ISSUE THREAD

**Issue by JasonZhao18** [weui/weui#227]
Click的时候延迟影响体验，是否可以用touch取代click

**Comment by graysheeep** [comment]
fastclick就可以了吧

**Comment by mlyknown** [comment]
用了fastclick 还是会有延迟，部分安卓机，我用得vuejs，不知道和这个有没得关系~~

**Comment by progrape** [comment]
用了 fastclick 之后，延迟效果会有所改善，应该在具体的项目中使用，UI 库本身就不用了
