### ISSUE TITLE
npm 的weui 的css版本和git的版本不一致

### ISSUE THREAD

**Issue by Neallin** [weui/weui#234]
css文件的注释都是
/*!
 * WeUI v0.3.0 (https://github.com/weui/weui)
 * Copyright 2016 Tencent, Inc.
 * Licensed under the MIT license
 */

但是里面的内容不一致。

.weui_cells_form input,
.weui_cells_form textarea,
.weui_cells_form label[for] {
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}

eg:这个在npm拉回来的package里面没有。

**Comment by progrape** [comment]
@Neallin npm 上面的版本是定期发布的，目前的最新版本 0.3.0 是 1 月 22 日发布。而你从 github clone 下来的代码是最新的，从上次发布至今，github 上的代码是有新增的，所以你看到 github 的最新代码和 npm 的不一致。
