### ISSUE TITLE
对话框会被页面中的富文本框遮盖

### ISSUE THREAD

**Issue by lanbaba** [weui/weui#239]
当页面中有富文本框，比如百度Ueditor时，对话框会被富文本框遮盖。即使修改弹出对话框的z-index，依然不太理想，最好是当对话框弹出来时，背景页面的富文本框也是变灰的。

![富文本框遮盖弹出对话框](http://7xnec8.com1.z0.glb.clouddn.com/6B77D4BA-36F1-4300-AE04-C64574704C7B.png)

**Comment by progrape** [comment]
#182

**Comment by lanbaba** [comment]
需要调整两个地方，对话框的mask的z-index调至大于999，因为ueditor的z-index是999，弹出层的z-index要调至大于mask的z-index。
`<div class="weui_mask" style="z-index: 9998;"></div>
     <div style="z-index: 9999;" class="weui_dialog">`
