### ISSUE TITLE
单选列表项扩展

### ISSUE THREAD

**Issue by cenxun** [weui/weui#240]
添加一个可以输入的选项！

如图 
![image](https://cloud.githubusercontent.com/assets/5516946/13453646/afaa8f30-e08c-11e5-9767-827f992ff9e1.png)

**Comment by progrape** [comment]
@cenxun 利用现有的组件，可以构建出这样的界面，看看能不能满足你的需求。

代码在这里，http://codepen.io/progrape/pen/oxXQEM

![image](https://cloud.githubusercontent.com/assets/4652816/13496519/9c13eade-e18b-11e5-936f-31df786fc516.png)

**Comment by cenxun** [comment]
这样也行，不过没选中标志，主要是想着库能不能添加这个，谢咯
