### ISSUE TITLE
父级设置height: 100%时使用weui_cells_title会出现滚动条

### ISSUE THREAD

**Issue by linayanse** [weui/weui#244]
示例页**tab**就出现了这个问题，建议将**weui_cells_title**中的**margin-top**修改为**padding-top。**

**Comment by progrape** [comment]
@linayanse 谢谢反馈，出滚动条是因为设置了高度 100% ，这是不需要的，先去掉 100% 来消除滚动条。暂时没有特别的需求需要更改 `weui_cells_title` 的 `margin-top` 为 `padding-top`，就先不改这里。
