### ISSUE TITLE
微信的缓存机制是基于什么样的

### ISSUE THREAD

**Issue by Phragmites** [weui/weui#246]
某些get请求会被缓存

**Comment by cnyyk** [comment]
不仅是get。页面一定会呗缓存。有时候公众号实测，不得已只有删除重新关注从新进。有时候甚至只有清掉微信的数据。重新登录。

**Comment by progrape** [comment]
@Phragmites 旧的 X5 内核不详，即将升级的新 X5 是标准的浏览器缓存策略~
