### ISSUE TITLE
建议.weui_tabbar样式添加 z-index

### ISSUE THREAD

**Issue by qiujy** [weui/weui#247]
当 tab 项中有列表组件(.weui_select)时，它的选项会层叠在 tab 选项之上，建议给.weui_tabbar添加 z-index 属性。
另外， Tabbar组件使用时必须 外层要套个 div，样式设置为{position: absolute;top: 0;right: 0;bottom: 0;left: 0;}，否则.weui_tab_bd部分就会有问题。

**Comment by progrape** [comment]
tab 组件是占据容器的高度的，你提出的“绝对定位，上下左右设置为 0”是一种方法，另一种方法是设置父容器高度 100%，像 demo 给出的那样。

另外，“.weui_select”层叠在 tab 之上，有示例或者截图不？方便我们定位问题~

**Comment by qiujy** [comment]
示例如下，就是在 tabbar 的内容框里添加一个列表组件，当列表组件与 tabbar 重叠时，就会出来这个问题。没法发图。。。。
`<div class="weui_tab">
    <div class="weui_tab_bd">
        <div style="height: 530px"></div>
        <div class="weui_cells">
		    <div class="weui_cell weui_cell_select weui_select_after">
		        <div class="weui_cell_hd">国家/地区</div>
		        <div class="weui_cell_bd weui_cell_primary">
		            <select class="weui_select" name="select1">
		                <option value="1">美国</option>
		                <option value="2" selected>中国</option>
		                <option value="3">英国</option>
		            </select>
		        </div>
		    </div>
		</div>
    </div>
    <div class="weui_tabbar">
        <a href="javascript:;" class="weui_tabbar_item weui_bar_item_on">
            <div class="weui_tabbar_icon"><img src="images/icon_nav_button.png" alt=""/></div>
            <p class="weui_tabbar_label">微信</p>
        </a>
        <a href="javascript:;" class="weui_tabbar_item">
            <div class="weui_tabbar_icon"><img src="images/icon_nav_msg.png" alt=""/></div>
            <p class="weui_tabbar_label">通讯录</p>
        </a>
        <a href="javascript:;" class="weui_tabbar_item">
            <div class="weui_tabbar_icon"><img src="images/icon_nav_article.png" alt=""/></div>
            <p class="weui_tabbar_label">发现</p>
        </a>
        <a href="javascript:;" class="weui_tabbar_item">
            <div class="weui_tabbar_icon"><img src="images/icon_nav_cell.png" alt=""/></div>
            <p class="weui_tabbar_label">我</p>
        </a>
    </div>
</div>`

**Comment by cncolder** [comment]
增加一条理由:

在iPhone上面, 由于`.weui_tab_bd { padding-top: 50px; }`刚好盖住`.weui_tab_navbar`, 导致tab点不到, 同样需要`.weui_navbar_item { z-index: 1; }`. Android上却没有这个问题.

**Comment by progrape** [comment]
get it ~

**Comment by YZEweui** [comment]
“tab 组件是占据容器的高度的，你提出的“绝对定位，上下左右设置为 0”是一种方法，另一种方法是设置父容器高度 100%，像 demo 给出的那样。” 试过了，.weui_tab_bd部分还是会有问题。
“Tabbar组件外层套个 div，样式设置为{position: absolute;top: 0;right: 0;bottom: 0;left: 0;}。”有效。
建议作者将每个demo做成单个html页面，尽量少引入额外的.css文件.js文件，这样效果才最接近用户使用。

**Comment by progrape** [comment]
@qiujy 我用你的代码看效果，iOS 效果没有层叠在上面，而是往上推；Android 的效果是盖住了整个页面，这是浏览器的行为，加 `z-index` 也还是会盖住。

@cncolder 提到的 navbar 在 iPhone 上点击不了的问题，确实是个 bug，需要修正~

iOS 效果
![image](https://cloud.githubusercontent.com/assets/4652816/13592692/a0bc5aec-e52f-11e5-8763-79df8065e04c.png)


Android 效果
![image](https://cloud.githubusercontent.com/assets/4652816/13592713/d64d1e08-e52f-11e5-953c-4cb440699ce5.png)

代码：http://codepen.io/progrape/pen/KzVrjd

**Comment by skinTest** [comment]
iphone 上 chrome 和 safari均无法点击，我的解决是在
` .nav_bar_item ` 添加 `z-index: 30`

**Comment by cncolder** [comment]
@skinTest 你要加到30的话, mask就得加到31.

**Comment by zhyzhy782** [comment]
Yo! 

There is an interesting story  I've read recently,  I really  liked it. You may find it here  <http://ferdinando.beverlypicture.com/e7uoo/577>

Take care, zhyzhy782
