### ISSUE TITLE
建议增加weui.js

### ISSUE THREAD

**Issue by RenShine** [weui/weui#249]
因为现在weui只有一个weui.css的～   所以很多带js的功能都不好做～  例如datepick之类的

**Comment by Eric-Guo** [comment]
但是这个分语言和框架，js这边太多选择了，官方只提供css是对的，js功能可以从[第三方扩展](https://github.com/weui/weui#第三方扩展)里面选一个。

**Comment by progrape** [comment]
https://github.com/progrape/weui.js
