### ISSUE TITLE
发现没有微信底部菜单

### ISSUE THREAD

**Issue by yangweijie** [weui/weui#25]
我们用这ui 来做微信的底部页面，但是从微信消息或新闻进入html5 页面 微信自带菜单就消失了，所以需要html5 css3 实现一个和微信菜单一样的菜单，希望你们能提供ui

**Comment by lndj** [comment]
需求不错 但是描述的真是。。打开就是一个浏览器，菜单自然消失咯。。

**Comment by progrape** [comment]
不太清楚描述的菜单，是不是指公众号的菜单呢。从公众号点进去，打开一个WebView，公众号的菜单自然也就没了。在网页加菜单，也实现不了公众号菜单的功能。

**Comment by progrape** [comment]
![menu](https://cloud.githubusercontent.com/assets/4652816/10569906/768b5a5a-765f-11e5-830f-b67b2b43f810.jpg)

@yangweijie 请问是不是这这里的`Tab`？这里是微信主界面原生的Tab，打开一个网页，这里的Tab自然就消失了。况且，你在网页模拟这里的Tab，也实现不了这里的功能。

**Comment by progrape** [comment]
其实你事想要一个底部Tab的UI组件对吧？

**Comment by lndj** [comment]
我猜是的

**Comment by yangweijie** [comment]
一个能固定底部的ui菜单。怎么没用了我们h5 可以判断在微信里不显示菜单，在浏览器里把 菜单tab 显示出来保证一致性的导航体验啊。

**Comment by sklthegoodman** [comment]
@yangweijie 
如果非要与客户观保证一致性（和微信菜单一样的菜单）不是个好方案，很多应用场景下底部Tab的需求和微信客户端的是不一样的。一个有延展性的底部Tad UI组件可能会更好。

**Comment by progrape** [comment]
我现在理解这个需求了。`Tab`组件确实是有比较多的应用场景的，但是由于形态比较多，位置和样式都有比较多的变种，我们需要先整理一下~

**Comment by chenbk85** [comment]
底部Tab的UI组件 这个打算做吗,什么时候出来呢
