### ISSUE TITLE
是不是没有  下拉刷新 ，上拉加载更多，大图预览 功能啊？

### ISSUE THREAD

**Issue by LiZheWang** [weui/weui#250]
预览大图 时能左右滑动，能pinch 放大缩小 。

**Comment by Samlv9** [comment]
@LiZheWang 大图浏览为什么不用 wx.previewImage?

**Comment by LiZheWang** [comment]
@Samlv9   手机站也会在浏览器中打开的

**Comment by logoove** [comment]
手机站一般屏蔽电脑打开 微信jssdk提供的就很好
