### ISSUE TITLE
没看到输入框控件呀。

### ISSUE THREAD

**Issue by evilbinary** [weui/weui#251]
没看到输入框控件呀。

**Comment by progrape** [comment]
@evilbinary input、textarea、select 等目前在 Cell 类里面，可以在 http://weui.github.io/weui/#cell 往下一点看到示例 demo

![image](https://cloud.githubusercontent.com/assets/4652816/13521414/45979fc8-e223-11e5-96f6-a35bfe6061ab.png)

**Comment by evilbinary** [comment]
好的谢谢。
