### ISSUE TITLE
安卓系统不支持flex

### ISSUE THREAD

**Issue by DRL9** [weui/weui#252]
安卓系统下，display:flex不支持，改为display:-webkit-flex也一样。
请问还有人遇到这问题吗

**Comment by progrape** [comment]
@DRL9 目前微信 Android 客户端中的 Webview 是 x5 内核的，经测试，支持部分 flex 的特性，但要用旧的写法，容器 `display: -webkit-box;`，子元素 `-webkit-box-flex: 1;` 。

推荐使用 [autoprefixer](https://github.com/postcss/autoprefixer) 来自动补全。

这里有个简单的示例：

http://codepen.io/progrape/pen/RaWabo

![image](https://cloud.githubusercontent.com/assets/4652816/13521315/7fb53cd4-e222-11e5-84b7-46f6ecfc90e5.png)

**Comment by Samlv9** [comment]
@progrape 是的，但是 flex-wrap 是不行的，-webkit-box 没有换行。这个支持仅仅是支持单行内的 flex。

**Comment by transtone** [comment]
安卓微信要大更新了。这不是自绝于人民吗。
