### ISSUE TITLE
iPhone4s上内容被截掉了

### ISSUE THREAD

**Issue by ydcss** [weui/weui#256]
iPhone4s上内容被截掉了

**Comment by opendever** [comment]
测试时，我也碰到这种情况，显示不全，不能向下滚动。有时候刷新页面可以显示完整，有时候不行。

**Comment by opendever** [comment]
@progrape 官方的demo也是一样情况

**Comment by gaolinjie** [comment]
我在iPhone6 plus上也是这样的呢，cell页面下半部分的内容都没法显示出来，android上就可以

**Comment by gaolinjie** [comment]
@progrape

**Comment by opendever** [comment]
@gaolinjie https://github.com/weui/weui/issues/216 我删掉动画效果后就正常了
