### ISSUE TITLE
Router in wechat webview

### ISSUE THREAD

**Issue by Huxpro** [weui/weui#26]
Hey, nice work guys.

我注意到你们使用 `history.pushState()` 实现了简单的路由，我在微信 webview 中测试了一下，有一个问题有点奇怪：**使用微信 webview 上方的 Back 和使用“屏幕边缘左滑返回” 的效果完全不一样**

当使用 Webview Back 时，所有的路由都很正常
但当通过屏幕边缘左滑返回时，路由好像失效了，直接退出了整个 webview。

我发现好像所有使用 `pushState` 实现路由的 web app 都有这个问题，
但是使用原始的 `locatin.hash` & `hashchange` 做路由的却没有这个问题……

但是它们确实都给 `history.length` +1 了……
是微信 webview 做了什么处理吗？还是 `pushState` 的表现在 iOS WebView 上本来有有不同？（Safari 是没有这个问题的）

**Comment by progrape** [comment]
@Huxpro 这个问题我们也留意到的，只是没有去深究。今天咨询了客户端开发的同事，**屏幕边缘左滑返回**，是实现监听了WebView的[webView:shouldStartLoadWithRequest:navigationType:](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebViewDelegate_Protocol/#//apple_ref/occ/intfm/UIWebViewDelegate/webView:shouldStartLoadWithRequest:navigationType:)事件，触发了这个事件就会做类似于`history.lenght + 1`的操作，然后就可以**屏幕边缘左滑返回**。

调试发现，`location.href`和`location.hash`这两种方式都可以触发到该事件，然而`pushState`却没有触发，因此`pushState`后滑动，就直接关闭了WebView了

**Comment by progrape** [comment]
@Huxpro 感谢关注，这个问题之前也留意到了，但是没有深究。昨天咨询iOS客户端同事**屏幕边缘左滑返回**的原理，是客户端监听[webView:shouldStartLoadWithRequest:navigationType:](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebViewDelegate_Protocol/#//apple_ref/occ/intfm/UIWebViewDelegate/webView:shouldStartLoadWithRequest:navigationType:)事件，如果有触发该事件，就会做类似于`history.length + 1`的操作，然后就可以右滑返回。

调试发现，`locatin.hash='#hash1'` 和`location.href = 'http://...'`两种方式都可以触发到，但是`pushState`的方式却触发不到，所以就滑动就直接关闭而不是返回了。客户端同事正在尝试解决~

今天发现有人问相同的问题[http://stackoverflow.com/questions/33210121/html5-pushstate-not-trigger-shouldstartloadwithrequest](http://stackoverflow.com/questions/33210121/html5-pushstate-not-trigger-shouldstartloadwithrequest) :grin:

目前demo页面改成设置hash的方式，可以滑动返回

**Comment by Huxpro** [comment]
@progrape 非常感谢如此周到的解答！
建议这个 issue 更名为 “Router with pushState in Wechat webview” 并保持 open 的状态；非常期待这个问题以后的进展！

**Comment by lynn328** [comment]
有个情况，和**路由**和**幕边缘左滑返回** 这两个操作相关：
背景：
    用原始的 locatin.hash & hashchange 做路由
    iOS 8.4  +  微信 6.3.9
    有3级路由页面（first > second > third 顺序进入各级界面）
情况：
    在third界面时，用**幕边缘左滑返回**会短暂闪过first的画面，然后才显示second，
    但此时，再次**幕边缘左滑返回**，直接退出了webview（本应显示first）。

使用webview Back来返回，则全部正常，不会像上面一样丢失first界面。

**Comment by lijijordan** [comment]
rooter.js 是微信实现的么？还是用的开源的？

**Comment by progrape** [comment]
@lijijordan router.js 是我们为了呈现 demo 简单写的，源码单独存放在这里 https://github.com/progrape/router 。目前功能比较单一，仅满足我们的 demo 使用，生产环境推荐使用更专业的路由。

**Comment by bsnwong** [comment]
请问如果使用其他框架该出现这种情况该怎么去解决呢，我用的是Framework7，但微博、Safari不会出现这个问题，微信就会

**Comment by JasonLisa** [comment]
#515 # @ @lijijordan

**Comment by qingdie** [comment]
我反复测试发现，连续打开3个窗口后，侧滑返回只能两次，在第3个窗口侧滑时看到的是第一个窗口的图像，侧滑完成后页面突然变成了第二个窗口，再次侧滑页面关闭了，应该是返回第一个窗口，
但是点击顶上的返回按钮就一切都正常！

**Comment by qingdie** [comment]
从第3个窗口侧滑返回到第二个窗口时，再侧滑没有了，但是顶上返回键点击有效，
