### ISSUE TITLE
tabbar控件异常

### ISSUE THREAD

**Issue by YZEweui** [weui/weui#261]
在demo中tabbar能够将bar控件正常显示在底部，但是自己写个测试程序按照说明，加入weui.css之后，且设置了 class="bd" style="height:100%;"，tabbar的bar并不能自动显示在底部，而是显示在顶端。
希望作者能将每一个demo做成单个html页面，要是能少引入如example.css等其它额外文件就更好了，这样更能照顾初学者。万分谢谢。

**Comment by YZEweui** [comment]
测试程序代码：
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="adb">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
    <title>WeUI</title>
    <link rel="stylesheet" href="../style/weui.css"/>
</head>
<body>
    <div class="bd" style="height: 100%;">
        <div class="weui_tab" >
            <div class="weui_tab_bd">

            </div>
            <div class="weui_tabbar">
                <a href="javascript:;" class="weui_tabbar_item weui_bar_item_on">
                    <div class="weui_tabbar_icon">
                        <img src="./images/icon_nav_button.png" alt="">
                    </div>
                    <p class="weui_tabbar_label">微信</p>
                </a>
                <a href="javascript:;" class="weui_tabbar_item">
                    <div class="weui_tabbar_icon">
                        <img src="./images/icon_nav_msg.png" alt="">
                    </div>
                    <p class="weui_tabbar_label">通讯录</p>
                </a>
                <a href="javascript:;" class="weui_tabbar_item">
                    <div class="weui_tabbar_icon">
                        <img src="./images/icon_nav_article.png" alt="">
                    </div>
                    <p class="weui_tabbar_label">发现</p>
                </a>
                <a href="javascript:;" class="weui_tabbar_item">
                    <div class="weui_tabbar_icon">
                        <img src="./images/icon_nav_cell.png" alt="">
                    </div>
                    <p class="weui_tabbar_label">我</p>
                </a>
            </div>
        </div>
</div>

</body>
</html>

**Comment by progrape** [comment]
@YZEweui 这里有个单独的 tabbar 的 demo，http://codepen.io/progrape/pen/dMMLVj
