### ISSUE TITLE
使用输入法时tabbar会挡住输入框

### ISSUE THREAD

**Issue by jinhucn** [weui/weui#262]
使用输入法时tabbar会挡住输入框。
一般的输入法都是从底部弹出来的，tabbar会随着输入法的弹出而上升，导致输入框被遮盖。
![screenshot_2016-03-10-09-50-05](https://cloud.githubusercontent.com/assets/7019006/13656965/55de4cf6-e6a6-11e5-9e15-fb7e51a46039.png)
未弹出输入框界面
![screenshot_2016-03-10-09-50-49](https://cloud.githubusercontent.com/assets/7019006/13656972/5fa019fe-e6a6-11e5-8628-bf1c41f11a21.png)
弹出输入框后的界面

**Comment by progrape** [comment]
Android ？

**Comment by itohok** [comment]
华为表示无压力

**Comment by jinhucn** [comment]
Android 6.0
huawei mate 7

**Comment by itohok** [comment]
荣耀7，没问题

**Comment by jinhucn** [comment]
浏览器中未弹出输入框界面
![screenshot_2016-03-10-10-03-19](https://cloud.githubusercontent.com/assets/7019006/13657128/c3a6c9e2-e6a7-11e5-87d8-949c0dea2701.png)
浏览器中弹出输入框后界面

**Comment by skinTest** [comment]
psuedo code
```js
$('body').focus(function () {
  // whatever the tag name api
  event.target.tagName === 'input' && $('#ur_tabbar').css('position', 'relative'
}).blur(function () {
  event.target.tagName === 'input' && $('#ur_tabbar').css('position', 'absolute')
})
```

**Comment by mlyknown** [comment]
https://segmentfault.com/q/1010000004716184
