### ISSUE TITLE
tabbar 与 iconfont

### ISSUE THREAD

**Issue by transtone** [weui/weui#266]
用iconfont和tabbar如何配合？ 微信自己不用图片形式的图标也好久了吧。想实现一下目前微信tabbar的样式。 另外在截图里看到每个页面都有header，却没找到header组件和使用方法，可否帮忙提供一下？

**Comment by progrape** [comment]
@transtone tabbar 可以使用字体图标的，不过需要你自己设置图标大小和颜色。这里有个示例：http://codepen.io/progrape/pen/dMMLVj

另外，你提到的 header，不是 WeUI 组件的一部分，只是我们呈现 demo 用的而已，在 `example.css` 中定义的 `.page_title` 和 `.page_desc`。

**Comment by transtone** [comment]
为何不将其内置到weui.css，而要自己设置字体大小呢。
```
.weui_tabbar_icon{
    text-align: center;
}
.weui_tabbar_icon  i{
    color: #999;
}

.weui_tabbar_item {
    padding:0 0 2px;
}
.weui_bar_item_on .weui_tabbar_icon  i{
    color: #09BB07;
}
.weui_tabbar_icon  i{
    font-size: 24px;
}
```

**Comment by cnyyk** [comment]
这个是小问题，自己引入就可以了。
