### ISSUE TITLE
Cells' bottom border is missing on Firefox

### ISSUE THREAD

**Issue by airyland** [weui/weui#267]
![image](https://cloud.githubusercontent.com/assets/559179/13659553/ad88f9da-e6bd-11e5-8933-1f5f7967c2a7.png)

**Comment by uxsi** [comment]
@airyland weui在firefox下只保证可用，完整效果需对firefox做适配，可以重新设置`transform-origin为50% 50%`

**Comment by airyland** [comment]
Thx，暂时也没有找到更好的办法。
