### ISSUE TITLE
cell 的一些建议

### ISSUE THREAD

**Issue by dsky1990** [weui/weui#268]
能不能修改下weui_cell_primary的样式，weui_cell_ft文字内容过长的时候weui_cell_primary内的文字会竖着排列

**Comment by uxsi** [comment]
@dsky1990 weui_cell_primary作弹性布局，就是这个表现哈，如果需要weui_cell_primary内容不换行，可以对weui_cell_primary的内容定义宽度，类似weui_form里面的weui_label

**Comment by dsky1990** [comment]
@uxsi 嗯，这个我已经处理了，就是看看能不能有通用的解决办法，还是谢谢啦
