### ISSUE TITLE
weui for OmniGraffle Stencil 有人需要吗？我做了一份，不知道大家是不是需要。

### ISSUE THREAD

**Issue by chonchoi** [weui/weui#270]
![image](https://cloud.githubusercontent.com/assets/7456582/13721471/7966c87e-e863-11e5-980f-aea6b231164d.png)

**Comment by TonyRenHK** [comment]
需要~

**Comment by chonchoi** [comment]
@TonyRenHK  上传好了 https://github.com/chonchoi/weui-for-OmniGraffle
