### ISSUE TITLE
input type="number"时maxlength不起作用

### ISSUE THREAD

**Issue by kpsanmao** [weui/weui#274]
input type="number"时maxlength不起作用

**Comment by scott-leung** [comment]
这个不是weui的问题

**Comment by progrape** [comment]
@kpsanmao 参考 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-maxlength

> If the value of the type attribute is text, email, search, password, tel, or url, this attribute specifies the maximum number of characters (in Unicode code points) that the user can enter; for other control types, it is ignored.
