### ISSUE TITLE
非常非常感谢WEUI的开发团队，希望能再增加点模块（详见说明）

### ISSUE THREAD

**Issue by ypsce** [weui/weui#277]
1，能自定义布局的表格UI支持
2，另外如果可以的话更希望提供统计图表类的UI
现在的用户体验至高无上，如果有这些东西的支持，那么我们大家开发的产品又会上升一个档次了，O(∩_∩)O~

**Comment by zcoding** [comment]
统计图表这种应该做到插件里面吧，一般由第三方提供。如果整合到WeUI就太大了。

**Comment by logoove** [comment]
统计图 一般不实用 实在需要直接插件
