### ISSUE TITLE
date 类的input显示不全

### ISSUE THREAD

**Issue by Shawn-Aaron** [weui/weui#279]
date 类的input在苹果上能正常显示，在安卓上面只能显示上半部分

**Comment by progrape** [comment]
@Shawn-Aaron 我们测试了两部 Android，date 类型的 input 没有出现你提的只能显示上半部分的 bug。可否提供更详细的信息？

![image](https://cloud.githubusercontent.com/assets/4652816/14071383/a497fa9c-f4e6-11e5-8313-14b85cc73719.png)

![image](https://cloud.githubusercontent.com/assets/4652816/14071388/bc294102-f4e6-11e5-990b-7f2ee537f5dd.png)

**Comment by Shawn-Aaron** [comment]
@progrape  前两天经过一步步排查发现是页面引入的其他样式与weui产生了冲突，更改后没有问题，抱歉，忘了及时更新信息了。

**Comment by progrape** [comment]
:+1:
