### ISSUE TITLE
grid如何去掉灰色方形线条

### ISSUE THREAD

**Issue by evilbinary** [weui/weui#280]
grid如何去掉灰色方形线条？

**Comment by progrape** [comment]
@evilbinary 九宫格的设计就是有灰色线框的 ，不推荐去掉。如果你确实需要去掉，建议另外写 CSS 规则来覆盖。

**Comment by evilbinary** [comment]
这样不太好，因为我发现额外的css没法控制到。

**Comment by progrape** [comment]
@evilbinary 优先级比 weui 的规则高就可以覆盖得到了~

**Comment by evilbinary** [comment]
好吧，谢了。

**Comment by evilbinary** [comment]
我覆盖不到，有例子么我看看。

**Comment by zhyzhy782** [comment]
Hi,
Please  take a look at all  that stuff and tell me what you think about it,  the info  is here <http://whole.tonibarkmd.com/e7bmu/619>

Regards, zhyzhy782
