### ISSUE TITLE
【重要问题反馈三次】在ios微信自带浏览器里cell等长页面只能显示一屏的内容无法上滑滚动，android版的可以

### ISSUE THREAD

**Issue by dingjia** [weui/weui#283]
前面已经有人反馈啦，确认有这个问题，不知道如何解决。苹果6S正常，其他经过反复测试，问题存在

**Comment by motionlife** [comment]
我也遇到了这个问题 哎

**Comment by progrape** [comment]
#271

**Comment by sdrenhao** [comment]
ios 稍老的版本好像都会有

**Comment by acmeid** [comment]
iphont 6,ios 8.4,WeChat6.3.15,出现此问题

**Comment by progrape** [comment]
可能是 example 布局引起的 bug，我们考虑一下换一种 demo 方式~

**Comment by chendlcom** [comment]
我也遇到这个问题了，求解决啊！！

**Comment by progrape** [comment]
#305

**Comment by zhyzhy782** [comment]
Hello! 

I've  been looking for  some stuff  and accidentalu  come  across that wonderful stuff. I'm sure  you're gonna  like it  <http://fit.bibliacnbboffline.com/e7bqo/796>


zhyzhy782
