### ISSUE TITLE
Tabbar 出现一条灰线

### ISSUE THREAD

**Issue by CarmenHYC** [weui/weui#285]
Tabbar 的 .weui_tab_bd 里，放了一个搜索栏后，下边放入内容超过一屏，往上滑动内容，会看到有一条灰线，目前只发现在微信浏览器里有这个问题。

**Comment by 1EDcom** [comment]
Ｅｒ，ｙｏｕ　　ａｒｅ　ｒｉｇｈｔ．

**Comment by 1EDcom** [comment]
ｂｕｘｉｎｇ

**Comment by 1EDcom** [comment]
ｂｕｘｉｎｇ
