### ISSUE TITLE
weui-fixed640基于官方版本，改造了一版适用于固定宽度为640的适配方案的weui

### ISSUE THREAD

**Issue by lidianhao123** [weui/weui#286]
https://github.com/lidianhao123/weui-fixed640
WeUI-fixed640 基于WeUI修改的，适用于将屏幕的宽度设定为固定640px值的适配方案。
<meta name="viewport" content="width=640, user-scalable=no, target-densitydpi=device-dpi">

**Comment by progrape** [comment]
:+1:
