### ISSUE TITLE
toast 只有 loading 和 success，没有 warn 和 info

### ISSUE THREAD

**Issue by holymonson** [weui/weui#287]
icon 里的图标因为大小和颜色的原因，不能直接放到 toast 上，所以专门有一个 `weui_icon_toast` （实现上就是放大版的 success）。可是不能永远都成功呀，需要有提示和警告的 toast 图标。

**Comment by uxsi** [comment]
@holymonson 谢谢反馈，toast除了现有的成功、等待状态外，还会提供警告、失败等其它的，已在排期队列中

**Comment by YouYII** [comment]
然而两年过去了
