### ISSUE TITLE
期望官方能出富文本编辑器

### ISSUE THREAD

**Issue by atjs** [weui/weui#291]

**Comment by airyland** [comment]
:open_mouth: 为什么手机web页面会有富文本编辑器的需求

**Comment by Beennnx** [comment]
哈哈哈  对啊 适用于手机甚至微信的组件为什么要符文本编辑器呢。

**Comment by progrape** [comment]
手机上不会大规模码字吧？有富文本编辑器的需求？

**Comment by logoove** [comment]
暖用

**Comment by a233894432** [comment]
富文本编辑器 真心没什么用...有那个心思...还不如用PC去发了

**Comment by zhyzhy782** [comment]
Hey,
Just take  a look  at that stuff, it is  so amusing and funny, check  it  out <http://prime.rayscruiseblog.com/e7zug/135>

Cheers, zhyzhy782
