### ISSUE TITLE
表示性能很差，无法用于生产环境

### ISSUE THREAD

**Issue by sharpmoons** [weui/weui#292]
企业原本想利用WeUI进行企业微信公众号开发
展示商品列表一步 100个产品显示，发现滚动时非常卡顿！
之后运行 WEUI原带Demo发现cell页面也是有卡顿情况。

**Comment by sharpmoons** [comment]
腾讯的UI技术不过如此~ 与百度的Ueditor 一样 问题太多~

**Comment by airyland** [comment]
额，上个demo更有说服力吧。我没有遇到过卡顿，甚至严重卡顿的情况。

**Comment by sharpmoons** [comment]
@airyland   您可以在安卓机器上 访问 cell子页面内容 代码 复制2次，保存  滑动体验一番。

**Comment by justinyaoqi** [comment]
确实非常卡顿

**Comment by progrape** [comment]
请阁下提供机型、微信客户端版本和卡顿的代码？另外，你试试不用 weui，在列表内放 100个贵司的产品，看看会不会卡顿？weui 和 ueditor 问题这么多，请阁下不吝发 PR 来完善一下，提升性能，造福开发者？

**Comment by sharpmoons** [comment]
@progrape   你好，我个人可能一时情绪，言辞有所过激，不过确实是卡顿的。

机型 三星 note3 ，努比亚。

卡顿代码 ：Cell模块源码 就已经卡顿，主要原因应该是sample.css 和sample.js 引起的 
计算滚动的性能问题。

**Comment by cnyyk** [comment]
我用pro5。暂未遇到卡顿。但是组件不够用。

**Comment by motionlife** [comment]
问题的根源就是内嵌X5内核引起的了。官方example如果在内嵌X5内核的微信和QQ手机客户端中打开的话，就会出现同样的触摸下拉闪屏卡顿问题！而如果微信和QQ的webview如果不是X5的话就没有这个问题。严重的是现在好多android客户的微信webview都是X5内核。。。那些一直讲提供demo的同学，您难道没跑过官方example吗

**Comment by airyland** [comment]
@motionlife 
我确实没有在Android下跑过官方example

前端页面复杂，在问题未确定的情况下，问题来源可能是其他，维护一个开源项目(我不是weui的维护者)不可能在没有demo的情况下猜出是什么问题，反馈问题时顺便提供demo或者说明使用方式方便重现我觉得没什么问题。

上面 progrape 这样说我觉得完全是因为 sharpmoons 开issue就<del>带着情绪指责某讯和某度一样技术渣</del>(这一句阅后删)。

说到具体问题，我拿了两台机测试，其中一台确实闪烁严重，不止在cell页面，只要出现滚动条的页面就会闪烁。另外一台有轻微的类似问题。在其他浏览器不会出现类似问题。

官方说X5到4月就完全升级到Blink了，应该可以解决一些X5的问题了。

**Comment by jiangtiger** [comment]
魅族PRO5表示没有出现卡顿现象，比较流畅

**Comment by xxcanghai** [comment]
魅族MX3， cell页面确实非常卡顿，而且经常下拉，直接把整个网页黑色底部拉出来，体验很差

**Comment by xxcanghai** [comment]
滚动下拉露底截图：
http://ww2.sinaimg.cn/large/ebc0cd11jw1f2h685v4l2j20u01e0782.jpg
