### ISSUE TITLE
panel的weui_media_title长度过长会使左边的图片不显示

### ISSUE THREAD

**Issue by wzlee** [weui/weui#294]
![image](https://cloud.githubusercontent.com/assets/4182865/14076582/78325158-f515-11e5-8f06-508d4fa7ce84.png)
![image](https://cloud.githubusercontent.com/assets/4182865/14076589/90984874-f515-11e5-8cc4-e11fb7015691.png)

**Comment by ZoomZhao** [comment]
#258
