### ISSUE TITLE
微信的JS接口是不是完全改版了，为什么在JSSDK里没有你说的内容

### ISSUE THREAD

**Issue by HelloLeeChan** [weui/weui#296]
类似`WeixinJSBridge.invoke`好像在微信JSSDK里没有，这微信的文档真挺看不明白的

**Comment by GTX990TI-BOOST** [comment]
just a test, a new developer.

**Comment by progrape** [comment]
@HelloLeeChan 微信提供的 sdk，http://res.wx.qq.com/open/js/jweixin-1.0.0.js 是对 `WeixinJSBridge.invoke` 等一系列方法的封装，方便调用。

另外，发 issue 之前，不妨平复一下心情，描述好你的问题，让别人没有经历和你一样的问题，也能够理解你想表达是什么。
