### ISSUE TITLE
confirm弹出框内的文字能不能居中？

### ISSUE THREAD

**Issue by zaxlct** [weui/weui#297]
![image](https://cloud.githubusercontent.com/assets/14342431/14095217/85abf9d0-f590-11e5-8c09-d031ef1e14f2.png)

**Comment by uxsi** [comment]
@zaxlct weui dialog的内容后面都会改成是居中的对齐方式，现网版本暂时只能自己改

**Comment by Craft24** [comment]
不要吧，并不是都要居中的吧

**Comment by zaxlct** [comment]
> 不要吧，并不是都要居中的吧

不居中太丑了

**Comment by mqliutie** [comment]
这强迫症- -
