### ISSUE TITLE
dist\example\index.html 用chrome浏览器打开显示空白

### ISSUE THREAD

**Issue by freelancer13** [weui/weui#302]
如题
什么都看不见……49.0.2623.110

**Comment by freelancer13** [comment]
补充：在 微信web开发者工具 里打开该页面，也空白。

**Comment by progrape** [comment]
这是 demo 的 bug，谢谢反馈

**Comment by bosen365** [comment]
这个跑在容器里就不是空白了

**Comment by progrape** [comment]
@freelancer13 空白是简易路由抛了异常导致的，预览 demo 推荐使用构建工具中的流程，跑一个 server 来预览。

**Comment by freelancer13** [comment]
感谢 @progrape
