### ISSUE TITLE
刚才下载的最新版搜索框有问题

### ISSUE THREAD

**Issue by bosen365** [weui/weui#306]
搜索框显示太高了，整屏都是，但手机扫描的效果不是这样，是不是css被污染了
![image](https://cloud.githubusercontent.com/assets/6869773/14312485/1ac9f186-fc1f-11e5-89db-04fda99d91d3.png)

**Comment by bosen365** [comment]
有没有哪位帮忙看下，在手机端、谷歌浏览器   weixindebug都显示如截图

**Comment by progrape** [comment]
@bosen365 麻烦提供你的代码，方便我们帮你定位问题~

**Comment by bosen365** [comment]
`<script type="text/html" id="tpl_searchbar">
<div class="page">
    <div class="hd">
        <h1 class="page_title">searchBar</h1>
    </div>
    <div class="bd">
        
        <div class="weui_search_bar" id="search_bar">
            <form class="weui_search_outer">
                <div class="weui_search_inner">
                    <i class="weui_icon_search"></i>
                    <input type="search" class="weui_search_input" id="search_input" placeholder="搜索" required/>
                    <a href="javascript:" class="weui_icon_clear" id="search_clear"></a>
                </div>
                <label for="search_input" class="weui_search_text" id="search_text">
                    <i class="weui_icon_search"></i>
                    <span>搜索</span>
                </label>
            </form>
            <a href="javascript:" class="weui_search_cancel" id="search_cancel">取消</a>
        </div>
        <div class="weui_cells weui_cells_access search_show" id="search_show">
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>实时搜索文本</p>
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>实时搜索文本</p>
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>实时搜索文本</p>
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>实时搜索文本</p>
                </div>
            </div>
        </div>
    </div>
</div>
</script>`

然后css中关于搜索部分的样式为
`.weui_search_bar {
  position: relative;
  padding: 8px 10px;
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  box-sizing: border-box;
  background-color: #EFEFF4;
  z-index: 2;
}
.weui_search_bar:before {
  content: " ";
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 1px;
  border-top: 1px solid #C7C7C7;
  color: #C7C7C7;
  -webkit-transform-origin: 0 0;
          transform-origin: 0 0;
  -webkit-transform: scaleY(0.5);
          transform: scaleY(0.5);
}
.weui_search_bar:after {
  content: " ";
  position: absolute;
  left: 0;
  bottom: 0;
  width: 100%;
  height: 1px;
  border-bottom: 1px solid #C7C7C7;
  color: #C7C7C7;
  -webkit-transform-origin: 0 100%;
          transform-origin: 0 100%;
  -webkit-transform: scaleY(0.5);
          transform: scaleY(0.5);
}
.weui_search_bar.weui_search_focusing .weui_search_cancel {
  display: block;
}
.weui_search_bar.weui_search_focusing .weui_search_text {
  display: none;
}
.weui_search_outer {
  position: relative;
  -webkit-box-flex: 1;
  -webkit-flex: auto;
      -ms-flex: auto;
          flex: auto;
  background-color: #EFEFF4;
}
.weui_search_outer:after {
  content: '';
  position: absolute;
  left: 0;
  top: 0;
  width: 200%;
  height: 200%;
  -webkit-transform: scale(0.5);
          transform: scale(0.5);
  -webkit-transform-origin: 0 0;
          transform-origin: 0 0;
  border-radius: 10px;
  border: 1px solid #E6E6EA;
  box-sizing: border-box;
  background: #FFFFFF;
}
.weui_search_inner {
  position: relative;
  padding-left: 30px;
  padding-right: 30px;
  height: 100%;
  width: 100%;
  box-sizing: border-box;
  z-index: 1;
}
.weui_search_inner .weui_search_input {
  padding: 4px 0;
  width: 100%;
  height: 1.42857143em;
  border: 0;
  font-size: 14px;
  line-height: 1.42857143em;
  box-sizing: content-box;
  background: transparent;
}
.weui_search_inner .weui_search_input:focus {
  outline: none;
}
.weui_search_inner .weui_icon_search {
  position: absolute;
  left: 10px;
  top: -2px;
  line-height: 28px;
}
.weui_search_inner .weui_icon_clear {
  position: absolute;
  top: -2px;
  right: 0;
  padding: 0 10px;
  line-height: 28px;
}
.weui_search_text {
  position: absolute;
  top: 1px;
  right: 1px;
  bottom: 1px;
  left: 1px;
  z-index: 2;
  border-radius: 3px;
  text-align: center;
  color: #9B9B9B;
  background: #FFFFFF;
}
.weui_search_text span {
  display: inline-block;
  font-size: 14px;
  vertical-align: middle;
}
.weui_search_text .weui_icon_search {
  margin-right: 5px;
}
.weui_search_cancel {
  display: none;
  margin-left: 10px;
  line-height: 28px;
  color: #09BB07;
}
.weui_search_input:not(:valid) ~ .weui_icon_clear {
  display: none;
}
input[type="search"]::-webkit-search-decoration,
input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-results-button,
input[type="search"]::-webkit-search-results-decoration {
  display: none;
}`

**Comment by bosen365** [comment]
dom结构是这样的
<script type="text/html" id="tpl_searchbar">
<div class="page">
    <div class="hd">
        <h1 class="page_title">searchBar</h1>
    </div>
    <div class="bd">
        
        <div class="weui_search_bar" id="search_bar">
            <form class="weui_search_outer">
                <div class="weui_search_inner">
                    <i class="weui_icon_search"></i>
                    <input type="search" class="weui_search_input" id="search_input" placeholder="搜索" required/>
                    <a href="javascript:" class="weui_icon_clear" id="search_clear"></a>
                </div>
                <label for="search_input" class="weui_search_text" id="search_text">
                    <i class="weui_icon_search"></i>
                    <span>搜索</span>
                </label>
            </form>
            <a href="javascript:" class="weui_search_cancel" id="search_cancel">取消</a>
        </div>
        <div class="weui_cells weui_cells_access search_show" id="search_show">
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>实时搜索文本</p>
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>实时搜索文本</p>
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>实时搜索文本</p>
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>实时搜索文本</p>
                </div>
            </div>
        </div>
    </div>
</div>
</script>

**Comment by bosen365** [comment]
`<script type="text/html" id="tpl_searchbar">
<div class="page">
    <div class="hd">
        <h1 class="page_title">searchBar</h1>
    </div>
    <div class="bd">
        
        <div class="weui_search_bar" id="search_bar">
            <form class="weui_search_outer">
                <div class="weui_search_inner">
                    <i class="weui_icon_search"></i>
                    <input type="search" class="weui_search_input" id="search_input" placeholder="搜索" required/>
                    <a href="javascript:" class="weui_icon_clear" id="search_clear"></a>
                </div>
                <label for="search_input" class="weui_search_text" id="search_text">
                    <i class="weui_icon_search"></i>
                    <span>搜索</span>
                </label>
            </form>
            <a href="javascript:" class="weui_search_cancel" id="search_cancel">取消</a>
        </div>
        <div class="weui_cells weui_cells_access search_show" id="search_show">
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>实时搜索文本</p>
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>实时搜索文本</p>
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>实时搜索文本</p>
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>实时搜索文本</p>
                </div>
            </div>
        </div>
    </div>
</div>
</script>`

**Comment by bosen365** [comment]
![image](https://cloud.githubusercontent.com/assets/6869773/14341494/c246157a-fcc4-11e5-9e54-26ec97573796.png)

**Comment by progrape** [comment]
@bosen365 推荐使用 http://codepen.io/ 提供代码给我们

**Comment by sklthegoodman** [comment]
请在codepen那里贴上所有相关的CSS代码吧，可能是某些CSS规则污染到了。

**Comment by bosen365** [comment]
应该是我本身项目代码css冲突了，导致weui被污染了。因为放在项目外构建预览是正常的，我再观察下
