### ISSUE TITLE
CSS class-name为什么使用下划线风格？

### ISSUE THREAD

**Issue by xixilive** [weui/weui#308]
1. 相信大多数前端工程师都习惯于连字符(dashes/hyphen)风格，为何贵产品选择下划线(underscore)风格？这违背了用户的长期习惯；

1. CSS官方命名规范也是dashes/hyphen风格；

1. 下划线输入要按住Shift键，不方便;

巴拉巴拉一大堆理由，诸如 BEM/NCSS 这些约定俗成的规范值得参考。

当然，这不是什么技术标准，也许你们有自己的理由.....

**Comment by progrape** [comment]
#10
