### ISSUE TITLE
路由首次进入只能push么？为啥router源码是压缩的呢？

### ISSUE THREAD

**Issue by i5ting** [weui/weui#310]
```
router.push(home)
```

**Comment by progrape** [comment]
@i5ting `router.min.js` 就是原来的 `pageManager` 单独拎出来的，源码在这里 https://github.com/progrape/router 

添加路由配置是通过 `push` 方法添加~

**Comment by i5ting** [comment]
@progrape 首次push动画，你们不觉得怪么？。。。。default的时候无动画就好了嘛，又不难

**Comment by i5ting** [comment]
@progrape O(∩_∩)O谢谢，看到源码了

**Comment by progrape** [comment]
这个建议好，可以改进一下~谢谢
