### ISSUE TITLE
键盘遮挡输入框

### ISSUE THREAD

**Issue by mixiu** [weui/weui#311]
用weui做过几个项目，根据反馈有部分机型（小米，三星S4等）在输入的时候弹出的键盘不会让页面自动上移(用微信打开的情况，浏览器打开就又正常)，在ios系统上的微信和浏览器测试暂无问题。不知道能否有什么解决方法，目前测试官方的demo也是如此。

**Comment by progrape** [comment]
@mixiu 这个是呈现 demo 的 bug，昨天发布的 v0.4.1 版本已经修正了 demo 的这个问题，参考 https://github.com/weui/weui/blob/master/src/example/example.js#L259

相关 issue：#284
