### ISSUE TITLE
navbar & tabbar fixed的问题

### ISSUE THREAD

**Issue by chendlcom** [weui/weui#312]
1、navbar 顶部的weui_navbar 由原来的fixed变成了absolute
2、navbar 顶部的weui_navbar即使自己设值了position: fixed; 在pc调试没问题，但到手机上（ios9.3.1)就不行了（weui_navbar不能一直固定在顶部，而是滑动的时候会在屏幕中间停留，当滑动停止1s左右才会回到它本该在的位置）

3、tabbar同上

**Comment by Jayin** [comment]
2. position:fixed 慎(不)用，换用position:absolute实现
