### ISSUE TITLE
开发的git 指令在哪里输入

### ISSUE THREAD

**Issue by allen317** [weui/weui#313]
我下载了npm 里面有一个是npm cmd的还有一个只有npm, 在第一个输入开发的git clone https://github.com/weui/weui.git 他说没这个指令，求解~thx

**Comment by progrape** [comment]
@allen317 上手使用 WeUI，请参考 https://github.com/weui/weui/wiki/getting-started ，不需要 git。

如果需要 clone WeUI 的代码下来修改，请先安装  git ，https://git-scm.com

**Comment by allen317** [comment]
谢谢你，我今年有一门open source的课程作业要求我们在开源社区为一个project写一些东西并且和大家互动，我有这个基础应该是可以修改些东西，真的很感谢你的回复！
