### ISSUE TITLE
为什么使用weui.css框架在有的手机上看页面是乱的在有的手机上看是正常的

### ISSUE THREAD

**Issue by Lectersjdhakashkhaskd** [weui/weui#315]
在安卓机和ios上都有这种情况，苹果9.0以下的系统都是这样9.0以上的就正常了。在网上查了一下好像是因为select标签的问题但是有些标签用的不是select也是这种情况

**Comment by progrape** [comment]
@Lectersjdhakashkhaskd 可否提供多点信息？什么情况下是乱的？乱成什么样？

**Comment by Lectersjdhakashkhaskd** [comment]
您好请您用微信关注一下租分期Zufenqi在支付房租(住宅商铺写字楼)页面http://www.zufenqi.net/wx/orders/toOrdersAdd.shtml页面，详细的我已经发到您gmail邮箱里了，请您帮忙看一下。

**Comment by progrape** [comment]
这个页面我用手机打开预览，没发现样式错乱的问题。另外，这个页面的 WeUI 用法存在很多问题，使用不当。
