### ISSUE TITLE
能否支持微信的滑动删除按钮

### ISSUE THREAD

**Issue by xiguichen** [weui/weui#318]
weui是否可以考虑添加微信中的滑动删除的功能？

**Comment by logoove** [comment]
安卓中效果不好  其实用zepto写就可以了 更偏向于操作表

**Comment by xiguichen** [comment]
还能说得更具体些？谢谢

**Comment by whlong789** [comment]
可以，我的已经用上了，过些天上线后给传上来

**Comment by whlong789** [comment]
zepto.touchWipe.js不谢

**Comment by whlong789** [comment]
/**
  * zepto插件：向左滑动删除动效
  * 使用方法：$('.itemWipe').touchWipe({itemDelete: '.item-delete'});
  * 参数：itemDelete  删除按钮的样式名
  */
 ;
 (function($) {
   $.fn.touchWipe = function(option) {
     var defaults = {
      itemDelete: '.item-delete', //删除元素
    };
    var opts = $.extend({}, defaults, option); //配置选项
    var delWidth = $(opts.itemDelete).width();

    var initX; //触摸位置X
    var initY; //触摸位置Y
    var moveX; //滑动时的位置X
    var moveY; //滑动时的位置Y
    var X = 0; //移动距离X
    var Y = 0; //移动距离Y
    var flagX = 0; //是否是左右滑动 0为初始，1为左右，2为上下，在move中设置，在end中归零
    var objX = 0; //目标对象位置

    $(this).on('touchstart', function(event) {
      console.log('start..');
      var obj = this;
      initX = event.targetTouches[0].pageX;
      initY = event.targetTouches[0].pageY;
      console.log(initX + ':' + initY);
      objX = (obj.style.WebkitTransform.replace(/translateX\(/g, "").replace(/px\)/g, "")) * 1;
      console.log (objX);
      if (objX == 0) {
        $(this).on('touchmove', function(event) {

          // 判断滑动方向，X轴阻止默认事件，Y轴跳出使用浏览器默认
          if (flagX == 0) {
            setScrollX(event);
            return;
          } else if (flagX == 1) {
            event.preventDefault();
          } else {
            return;
          }

          var obj = this;
          moveX = event.targetTouches[0].pageX;
          X = moveX - initX;  
          if (X >= 0) {
            obj.style.WebkitTransform = "translateX(" +0+ "px)";
          } else if (X < 0) {
            var l = Math.abs(X);
            obj.style.WebkitTransform = "translateX(" + -l + "px)";
            if (l > delWidth) {
              l = delWidth;
              obj.style.WebkitTransform = "translateX(" + -l + "px)";
            }
          }
        });
      } else if (objX < 0) {
        $(this).on('touchmove', function(event) {

          // 判断滑动方向，X轴阻止默认事件，Y轴跳出使用浏览器默认
          if (flagX == 0) {
            setScrollX(event);
            return;
          } else if (flagX == 1) {
            event.preventDefault();
          } else {
            return;
          }

          var obj = this;
          moveX = event.targetTouches[0].pageX;
          X = moveX - initX;
          if (X >= 0) {
            var r = -delWidth + Math.abs(X);
            obj.style.WebkitTransform = "translateX(" + r + "px)";
            if (r > 0) {
              r = 0;
              obj.style.WebkitTransform = "translateX(" + r + "px)";
            }
          } else { //向左滑动
            obj.style.WebkitTransform = "translateX(" + -delWidth + "px)";
          }
        });
      }
    })

    //结束时判断，并自动滑动到底或返回
    $(this).on('touchend', function(event) {  
      var obj = this;
      objX = (obj.style.WebkitTransform.replace(/translateX\(/g, "").replace(/px\)/g, "")) * 1;
      if (objX > -delWidth / 2) {
        obj.style.transition = "all 0.2s";
        obj.style.WebkitTransform = "translateX(" +0+ "px)";
        obj.style.transition = "all 0";
        objX = 0;
      } else {
        obj.style.transition = "all 0.2s";
         obj.style.WebkitTransform = "translateX(" + -delWidth + "px)";
         obj.style.transition = "all 0";
         objX = -delWidth;
       }
       flagX = 0;
     })
 
     //设置滑动方向
     function setScrollX(event) {   
       moveX = event.targetTouches[0].pageX;
       moveY = event.targetTouches[0].pageY;
       X = moveX - initX;
       Y = moveY - initY;
 
       if (Math.abs(X) > Math.abs(Y)) {
         flagX = 1;
       } else {
         flagX = 2;
       }
       return flagX;
     }
 
     //链式返回
     return this;
   };
 
 })(Zepto);

**Comment by whlong789** [comment]
$('.weui_cell').touchWipe({ itemDelete: '.weui_cell_delete' });

<div class="weui_cells">
    <div class="weui_cell">
        <a href="javascript:;">
            <div class="weui_cell_hd"><img src="http://shp.qpic.cn/weixinsrc_pic/pScBR7sbqjOBJomcuvVJ6iacVrbMJaoJZkFUIq4nzQZUIqzTKziam7ibg/" /></div>
            <div class="weui_cell_bd">
                <h4 class="ellipsis">一木建筑装饰设计（台州）有限公司一木建筑装饰设计（台州）有限公司</h4>
                <p><span class="ellipsis">私营企业<i>|</i>少于50人<i>|</i>2011年</span><span>22分钟前</span></p>
            </div>
        </a>
        <div class="weui_cell_delete">
            <button>删除</button>
        </div>
    </div>
</div>

**Comment by whlong789** [comment]
<div class="weui_cells"><div class="weui_cell"><a href="javascript:;">呃呃呃 </a><div class="weui_cell_delete"><button>删除</button></div></div></div>

**Comment by logoove** [comment]
2017-4-21新增左滑动删除 http://weixin.yoby123.cn/weui/c/cell11.html

**Comment by isabellaling** [comment]
@whlong789 
报错了，Invalid regular expression: /translateX(/: Unterminated group

**Comment by isabellaling** [comment]
@whlong789 
好了，正则表达式匹配括号要加个\
objX = (obj.style.WebkitTransform.replace(/translateX\(/g, "").replace(/px\)/g, "")) * 1;
