### ISSUE TITLE
Android上输入框被键盘挡住问题

### ISSUE THREAD

**Issue by LWFeng** [weui/weui#319]
已经使用example.js中那段代码，但是似乎无效果，部分安卓机有效，在小米note和红米系列、索尼上不会自动弹上。
![image](https://cloud.githubusercontent.com/assets/12045687/14449045/900681b8-00a1-11e6-9178-38ded5084ce8.png)
小米note被遮挡的效果。
![image](https://cloud.githubusercontent.com/assets/12045687/14449053/a9bc11f4-00a1-11e6-9388-ca477da3a6f9.png)
对比IPhone6s Plus的效果。

**Comment by mlyknown** [comment]
这个坑不好填呀。。

**Comment by progrape** [comment]
遮挡是共性问题，与 weui 无关

**Comment by LWFeng** [comment]
求解有没有好办法，试了几种办法都没有效果

**Comment by fay04** [comment]
你们有啥好的解决办法了吗

**Comment by LWFeng** [comment]
@fay04 在focus的时候滚动相应的高度。
```
$('#search-input').bind('focus',function(e){
     var $this = $(this);
     e.preventDefault()
     setTimeout(function(){
           $(window).scrollTop($this.offset().top);
     }, 0);
 });
```

**Comment by fay04** [comment]
@LWFeng 这个只能处理有滚动条的界面，对于没滚动条的界面或者是input位于最底部的界面不起作用
