### ISSUE TITLE
编码规范问题

### ISSUE THREAD

**Issue by long0375** [weui/weui#320]
您好：请问在使用微信UI的时候，我这里存在一个疑惑，需要你们帮助，谢谢。

请问官方当中是否有提供一套微信的前端界面UI编码规范，比如项目文件命名、样式、脚本等等方面的规范文档。

如果有，请给出一个微信UI界面文档地址，感谢。

**Comment by yhhwpp** [comment]
看完他们的源码就清楚了

**Comment by BearJ** [comment]
@long0375 说明请看：https://github.com/weui/weui/blob/master/CONTRIBUTING.md

**Comment by long0375** [comment]
@BearJ 非常感谢。
