### ISSUE TITLE
微信和苹果有什么关系？

### ISSUE THREAD

**Issue by qiaoyan** [weui/weui#321]
github上有比这个更丑的ui吗？与qq账户互通的“技术”才是其他开发者所需要的。

**Comment by progrape** [comment]
怎么个互通法？另外，标题和内容有啥关系？

**Comment by qiaoyan** [comment]
这个ui看起来想ios原生。开始阶段微信可以用qq账户登录，并获取朋友关系。

**Comment by progrape** [comment]
so？你想表达什么思想感情？

**Comment by yhhwpp** [comment]
ios原生 跟微信色UI还是有差距的吧

**Comment by airyland** [comment]
这种缺乏常识，不知所吾的issue直接lock掉好了。。
