### ISSUE TITLE
select控件的样式跟其他input样式没有对齐

### ISSUE THREAD

**Issue by ctfzh** [weui/weui#326]
在使用weui.css做表单的时候，发现select 控件的样式跟其他input控件的样式没有对齐，比如：
1. select控件使用weui_cell_select类时，weui_label类要增加padding-left: 15px;才能跟其他控件左边对齐；
2. select控件使用weui_cell_select类时，weui_select类要增加padding-left: 0; 

建议把相关建议整理到weui.css里。
谢谢

**Comment by uxsi** [comment]
@ctfzh weui label对齐了视觉，第2点已修复；第1点是否是因为缺失`weui_select_after`这个扩展类？
