### ISSUE TITLE
怎样设置title

### ISSUE THREAD

**Issue by mlyknown** [weui/weui#327]
https://www.zhihu.com/question/26228251
ios里面不能设置title了,这里面提到的解决方案已经失效 0.0

**Comment by airyland** [comment]
这跟weui无关吧。

**Comment by mlyknown** [comment]
微信的问题嘛。。毕竟维护weui的是官方的人嘛。。。微信好多坑啊。 0.0

**Comment by airyland** [comment]
@mlyknown 目测是iOS webview的问题。

**Comment by progrape** [comment]
测试发现可以设置一次，第二次设置就不生效

**Comment by xuanfeng** [comment]
微信SPA单页面应用更换title: http://www.xuanfengge.com/wx-spa-change-title.html

**Comment by logoove** [comment]
看看我的效果<http://weixin.yoby123.cn/weui/>  公众号![关注我](http://weixin.yoby123.cn/attachment/qrcode_1.jpg?time=1463394124)  代码下载<https://github.com/logoove/weui2>

**Comment by progrape** [comment]
设置标题和你这个有什么关系！
