### ISSUE TITLE
select 的选项列表样式和文档里面的不一样

### ISSUE THREAD

**Issue by pangz1** [weui/weui#335]
为什么我的select 出来的样式是这样的，是我没用对吗
![image](https://cloud.githubusercontent.com/assets/16848594/14759511/f3044100-0958-11e6-9cf8-35033bcac6aa.png)

我期望是这样的
![image](https://cloud.githubusercontent.com/assets/16848594/14759513/1377675a-0959-11e6-8cbb-a6fddb8456af.png)

**Comment by progrape** [comment]
@pangz1 select 控件和平台有关，你截图的是 Android 平台下的表现，也是 Android 用户的习惯。下面你期望的是 iOS 的表现。

**Comment by logoove** [comment]
安卓表现不一样  希望用picker来代替select 这样能达到 双平台一样效果

**Comment by logoove** [comment]
看看我的效果<http://weixin.yoby123.cn/weui/>  公众号![关注我](http://weixin.yoby123.cn/attachment/qrcode_1.jpg?time=1463394124)  代码下载<https://github.com/logoove/weui2>

**Comment by whlong789** [comment]
选择的时候，内容区被遮挡，并没有像ios那样向上滚

**Comment by whlong789** [comment]
@logoove 选择的时候，内容区被遮挡，并没有像ios那样向上滚
