### ISSUE TITLE
在iphone4下，0.4.1版本 出现weui_lable和weui_input重叠到一起的情况

### ISSUE THREAD

**Issue by mablevi** [weui/weui#336]
原因是weui_lable设置了105px的宽度，可以用媒体查询处理。 使用了css文件，less的没看。

**Comment by progrape** [comment]
@mablevi `weui_label` 默认是 `3em` 的宽度，应该没有 `105px` 那么宽，这个 105 是你自己设置的？

**Comment by mablevi** [comment]
不是，是在master下载的dist的example里。 官网的demo是3em。
引用样式位置在weui_form_common.less里
.weui_label{
  display:block;
  width:@weuiCellLabelWidth;//这里显示105px
}

**Comment by uxsi** [comment]
@mablevi 会加上断行

另外问一下是因为设置了105px，导致重叠？可以发下重叠相关的截图不？

**Comment by mablevi** [comment]
公司渣网络 传不上去
![Uploading 111.png…]()
