### ISSUE TITLE
0.4.1版本在cdnjs和bootcdn上都没有，没有提交？

### ISSUE THREAD

**Issue by firesh** [weui/weui#337]

**Comment by progrape** [comment]
@firesh cdnjs 那边在发布后一两天内就自动同步到了，地址是 https://cdnjs.cloudflare.com/ajax/libs/weui/0.4.1/style/weui.css 。而 bootcdn 是从 cdnjs 那边同步的，不知为何 0.4.1 的版本没有同步到。

**Comment by progrape** [comment]
强烈推荐使用微信提供的 CDN 链接 https://res.wx.qq.com/open/libs/weui/0.4.1/weui.min.css
