### ISSUE TITLE
没有表格样式

### ISSUE THREAD

**Issue by liu120945561** [weui/weui#338]
没有表格样式，不得不用bootstrap，导致了两个css用在一起特别难看

**Comment by progrape** [comment]
@liu120945561 目前 WeUI 没有表格的样式，是因为 WeUI 定位是在移动端、微信内使用的，而手机屏幕比 PC 的屏幕小得多。手机上显示 3、4 列的表格就撑满了，而且表格内的文字如果比较多，就很容易发生折行、错位，所以我们在设计层面就不推荐使用表格来展示数据。

举一个例子，假设需要展示以下表格数据：

|厂家|类型|型号|数量|时间
|------|------|------|------|------|
|xx商家|xx类型|xx型号|100|2016-04-26 15:18:07
|xx商家|xx类型|xx型号|100|2016-04-26 15:18:07
|xx商家|xx类型|xx型号|100|2016-04-26 15:18:07
|xx商家|xx类型|xx型号|100|2016-04-26 15:18:07
|xx商家|xx类型|xx型号|100|2016-04-26 15:18:07

**Comment by cncolder** [comment]
每行放4个 `.weui_cell_bd.weui_cell_primary` 勉强能实现你要的效果, 每列等宽, 无法宽度自适应, 竖条分隔线就只能自己用CSS调整了.
