### ISSUE TITLE
微信可能内置 React.js 吗

### ISSUE THREAD

**Issue by Huxpro** [weui/weui#34]
目前听说是有 Zepto.js 的，
作为微信内生态的合作伙伴，想知道有没有内置 React.js 的计划～
毕竟你们也要推基于 React.js 的 React-weUI 嘛

**Comment by willerce** [comment]
小道消息是内置的了。

**Comment by kevyu** [comment]
什么意思？内置之后就不用从外部加载了？

**Comment by xcfed** [comment]
是由amui+react联想到的吗？
