### ISSUE TITLE
弹出框 布局问题

### ISSUE THREAD

**Issue by MinJieLiu** [weui/weui#343]
目前弹出框的布局是用
`transform: translate(-50%,-50%);`
来进行居中布局的。
目前此方案有个缺陷，如我想用弹出框 transform 动画，会出现出现位置不正确的问题

**Comment by uxsi** [comment]
@MinJieLiu 动画效果是怎么样的呢？

**Comment by MinJieLiu** [comment]
@uxsi 弹出框的 zoomIn动画和zommOut动画 出现位置和消失位置会在屏幕右下角 就是禁用掉弹出框`transform: translate(-50%,-50%);` 的位置
