### ISSUE TITLE
ActionSheet遮挡问题

### ISSUE THREAD

**Issue by kejuwang** [weui/weui#344]
我的界面是基于TabBar的，所以每个子界面底部都会有一个条。这时如果我需要在某一个界面弹出ActionSheet的话，应该出现的效果是ActionSheet从底部弹出，挡住TabBar。
我在使用Chrome进行本地调试，以及使用微信web开发者工具远程调试时都能达到刚才我说的效果。但是在微信（苹果，6.3.16，2016年4月20日发布）里打开时，ActionSheet却被TabBar遮挡了。难道用的不是一个内核码？疑似z-index失效了……求解

**Comment by progrape** [comment]
@kejuwang 这里有个例子，http://progrape.github.io/weui.js/ 。

![image](https://cloud.githubusercontent.com/assets/4652816/14973633/c6b706b6-111c-11e6-86b4-138b22939f14.png)

用了 Tabbar，也有 ActionSheet，我在 iOS 版微信打开没有出现你说的遮挡情况。用你的手机打开试试看？如果有问题的话，请点击这个页面右下角的“面板”，切到“系统”的tab，截图提供一下系统信息，谢谢~
