### ISSUE TITLE
建议添加 栅格系统、网格布局之类的。

### ISSUE THREAD

**Issue by qiujy** [weui/weui#347]
已使用 weui 做了一个公司微网站，效果还是挻不错了。下一步打算用它做个微商城，它的页面布局比较麻烦。希望官方增加这方面的 CSS 支持。

**Comment by progrape** [comment]
开发中，谢谢建议~

**Comment by logoove** [comment]
栅栏其实很好找  网上一大把 http://weixin.yoby123.cn/weui/  参考我的
