### ISSUE TITLE
希望能增加无icon的圆弧Toast，和通讯录列表

### ISSUE THREAD

**Issue by echobailin** [weui/weui#348]
希望能增加无icon的圆弧Toast，和通讯录列表

**Comment by progrape** [comment]
无 icon 的圆弧 toast 是指？

**Comment by airyland** [comment]
like this? 
![image](https://cloud.githubusercontent.com/assets/559179/15008539/874a8ac8-1213-11e6-842e-389e7a9fd775.png)

**Comment by echobailin** [comment]
对！现在正方形那个如果文字长点就很难看。。。

**Comment by logoove** [comment]
建议用alert代替 图片的效果在ios就很难看

**Comment by gaoqiang19514** [comment]
> like this?
> ![image](https://cloud.githubusercontent.com/assets/559179/15008539/874a8ac8-1213-11e6-842e-389e7a9fd775.png)

为什么死活就是不肯加这个呢？
