### ISSUE TITLE
样式可否改成使用rem？

### ISSUE THREAD

**Issue by acmeid** [weui/weui#350]
样式可否改成使用rem？

**Comment by uxsi** [comment]
@acmeid  weui暂时不支持rem。rem在实现等比放大时，可能会对页面可用性造成影响，使用场景有局限；另外，使用rem，必须入侵开发者的项目，设置根节点字号，weui作为基础库，不希望这样做。可在业务侧使用工具对单位做转换

**Comment by acmeid** [comment]
好的，谢谢！可否推荐个 单位转换工具，毕竟之前没有尝试过这种转换。

**Comment by progrape** [comment]
@acmeid px 转 rem 推荐使用这个工具，https://github.com/cuth/postcss-pxtorem。

在 weui 的`build:style` 这个构建任务中，有使用 postcss 的 autoprefixer 插件，把 postcss-pxtorem 加进去就可以转换了。

```javascript
.pipe(...)
.pipe(postcss([autoprefixer, pxtorem]))
.pipe(...)
```

- 转换时需要注意 1px 的问题，1px 转出来会有小数点，渲染时可能会有缺陷，可以指定转换最小值；
- 如果有些地方不想转换，可以写成大写 `PX`，postcss-pxtorem 会忽略；
- 具体可以参考 postcss-pxtorem 的文档

**Comment by acmeid** [comment]
非常感谢！

**Comment by zhump** [comment]
@progrape  如何将less 源码 里的px 替换成rem
