### ISSUE TITLE
不知道是否有提示失败的Toast

### ISSUE THREAD

**Issue by ljnchn** [weui/weui#351]
我在Demo中看到Toast只有一个对号的图标加文字的样式，并没有代表失败的叉叉图标。试了换成Demo里其它的icon，效果并不好看。不知道是否有这种提示操作失败的Toast。

**Comment by progrape** [comment]
@ljnchn 按照设计师的设计理念，WeUI 不推荐开发者使用 toast 来呈现失败情况，toast 只是短暂的停留。失败的情况下，应该明确告诉用户失败的原因，推荐使用 alert 弹框来告知用户~

**Comment by ljnchn** [comment]
@progrape 哦哦，原来是这样，谢谢回复。

**Comment by logoove** [comment]
我的有哦 http://weixin.yoby123.cn/weui/ 可以参考
