### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasChildNodes' of null

### ISSUE THREAD

**Issue by 18259064372** [weui/weui#352]
我把dist中的文件拷贝到项目中，在自己的页面中引入dist中的样式和js文件，提示Uncaught TypeError: Cannot read property 'hasChildNodes' of null这个错误。。。之前的不会，加了router.min.js后就会这样，是不能直接用了吗

**Comment by progrape** [comment]
@18259064372 这是我们呈现 demo 的缺陷，会修正过来的。另外，这里的 router.min.js 是我们呈现 demo 时写的简易路由，不推荐用在生产环境，生产环境推荐你使用成熟的路由 https://github.com/sorrycc/awesome-javascript#routing

**Comment by newjie** [comment]
菜鸟求教：请问这个“路由”是干什么用的？是不是用来控制页面跳转、返回等功能的？Demo里面打开新页面时从右向左滑动的功能是不是也是router.min.js中实现的？

**Comment by progrape** [comment]
@newjie 是这个作用
