### ISSUE TITLE
weui_tab内容的切换

### ISSUE THREAD

**Issue by sxychmj** [weui/weui#358]
使用weui_tab样式,weui_navbar中的导航切换时,如何动态更换weui_tab_bd weui_tab_bd2 weui_tab_bd3呢,就像bootstrap中的那样,人家就直接写在里面.改weui_tab_bd后面的数字就可以了.这个如何做.
<div class="weui_tab">
    <div class="weui_navbar">

    </div>
    <div class="weui_tab_bd">

    </div>
</div>

**Comment by logoove** [comment]
笨,看我的 http://weixin.yoby123.cn/weui/

**Comment by logoove** [comment]
看看我的效果<http://weixin.yoby123.cn/weui/>  公众号![关注我](http://weixin.yoby123.cn/attachment/qrcode_1.jpg?time=1463394124)  代码下载<https://github.com/logoove/weui2>
