### ISSUE TITLE
searchBar focus的时候输入框被撑开了

### ISSUE THREAD

**Issue by youngBrain1893** [weui/weui#359]
searchBar focus的时候输入框被撑开了，由于没有安装上weiner调试，猜测是<a >取消</a> 宽度放不下 "取消" 二字，我自己的修改内容如下

    .weui_search_focusing .weui_search_outer { margin-right: 40px; }
    .weui_search_cancel { position: absolute; right: 10px; }

**Comment by youngBrain1893** [comment]
测试手机: 小米 4
微信版本号: 6.3.16 
![错误展示详情](https://cloud.githubusercontent.com/assets/16771528/15278706/cd6f786c-1b4e-11e6-80e0-b99bbd273d9a.png)

**Comment by logoove** [comment]
看看我的效果<http://weixin.yoby123.cn/weui/>  公众号![关注我](http://weixin.yoby123.cn/attachment/qrcode_1.jpg?time=1463394124)  代码下载<https://github.com/logoove/weui2>

**Comment by sklthegoodman** [comment]
这个问题已经定位，新的PR已经解决这个问题。用iphone6，小米3，oppo R7测试通过：
#365 

你提供的解决方案能解决取消按钮为两个汉字时的问题，而这里要求应该是自适应的。
