### ISSUE TITLE
非常酷的搜集weui效果集合和具体使用weui应用演示

### ISSUE THREAD

**Issue by logoove** [weui/weui#363]
http://weixin.yoby123.cn/weui/
喜欢的可以看看 是基于weui写的,来自非常多的开源组件集合,比如vux,jquery-weui,以及其他,效果超级多

**Comment by airyland** [comment]
话说swiper里面的图片地址直接复制我demo里的图片地址不大好啊

**Comment by logoove** [comment]
@airyland 可以到 https://github.com/logoove/weui2下载源码  具体应用案例关注公众号![公众号](http://weixin.yoby123.cn/attachment/qrcode_1.jpg?time=1463394124)

**Comment by airyland** [comment]
大哥，我是说你直接复制我vux demo里图片的cdn地址不大好。这么刷issue狂推也不是很好。

**Comment by logoove** [comment]
@airyland 好的 我换到oss去
