### ISSUE TITLE
IOS 下使用 hash 实现的 webapp，需要刷新一下才能够 config 成功

### ISSUE THREAD

**Issue by Hanruis** [weui/weui#367]
抱歉，在这里提问关于 weixin  jssdk 的问题。因为发了邮件给 jssdk 的邮箱反馈，但一直没有收到回复，所才来这问提问。

具体是这样的。

背景假设：
- 假设webapp 所在域名是 www.mywebapp.com
- 因为微信支付目录需要设置到具体的二级或者三级目录，于是需要设置为 www.mywebapp.com/#pay/

具体操作：
- 当去到  www.mywebapp.com/#pay/ 用户准备支付的时候，如果 IOS 下，不刷新页面，则提示 当前地址未注册；
- 刷新页面，再 config 一次，才能够正常调用支付功能；

ps：这个过程中 config 使用的 url 为：encodeURIComponent(location.href)  
pps: 不使用 encodeURIComponent(location.href.split("#")[0]) 的原因是，微信支付的目录需要设置到二三级。如果去掉了 hash 部分的话，会导致实际上 config 的Url是  www.mywebapp.com， 而后台配置的支付目录是 www.mywebapp.com/#pay/  ，然后报错，提示 当前地址未注册

在网上搜索了许多的资料，相关的内容很少，几乎没有提到过这个问题。
也查了文档，没有相关的介绍说明。

请问这种情况，是哪里使用不对出了问题么。有什么方法可以处理么？

**Comment by ITJaye** [comment]
该目录必须是发起支付的页面的精确目录，子目录下无法正常调用支付。
【发起支付】也就是说那个页面需要支付，就去【支付授权目录】设置该目录，另外，ios下你把www.mywebapp.com在【支付授权目录】设置就行。
