### ISSUE TITLE
怎么没有看到 input form 呢？

### ISSUE THREAD

**Issue by dotku** [weui/weui#370]
希望有一些提交表格之类的东西... 比如 textarea

**Comment by logoove** [comment]
你想说的是表单吧  weui提供有 全部都有啦

**Comment by dotku** [comment]
嗯，提交一个 feature request :D

On Wed, May 18, 2016 at 3:17 PM, Yoby <notifications@github.com> wrote:

> 你想说的是表单吧 weui提供有 全部都有啦
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/weui/weui/issues/370#issuecomment-220174729>
>



-- 
Jay/Weijing Lin

**Comment by progrape** [comment]
常用的表单组件已经有了
