### ISSUE TITLE
为什么1px解决方案没有使用响应式判断dpr的办法呢

### ISSUE THREAD

**Issue by riskers** [weui/weui#377]
而是全部 scale 0.5 那么dpr=1 的设备怎么办

**Comment by BearJ** [comment]
你好，低dpr也是会按照1px来渲染的

**Comment by Troland** [comment]
可是如果dpr是3的设备呢？我测试了一下，变粗了0.5倍。。。。不理解为什么不进行媒体判断？

**Comment by BearJ** [comment]
@Troland 因为会增加比较多的代码，毕竟用到1px的地方还是蛮多的。而且dpr是3的设备在weui视觉看来符合的，所以就没有用到媒体查询。

**Comment by Troland** [comment]
@BearJ 谢谢，明白了。
