### ISSUE TITLE
为什么官方演示的Demo有左右滑动的动画效果，而我的却没有咧

### ISSUE THREAD

**Issue by aiyuchen** [weui/weui#378]
我和官方演示一样，用的是https://github.com/progrape/router.git  做路由的，为何官方点击页面切换的时候是有左右滑动的效果，而我没有呢？

**Comment by aiyuchen** [comment]
我用起来很卡顿。。。。。

**Comment by jasondu** [comment]
这个是自己写动画的，进来和出去这是帮你加了一个class而已，动画还是要自己定义的

**Comment by aiyuchen** [comment]
@jasondu 请问动画代码是哪段，我怎么没找到咧？

**Comment by jasondu** [comment]
你打开http://weui.github.io/weui/#/ 打开开发者工具看里面的example.css最后一部分就知道了

**Comment by aiyuchen** [comment]
谢谢

**Comment by jasondu** [comment]
麻烦close掉
