### ISSUE TITLE
为什么图标有时候能显示出来有时候不能显示

### ISSUE THREAD

**Issue by 401442771** [weui/weui#379]
就是Toast弹出后，只显示【已完成】，上面的勾勾不显示，有时又能显示。
icons中的各种图标也一样，时有时无，忘大神解答。

**Comment by logoove** [comment]
一般页面先引入css 后面使用都没问题  如果是在php这类编程语言中输出 基本上是没有的

**Comment by progrape** [comment]
与 PHP 无关。 @401442771 什么情况下出现显示不了 icon 的？机型，系统版本，浏览器（微信客户端）版本？

**Comment by Mengds** [comment]
我的也是这种问题。toast对勾显示不出来，复选框单选框，图标都显示不出来，iphone6s，最新版本微信

**Comment by Mengds** [comment]
@401442771 请问问题解决了吗？

**Comment by 401442771** [comment]
@Mengds   没有解决，不知道原因
