### ISSUE TITLE
[建议]示例中的example.js添加一个自动加载的方法

### ISSUE THREAD

**Issue by zdsiyan** [weui/weui#38]
$container.on('click', '.js_cell[data-id]', function () {
        var id = $(this).data('id');
        var $tpl = $($('#tpl_' + id).html()).addClass('slideIn').addClass(id);
        $container.append($tpl);
        stack.push($tpl);
        history.pushState({id: id}, '', '#' + id);

        //加载数据
        if(typeof eval('load_'+id) != 'undefined' && eval('load_'+id) instanceof Function) { 
            eval('load_'+id+'();');
        }
        $($tpl).on('webkitAnimationEnd', function (){
            $(this).removeClass('slideIn');
        }).on('animationend', function (){
            $(this).removeClass('slideIn');
        });
        // tooltips
        if (id == 'cell') {
            $('.js_tooltips').show();
            setTimeout(function (){
                $('.js_tooltips').hide();
            }, 3000);
        }
    });

添加的三行代码用于页面跳转前的加载数据

    //加载测试
    function load_test(){
        $('#toast').show();
        setTimeout(function () {
            $('#toast').hide();
        }, 800);
    }

**Comment by progrape** [comment]
可以优化，可否发一个PR？

**Comment by zdsiyan** [comment]
@progrape 额，PR是啥意思？

**Comment by progrape** [comment]
`pull request`

**Comment by zdsiyan** [comment]
明白了，回去搞，今天又做了一个加强版，可以把id传给子页面，用于加载数据

        if(typeof eval('load_'+id) != 'undefined' && eval('load_'+id) instanceof Function) {
            var index = $(this).data('index');
            if(index!= 'undefined'){
                eval('load_'+id+'("'+index+'");');
            }else{
                eval('load_'+id+'();');
            }
        }

**Comment by zdsiyan** [comment]
自动加载的示例 #43
