### ISSUE TITLE
怎么做多屏适配？

### ISSUE THREAD

**Issue by Amos-tanke** [weui/weui#380]
大神们，你们怎么做的多频适配，求方法？

**Comment by mlyknown** [comment]
https://github.com/amfe/lib-flexible  阿里的解决方案

**Comment by progrape** [comment]
@Amos-tanke 不同屏幕尺寸的适配，可以尝试 REM

**Comment by NicholasNC** [comment]
@mlyknown @progrape 使用阿里的解决方案，在处理富文本编辑器输出的内容时出现字体很小的情况，不知你们是怎样解决的？

使用阿里的适配方案，因为在2倍屏下，它将 viewport 的 scale 设成0.5，这样富文本出来的文章内容里面如果设置了字体大小，例如：10px、18px 的话，在 iOS 下字体就特别小。
