### ISSUE TITLE
请问在WEUI项目中所有页面都在首页中，如何分成多个页面，然后在通过路由跳转？

### ISSUE THREAD

**Issue by zhaoleo007** [weui/weui#382]
请问在WEUI项目中所有页面都在首页中，如何分成多个页面，然后在通过路由跳转，这个问题困惑了我两天了，希望知道的大神告诉我一声，十分感谢

**Comment by progrape** [comment]
写的时候分成多页面来写，构建工具合并到首页中，然后通过路由来展示不同的界面
