### ISSUE TITLE
关于群主把我从WEUI群踢出的问题

### ISSUE THREAD

**Issue by lihongxun945** [weui/weui#387]
我不是来吵架的，也不是想再次加群的（说实话我也不屑于加这个群），只是想就事论事说一下这个情况。

1. 我不认为群主有随便踢人的权利
2. 如果确实触犯群规，那么群主踢人前是不是应该先说明一下原因，明确一下规定？什么情况下是会被踢出群的难道就是看管理员心情？
3. 我只能猜测原因是因为我说了"官网“两个字，我已经补充说明了我说的是 XXX 的官网，那么难道这个世界上只有 `weui`的网站能叫官网，其他的都不能这么叫？
4. 又或者是因为我一直在讨论 `XXX` 的问题让群主不爽了？说好的一起打造 weui 生态环境？
5. 作为一个还算有名的开源项目，这么做是不是显得太小气？

以上 "XXX" 指的是一个开源项目，不说名字是为了避免打广告的嫌疑。

PS：以群主的作风是不是也想直接关掉这个 `issue` 然后把我拉黑？

**Comment by evolutionjay** [comment]
沙发坐看国内开源群各种撕逼。

**Comment by fadesky** [comment]
看看

**Comment by lihongxun945** [comment]
楼主的作风果然就是直接踢人，直接关issue，哈哈

**Comment by bigmeow** [comment]
领导出来说话了：风头不能就这么被抢了

**Comment by ColdXu** [comment]
坐等
