### ISSUE TITLE
图片上传组件无法选中图片

### ISSUE THREAD

**Issue by zjhui** [weui/weui#388]
安卓下图片上传组件BUG，无法选中图片。
![qq 20160613160046](https://cloud.githubusercontent.com/assets/1116346/16000689/5e17fffa-3180-11e6-92a9-27b20470f1a3.jpg)
     当选择1（图片）时，手机屏幕变成白色，无法选中图片。
![823833729354064362](https://cloud.githubusercontent.com/assets/1116346/16000731/98b74378-3180-11e6-8b05-6d50f673199b.jpg)
     但是当选择2（图库）时，一切正常。使用[weui.io](url)上的上传组件也出现同样的情况。手机为`荣耀6`，系统型号见下图：
![85127381064647280](https://cloud.githubusercontent.com/assets/1116346/16000763/e0c26cd8-3180-11e6-94fc-054202cfbf7f.jpg)
微信版本：`6.3.18`

**Comment by alongchengtian0** [comment]
这个应该是华为系统的问题

**Comment by progrape** [comment]
调起这个界面之后就是系统的问题了，web 层面无能为力

**Comment by zjhui** [comment]
@progrape 那为何我用这种
![1](https://cloud.githubusercontent.com/assets/1116346/16001897/531b8af2-3187-11e6-8bf3-03899207515e.jpg)
就没有任何问题？

**Comment by progrape** [comment]
weui 也是 `<input type="file" />` 标签，不过 demo 那里多了图片格式的限制，是不是你那张图片格式不在这些格式范围内？

![image](https://cloud.githubusercontent.com/assets/4652816/16002246/3c7b15cc-3189-11e6-8df1-da0dbdfda864.png)

**Comment by zjhui** [comment]
我把图片格式限制去掉之后，还是一样。整个手机屏幕背景变成白色，无法选中任何图片。
![image](https://cloud.githubusercontent.com/assets/1116346/16028244/03bac6ce-3210-11e6-9368-af8a8a98d314.png)

**Comment by progrape** [comment]
你试一下写一个最简单的页面，只放一个 `<input type="file" />` 进去，看看有没有问题？

**Comment by zjhui** [comment]
@progrape 
![22](https://cloud.githubusercontent.com/assets/1116346/16031430/a2b4d1e4-322d-11e6-8d8f-e8851c615ca1.jpg)
加了一个最简单的`<input type="file" />` 就没有问题。我刚刚测试了一下，将
`.weui_uploader_input {  z-index: 1; }` 改为 `.weui_uploader_input {  z-index: 0; }`就没问题。
![image](https://cloud.githubusercontent.com/assets/1116346/16031450/da713dd4-322d-11e6-8361-1766698cc80f.png)

**Comment by progrape** [comment]
好的，这里需要确认一下改成 `z-index: 0` 看会不会引发别的 bug，如果不会，就改成 `z-index: 0` 兼容一下这种情况

**Comment by BearJ** [comment]
@zjhui 这里如果不加z-index:1的话，按钮里的" + "挡住了隐藏的input，会导致按钮有时点了没反应。所以这里先保留。或者你直接在你那边的项目修改这个z-index。谢谢。

**Comment by zjhui** [comment]
这个问题你们那边有华为手机吗？能不能复现修复一下？还有这里的`按钮里的" + "挡住了隐藏的input，会导致按钮有时点了没反应`这个问题会在哪些手机上出现？

**Comment by BearJ** [comment]
@zjhui 最近发现是input的accept导致的问题，改成 accept="image/*" 就可修复你上述的问题。

**Comment by zjhui** [comment]
非常感谢！
