### ISSUE TITLE
Edge浏览器中switch开关样式不正确

### ISSUE THREAD

**Issue by yikuo123** [weui/weui#389]
![wp_ss_20160613_0001](https://cloud.githubusercontent.com/assets/13978174/16033110/cd806c6c-323c-11e6-8f18-17824ed8b25a.png)

**Comment by progrape** [comment]
图片上传失败？

**Comment by yikuo123** [comment]
@progrape 已经重新长传图片了

**Comment by BearJ** [comment]
@yikuo123 这里因为edge对-webkit-appearance的支持不好导致这个情况，若要兼容需要改动html。这在下个大版本才能实现。如果您要兼容，目前建议您可以用一个hidden的input和 label 配合来模拟实现。

**Comment by stylejinmu** [comment]
![close](https://cloud.githubusercontent.com/assets/9429058/16106018/14247bc2-33c3-11e6-8b1a-3a7a52ca3e35.jpg)
![open](https://cloud.githubusercontent.com/assets/9429058/16106019/142577e8-33c3-11e6-9552-4db51a70b420.jpg)
在自家app里switch开关样式异常，见图。
红米1s
android版本： 4.2.2HM2014011
MIUI版本： MIUI-JHFCNBE8.0
app内核信息：Mozilla/5.0(Linux; U;Android 4.2.2;zh-cn;2014011 Build/HM2014011)AppleWebkit/534.30(KHTML,like Gecko) Version/4.0 Mobile Safari/534.30

华为 HuaweiH30-U10
android版本 4.2.2
系统版本号：Emotion系统 2.0
app内核信息： Mozilla/5.0(Linux;U; Android 4.2.2;zh-cn; H30-U10 Build/HuaweiH30-U10) AppleWebkit/534.30(KHTML,like Gecko) Version/4.0 Mobile Safari/534.30

**Comment by BearJ** [comment]
已fixed https://github.com/weui/weui/commit/515c7148728c19640594eedcf84737fb4f6187d7
