### ISSUE TITLE
Firefox下weui_switch有bug

### ISSUE THREAD

**Issue by dangjun625** [weui/weui#392]
<input class="" type="checkbox">

![firefox bug](https://cloud.githubusercontent.com/assets/4170198/16103489/b7e70c9c-33ab-11e6-81a8-10cd5683d20d.png)

**Comment by dangjun625** [comment]
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by logoove** [comment]
微信浏览器用的 本来就不兼容pc

**Comment by lichunqiang** [comment]
Firefox也有手机版的，也是不兼容的。

**Comment by BearJ** [comment]
@dangjun625 目前是用一个input来实现的，可能某些浏览器会有兼容问题，下个版本将重构switch
