### ISSUE TITLE
a按钮或链接weui_btn，点击后隐藏自己，再显示时无active状态

### ISSUE THREAD

**Issue by mengsian** [weui/weui#394]
`<p>&lt;!DOCTYPE html&gt;<br />
  &lt;html lang=&quot;en&quot;&gt;<br />
  &lt;head&gt;<br />
  &lt;meta charset=&quot;UTF-8&quot;&gt;<br />
  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1,user-scalable=0&quot;&gt;<br />
  &lt;title&gt;WeUI&lt;/title&gt;<br />
  &lt;!-- 引入 WeUI --&gt;<br />
  &lt;link rel=&quot;stylesheet&quot; href=&quot;weui/weui.min.css&quot;/&gt;<br />
  &lt;script src=&quot;http://libs.baidu.com/jquery/2.0.0/jquery.min.js&quot;&gt;&lt;/script&gt;<br />
  &lt;/head&gt;<br />
  &lt;body ontouchstart&gt;<br />
  &lt;br&gt;<br />
  &lt;a href=&quot;1.php&quot; class=&quot;weui_btn weui_btn_primary&quot;&gt;按钮一&lt;/a&gt;<br />
  &lt;br&gt;<br />
  &lt;a href=&quot;javascript:show();&quot; class=&quot;weui_btn weui_btn_primary&quot;&gt;按钮二&lt;/a&gt;<br />
  &lt;br&gt;<br />
  &lt;a href=&quot;javascript:;&quot; class=&quot;weui_btn weui_btn_primary&quot; id=&quot;qqq&quot;&gt;按钮三&lt;/a&gt;<br />
  &lt;!--<br />
  微信端访问：<br />
  按钮一：链接外部或锚点，正常<br />
  按钮二：运行函数，正常<br />
  按钮三：不正常，一直处于按下状态<br />
  所有的按钮或链接，点击以后的业务处理中，如果隐藏了自己或自己所在的区块，当再次显示按钮或区块时此按钮一直处于按下状态<br />
  如果延迟隐藏自己，例如 $(this).delay(300).hide(0);则正常<br />
  --&gt;<br />
  &lt;script&gt;<br />
  function show(){<br />
  $(&quot;#qqq&quot;).show();<br />
  }</p>
<p>$(function () {</p>
<p> $('#qqq').on('click', function () {<br />
  $(this).hide();<br />
  //$(this).delay(300).hide(0);<br />
  });<br />
  <br />
  });<br />
  &lt;/script&gt;<br />
  &lt;/body&gt;<br />
  &lt;/html&gt;</p>`

**Comment by BearJ** [comment]
@mengsian 标题说无active态，文中又说一直处于按下状态，所以你的问题应该是哪个？

**Comment by mengsian** [comment]
无active变化，一直处于按下状态，手机端
点击立刻隐藏自己的时候，来不及变化了，当显示自己的时候一直处于按下状态

**Comment by BearJ** [comment]
这个好像是被快速隐藏导致的，可以试试改变实现

**Comment by zhyzhy782** [comment]
Hello, 

I couldn't decide which  model of  phone to buy so I decided to ask you,  please take a look <http://another.latetripper.com/e7iv/788>

Good wishes, zhyzhy782
~SUBJECT=need your advice
Hello, 

I've found something interesting and  need your opinion about that  stuff, please take a look  <http://another.latetripper.com/e7iv/788>

Good wishes, zhyzhy782
