### ISSUE TITLE
关于页面跳转的问题：如何在各页面中通信？

### ISSUE THREAD

**Issue by newjie** [weui/weui#397]
我参照index.html自己做了一个表单页面，从公司各部门中选择人员并提交。在主页面上按下选择按钮后，跳转到部门列表页面，再按下某个部门后跳转到部门人员列表。以上UI都已实现，成员列表是复选。现在问题是除去当前页面的元素外，其他页面的元素实际上都是包含在`<script>`标签里面，无法用javascript方便地选取：

我在主页面上有一个容器#selected用来显示已经选定的人员，在成员列表页面用户选中某个成员时，本来应该用javascript选择该容器并加入已选择的人员，但是因为#selected此时实际上处于`<script>`标签中，所以无法选取了。请问这该如何解决呢？
我能想到的一个办法是在当前页面把已选中人员的信息放到全局变量中，等回到主页面时再从该全局变量中读取信息并显示在#selected中。但是如何判断用户已经回到主页面呢？我可以在分页面上做一个返回主页面的按钮，但是用户也可以按手机上的返回键返回啊。

**Comment by BearJ** [comment]
你好，可以设置全部变量。或使用其它路由库。
