### ISSUE TITLE
NavBar 与 SearchBar 之类的组件是否应该固定顶部？

### ISSUE THREAD

**Issue by MrChu** [weui/weui#398]
NavBar 与 SearchBar 之类的组件，当页面出现滚动时是否不应该跟随内容滚动而是在页面顶部固定？

**Comment by logoove** [comment]
肯定可以 我们实现了

**Comment by MrChu** [comment]
demo 中没看到效果啊

**Comment by logoove** [comment]
http://weixin.yoby123.cn/weui/  列表中 一直粘帖顶部

**Comment by MrChu** [comment]
@logoove  weui plus-_-

**Comment by 601774135** [comment]
为什么我使用了底部固定导航，他还是会跟着页面动，就不能一直固定在底部吗？

**Comment by BearJ** [comment]
你好，可以把内容放置在weui-tab__panel里。

**Comment by kanouken** [comment]
weui-tab__panel  也不可以哦
