### ISSUE TITLE
列表项标题文字和说明文字的字数过多时能否自动隐藏？

### ISSUE THREAD

**Issue by jiuqiang** [weui/weui#399]
列表项标题文字和说明文字的字数过多时能否自动匹配一下两者的宽度并自动隐藏文字？

**Comment by progrape** [comment]
@jiuqiang 你指的是 Panel 还是 Cell ？Panel 是可以自动隐藏的

![image](https://cloud.githubusercontent.com/assets/4652816/16475727/749814fa-3eb3-11e6-8f5a-46bf35ae96da.png)

**Comment by jiuqiang** [comment]
我指的是Cell，现在用Panel代替了

**Comment by uxsi** [comment]
@jiuqiang 公共库的组件越简单才越好用，如果需求量大得话后面我们会考虑加上哈
