### ISSUE TITLE
AngularJS 有计划支持吗

### ISSUE THREAD

**Issue by cloverstd** [weui/weui#4]

**Comment by qianduan** [comment]
暂时没有，等angularJS 2.0正式发布了再评估下，毕竟angular对浏览器支持不太好，比如IE和Firefox各个版本和android 4.4以下的内置浏览器。

**Comment by steambap** [comment]
火狐跑angular没有问题啊

**Comment by abellee** [comment]
有没考虑过直接内置到微信中😍

**Comment by progrape** [comment]
@abellee 敬请期待 :relaxed:

**Comment by qianduan** [comment]
@steambap 浏览器支持情况来源： https://saucelabs.com/u/angular2-ci angular 2.0貌似抛弃了一些浏览器～～

**Comment by dusdong** [comment]
angular2.0还比较遥远，angular 1.x 是当前主力并且会存在很长时间。可以考虑下推出 angular 1.x 版的吗？

**Comment by kevyu** [comment]
感觉angular没出来之前，市场会被react蚕食的差不多了。

**Comment by chenjianjx** [comment]
赶紧支持angular1吧，jquery什么的属于上一代js框架了。  angular2 的流行还很遥远。

**Comment by progrape** [comment]
有开发者封装有 angular 版本，可以参考选择

- https://github.com/x-cold/angular-weui
- https://github.com/limeng0403/Angularjs-weui
- https://github.com/threeq/angular-weui
