### ISSUE TITLE
【吐吐更健康】建议做Weui + Bootstrap

### ISSUE THREAD

**Issue by xcfed** [weui/weui#40]
建议做Weui + Bootstrap

**Comment by zdsiyan** [comment]
那跟直接用bootstrap有什么区别？

**Comment by progrape** [comment]
为什么需要做“WeUI + Bootstrap”呢？怎么个做法？

**Comment by xcfed** [comment]
WEUI的特点就是微信UI,而bootstrap最大的特点是框架和流行度，正好这好是可以合二为一的卖点，相信如果可以整合成功会比较好，有可能成为新的移动开发的一种解决方案。对那些想延续微信特色的团队会非常有用。当然，我说了这个是建议，是现在没有实现的，是向前看，是为了bootstrap移动端看起来更像微信而言的。

**Comment by xcfed** [comment]
想想当年bootstrap做出来的时候那么多人追，而现在移动的微信又这么火，那么以后呢！

**Comment by kevyu** [comment]
没太理解，weui和bootstrap不是对等的关系吗？虽然现在weui的控件还很少。

**Comment by xcfed** [comment]
不是对等的关系

**Comment by zdsiyan** [comment]
微信由于是手机访问，网络信号问题会比有线终端更严重，加上手机浏览器的性能低于pc，所以界面越简单越好，控件越少越好。否则很容易出现加载不全不能正常显示的问题，这是常态。
而bootstrap是为了兼容不同屏幕尺寸的布局方案，对PC,平板要优于手机平台。虽然bootstrap也支持手机布局，但真想用同一套ui来实现不同平台，必然会浪费大量的dom。如果页面很复杂的话，不如单独实现手机端放弃大部分控件会好些。
那么精简过的bootstrap跟weui就没什么区别了，为什么还要融合？
浏览器厂商这么闲不如把cocos2d内嵌了，让html开发可以拥有游戏般的体验。

**Comment by zhaisasi** [comment]
同意楼上

**Comment by xcfed** [comment]
未来带宽环境都会改变，未来的事也不是现在就能决定的。
Bitcoin刚出来的时候代码量才多少，而现在的代码量却是巨量级的。
为什么代码量会变得这么大？
因为，有需求！我们很难想到是，这个问题很难我们不去做，而更多的时候是我们需要他，我们必须去做。
只要未来有人需要那就会像需求方发展。控件少会变多、加载不全那就改善，浪费资源那就适度创新精简。想要webkit+coco2d未来一起，也不会妨碍weui+x+bootstrap未来不会更好。

**Comment by xcfed** [comment]
永远记住互联网没有权威，中国的互联网当然更没有。

**Comment by zdsiyan** [comment]
我不是微信的人，只是做微信端开发时偶然看到这个ui拿来用发现还挺方便，今天还顺手提交了一个PR，有兴趣可以看看

并没有阻止你表达立场，只是无法理解你的需求

**Comment by xcfed** [comment]
需求：人们为什么会用bootstrap？人们想要什么？那么移动端人们会不会也这样想？

**Comment by zdsiyan** [comment]
换个问题问可能更清晰些，什么场景下需要同时用到weui和bootstrap，只用其中一个是否可以？

**Comment by djyde** [comment]
bootstrap 和 weui 是两个不同的东西吧。。

**Comment by xcfed** [comment]
人们觉得weui不够，又想在移动端使用bootstrap的时候

**Comment by xcfed** [comment]
@djyde  是的，是两个东西，一个是UI，一个前端框架

**Comment by djyde** [comment]
不合理，不支持，也不可能

**Comment by zdsiyan** [comment]
"微信UI风格的bootstrap前端框架" 这个才是你要的东西，不过这东西和weui一点关系都没有，你可以找个前端帮你做一套"微信UI风格的bootstrap前端框架"

**Comment by xcfed** [comment]
我说的不仅仅是这些，不过你说的可以是当前的目标。

**Comment by xjiaoyang** [comment]
我也就在公众号和卡包用用，如果用到其他与WX没有半毛钱关系的项目上，那不是不伦不类了？我不知道作者发布这个项目的初衷有多广大，但是我觉得这个项目做微信相关的开发时最合适的。至于加bootstrap，那就更是没有任何理由了。

**Comment by djyde** [comment]
设计是一种语言和规范，weui 仅仅是一个对微信设计的前端技术实现。你完全可以用 bootstrap 实现一次（即使没有必要），叫做 weiui-bootstrap （就像 FlatUI）。

**Comment by xcfed** [comment]
我的想法是让其他人在需要的时候多一种选择

**Comment by xcfed** [comment]
大不了开始可以做成themes出来嘛，没必要一上来做framework。可能也不会来这么多质疑。我觉得这样说是一种妥协。设计，只是人们瞬间感觉的一种回应。有人喜欢，有人爱，有人讨厌，有人骂，但都不妨碍她本身是一种存在。

**Comment by xcfed** [comment]
我有一个外国朋友，他是那种代码控，声称我们在github在追的代码在整个github的不到5%（当然是去除Fork的垃圾复制库）。你不去了解的话，光听别人说是没有什么太大价值的。

**Comment by djyde** [comment]
我没有反对你自己去写一个 bootstrap theme for weui，仅仅是不支持微信 webview 自带 bootstrap 而已

**Comment by all-free-downloading** [comment]
weui 自带的那个bs太简单了 。 我主要看好 控件这块。

**Comment by abellee** [comment]
唉 这么多提需求的 不乏好的 但n多的人提的需求我觉得更像是想着这东西把本应自己做的都实现 拿来就能用 但weui到底是要干嘛？这都不用问吧？微信大了 微信开发这么普遍 但风格不一 要统一一下 我猜应该是这样吧

**Comment by all-free-downloading** [comment]
微信这个东西本身就每天再变， 无所谓什么统一不统一的。反正作为一个消费者用的爽就行了！什么设计风格什么的消费者才不管了。你weui+bootstrap让我用的爽我就支持你， 不是名门，支持你让你变成名门！得众人心者，得天下也！@xcfed 思路不错！但前路漫漫啊！支持你下！
