### ISSUE TITLE
demo页面 可以左右拖动~~

### ISSUE THREAD

**Issue by Lotuslwb** [weui/weui#400]
https://weui.io/#/   这个demo的首页

在PC chrome 和ip6s 上面都可以左右拖动，在body加上  width: 100%;   overflow: hidden; 就没事了；但是还是没找到哪里overflow了~~麻烦看看

**Comment by progrape** [comment]
好的，我查看一下~

**Comment by uxsi** [comment]
@Lotuslwb 我们在chrome和6sp上复现不了哦，你的chrome是什么版本？
