### ISSUE TITLE
无法显示微信ui效果

### ISSUE THREAD

**Issue by winbada** [weui/weui#408]
本地苹果电脑能显示ui效果，但是打包到服务器，就需要我的电脑上打开一次网页后，公众号才能显示ui效果。如果是需要微信软件上打开要传入appid的url，就不可以显示。在我自己的公众号中菜单点击后，无法显示微信的ui效果，这到底是什么回事呢？我的公众平台微信号是znjjsk,菜单中 ［产品介绍］－申请体验是有效果，［关于我们］－我的帐号，就不能现实效果

**Comment by progrape** [comment]
![image](https://cloud.githubusercontent.com/assets/4652816/16517949/cf03ab02-3fb2-11e6-83ab-d43b8db0feb7.png)

你服务端程序挂了

**Comment by winbada** [comment]
麻烦你再看多一遍，那天我已经把这个问题给改了

**Comment by progrape** [comment]
![image](https://cloud.githubusercontent.com/assets/4652816/16539662/adfe095a-407c-11e6-8e10-eb59c3570536.png)

![image](https://cloud.githubusercontent.com/assets/4652816/16539663/c3462590-407c-11e6-8585-89423ba46236.png)

css 路径错了，修正一下吧，还有就是引入一个就够了，不用两个

**Comment by winbada** [comment]
我去掉min.css，也没有显示出样式来？和之前是一样的

**Comment by progrape** [comment]
路径错了，用 CDN 吧。https://res.wx.qq.com/open/libs/weui/0.4.2/weui.css

**Comment by winbada** [comment]
解决了！！！！原来是这个问题，电脑上可以显示，就到了服务器就出现问题了！非常感谢，请受我一拜
