### ISSUE TITLE
search 提示文本垂直居中

### ISSUE THREAD

**Issue by transtone** [weui/weui#410]
https://github.com/airyland/vux/issues/314

**Comment by progrape** [comment]
@sklthegoodman

**Comment by sklthegoodman** [comment]
![image](https://cloud.githubusercontent.com/assets/4933537/16553385/f9868670-41fa-11e6-9d4f-88828d795ed4.png)

这里按照你的方法做默认文本反而更过于偏上。 @transtone

**Comment by zhyzhy782** [comment]
Hi! 

I found some cool  stuff that I couldn't pass, take a look  at  that  <http://surprise.ncbagpiper.com/e7hug/062>

Typos courtesy of my iPhone, zhyzhy782
