### ISSUE TITLE
求 https://weui.io/example 的源码

### ISSUE THREAD

**Issue by wzlee** [weui/weui#412]
感觉做的很酷，想学习一下规范，能开源出来就开源吧，或者能否私发给我：214508914@qq.com，感激不尽。

**Comment by airyland** [comment]
源码本就有src/example
https://github.com/weui/weui/wiki/Develop

**Comment by progrape** [comment]
@airyland 不一样的， https://weui.io 对应的是本仓库的 example，https://weui.io/example 是另外写的，我整理一下可以发出来

**Comment by airyland** [comment]
@progrape 明白了 😅

**Comment by wzlee** [comment]
Good job！

**Comment by progrape** [comment]
@wzlee  这里 https://github.com/progrape/weui-example ，学习规范谈不上，仅供参考

**Comment by wzlee** [comment]
收到，谢谢
