### ISSUE TITLE
问个问题, 关于transform: scale(0.5);

### ISSUE THREAD

**Issue by lzl124631x** [weui/weui#413]
为什么WeUI中大量使用`transform: scale(0.5);`? 这个会使边框变得更细么?

为什么直觉上会用`border`实现的按键边框, WeUI中使用的是`:after`, 这有什么好处吗?

**Comment by progrape** [comment]
@lzl124631x 因为手机的 retina 屏幕，如果直接设置 `1px` ，实际显示会比 `1px` 粗，达不到设计师想要的效果。所以移动端里面都会整一下 `1px` 线，方案有很多种，可以网上搜索了解。我们用的是其中一种方式。

**Comment by lzl124631x** [comment]
赞. 搜索`retina 1px`能出来我想要的. 非常感谢!
