### ISSUE TITLE
WeUI 在移动端测试时，Click点击事件都会有背景闪烁

### ISSUE THREAD

**Issue by MrChu** [weui/weui#420]
WeUI 在移动端测试时，Click点击事件都会有背景闪烁，能否修复响应延迟的问题？

**Comment by progrape** [comment]
@MrChu 点击延时问题可以通过 [fastclick](https://github.com/ftlabs/fastclick) 来处理。闪烁问题，你试一下在容器加上 `-webkit-tap-highlight-color: transparent;` CSS 规则 ？

**Comment by MrChu** [comment]
@progrape 谢谢！问题已解决！
我也找到了一篇文章：[https://segmentfault.com/a/1190000000339907](https://segmentfault.com/a/1190000000339907)
