### ISSUE TITLE
tabbar和头部怎么固定

### ISSUE THREAD

**Issue by 601774135** [weui/weui#425]
tabbar能不能一直固定在最下面，不管中间有多少东西，一直在下面，我用了文档中的tabbar代码只能固定到不能滑动的界面最底部，如果中间加了东西超出一页，它就不会固定了，为什么？

**Comment by 601774135** [comment]
求大神指点啊，

**Comment by ruansongsong** [comment]
position:fixed ?

**Comment by ynioba** [comment]
position:fixed,会导致出现固定滚动条，所以，上来看，发现也没说怎么固定。。

**Comment by BearJ** [comment]
@601774135 可以把内容放置在.weui-tab__panel里

**Comment by thewangcj** [comment]
html,body{
    height: 100%;
}
