### ISSUE TITLE
单选延时好严重这个有办法修复吗？ 

### ISSUE THREAD

**Issue by 410919244** [weui/weui#433]
radio 点击后1秒后才会被选中。。。机器是iphone 6s plus  性能应该没问题。这个能修复吗？

**Comment by 410919244** [comment]
代码：
`<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
    <title>稽核员考试题库</title>
    <link rel="stylesheet" href="../style/weui.css"/>
    <link rel="stylesheet" href="./example.css"/>

</head>
<body ontouchstart>
    <div class="container" id="container">
		
		<div class="bd">
			<div class="weui_panel weui_panel_access">
				<div class="weui_panel_hd" style="color:#000;font-size:16px;">77.可供出售金融资产应当按取得该金融资产的公允价值和相关交易费用之和作为初始确认金额，支付的价款中包含的已到付息期但尚未领取的债券利息，应单独确认为(   )。</div>
			</div>
			
			<div class="weui_cells weui_cells_checkbox">
				<label class="weui_cell weui_check_label" for="s11">
					<div class="weui_cell_hd">
						<input type="radio" class="weui_check" name="checkbox1" id="s11" checked="checked">
						<i class="weui_icon_checked"></i>
					</div>
					<div class="weui_cell_bd weui_cell_primary" style="color:#000;font-size:14px;">
						<p>A.基本存款帐户、一般存款帐户、临时存款帐户和专用存款账户</p>
					</div>
				</label>
				<label class="weui_cell weui_check_label" for="s12">
					<div class="weui_cell_hd">
						<input type="radio" name="checkbox1" class="weui_check" id="s12">
						<i class="weui_icon_checked"></i>
					</div>
					<div class="weui_cell_bd weui_cell_primary" style="color:#000;font-size:14px;">
						<p>B.基本存款帐户、一般存款帐户、临时存款帐户</p>
					</div>
				</label>
				<label class="weui_cell weui_check_label" for="s13">
					<div class="weui_cell_hd">
						<input type="radio" name="checkbox1" class="weui_check" id="s13">
						<i class="weui_icon_checked"></i>
					</div>
					<div class="weui_cell_bd weui_cell_primary" style="color:#000;font-size:14px;">
						<p>C.基本存款帐户、一般存款帐户、专用存款帐户</p>
					</div>
				</label>
				<label class="weui_cell weui_check_label" for="s14">
					<div class="weui_cell_hd">
						<input type="radio" name="checkbox1" class="weui_check" id="s14">
						<i class="weui_icon_checked"></i>
					</div>
					<div class="weui_cell_bd weui_cell_primary" style="color:#000;font-size:14px;">
						<p>D.基本存款帐户、专用存款帐户、临时存款帐户</p>
					</div>
				</label>
			</div>

			<div class="button_sp_area">&nbsp;</div>

			<a href="#" class="weui_btn weui_btn_primary">下一题</a>
		
		</div>
		

		
	</div>
</body>
</html>
`

**Comment by progrape** [comment]
请看 #14  #227  #420

**Comment by Pumpe** [comment]
可以用fastclick，然后将radio 的pointer-events: none，走label的点击，就可以解决延迟的问题

2016-07-29 10:12 GMT+08:00 410919244 <notifications@github.com>:
