### ISSUE TITLE
rem布局的weui

### ISSUE THREAD

**Issue by chanelnumberfive** [weui/weui#434]
有rem布局的weui吗？看了下weui的css样式都是固定单位，有没有rem布局的weui版本？

**Comment by datoulei** [comment]
我也需要一个rem布局的weui

**Comment by duanhaowei** [comment]
支持，为何微信团队不改成rem？

**Comment by zhangxinxinWTB** [comment]
微信是怎么做适应的。不用rem的话

**Comment by p2227** [comment]
这个问题我了解过。框架职责的问题，weui不入侵开发者的代码，如果你需要转，用构建工具也是很容易做到的。

**Comment by BearJ** [comment]
是的，是出于楼上的想法，不想侵入代码

**Comment by tiemei** [comment]
+1 看来需要自己改写css
