### ISSUE TITLE
input 日期时间类型，是否支持自定义可选时间范围？

### ISSUE THREAD

**Issue by maojindao55** [weui/weui#435]
类似于bootstrap 日期控件，支持范围自定义，范围外的时间不可选，不知道weiui是否支持此功能？

**Comment by dingjia** [comment]
日期时间控件获得的数据 带有中间一个 T , 2016-10-1 T  12：00 这个T好烦人，不能每次做处理吧，怎么破？

**Comment by BearJ** [comment]
@maojindao55 暂不支持，抱歉哈。
@dingjia 可以分开date和time使用；或者自己实现一个选择一个，展示又是另一个dom；或者使用第三方组件。
