### ISSUE TITLE
日期时间控件获得的数据 带有中间一个 T , 2016-10-1 T  12：00 这个T好烦人，不能每次做处理吧，怎么破？

### ISSUE THREAD

**Issue by dingjia** [weui/weui#438]
日期时间控件获得的数据 带有中间一个 T , 2016-10-1 T  12：00 这个T好烦人，不能每次做处理吧，怎么破？

**Comment by yeahisme** [comment]
type datetime-local
> The format is "yyyy-MM-ddThh:mm" followed by optional ":ss" or ":ss.SSS".

**Comment by logoove** [comment]
没有格式化
