### ISSUE TITLE
fastclick与 :active的问题

### ISSUE THREAD

**Issue by p2227** [weui/weui#439]
http://s.codepen.io/progrape/debug/vNQNyj

我用安卓4.04的pad上的qq浏览器打开以上网址，点击发现没有点击反馈
但是用安卓6.0版本上的微信扫描，发现是有点击反馈的
ios则是完全没有问题的

那么这个在引入fastclick之后，要想有 :active 点击反馈，是要取决于css代码，安卓的版本，还是微信里面做了什么处理呢？

**Comment by BearJ** [comment]
@p2227 你好，可以试试自己手动实现fastclick，用touchstart和touchend，然后就会发现部分浏览器，event.preventDefault()导致了:active的不生效。可能是和浏览器内核不一样有关。

**Comment by p2227** [comment]
好吧，简单说就是浏览器兼容性问题。
主要想知道在浏览里面，由于内置了内核，是不是肯定会有点击反馈呢？

**Comment by BearJ** [comment]
IOS和安卓的内核不一样，而安卓的微信现在内核是新版的x5，我手头上的机器没问题，看看你的？

**Comment by p2227** [comment]
我试过安卓4.4/6.0的机和IOS的都没问题。
