### ISSUE TITLE
默认的alert问题

### ISSUE THREAD

**Issue by Imladris** [weui/weui#440]
使用微信网页默认的alert的时候，当确认/取消窗口跳出来第三次，窗口会自动变成确认/关闭网页，请问这个功能怎么取消

**Comment by firesh** [comment]
别用alert。
用weiui里面的dialog

**Comment by sklthegoodman** [comment]
@Imladris 多次alert会伤害用户的体验，建议使用自己定制的弹窗或者使用weui的dialog。
