### ISSUE TITLE
WEUI的图标显示问题

### ISSUE THREAD

**Issue by Mengds** [weui/weui#443]
苹果手机5s-6s都有这个问题，时不时显示不出来字体图标，需要用微信右上角菜单里面的刷新按钮才可以正常显示，我自己从阿里的字体图标下载的在项目里显示都没有问题，不需要多余的刷新，就WEUI这个里面的图标会这样，求帮忙解决下，困扰了好久了！非常感谢！

**Comment by hongweizhiyuan** [comment]
我今天发现手机的图标地址大概是远程地址吧，所以会出现这个问题，官方真是的，这一点儿都不把字体字体开源，真是叫人无言以对！
