### ISSUE TITLE
datetime-local的不能选择时间啊

### ISSUE THREAD

**Issue by leasontou** [weui/weui#444]
在chrome上datetime-local这个只有选择日期的啊，后面--:--里的时间没法选。

**Comment by BearJ** [comment]
这个不是weui的问题吧。。可以试试将date和time两个分开使用

**Comment by gengjiawen** [comment]
嗯，我也发现了，这个属性只有在微信浏览器是正常的。。。Firefox， Chrome全不行。。。

**Comment by gengjiawen** [comment]
不是weui的问题，才发现这个是html5的新特性。。。

**Comment by gengjiawen** [comment]
经我测试，Firefox 52.01，Safari 10.1完全不工作，Chrome 57只能选择日期。

**Comment by gengjiawen** [comment]
Android 上的浏览器竟然支持这个，我试了Smartisan T2自带的浏览器和移动版火狐浏览器，全部支持。看来桌面端主流浏览器基本gg， 移动浏览器支持的很好。
