### ISSUE TITLE
公众平台weui相关文档Github链接错误

### ISSUE THREAD

**Issue by airyland** [weui/weui#445]
文档地址：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1455784134&token=&lang=zh_CN

实际链接：`#https://github.com/weui/weui`

下面的链接都是hash(可能是渲染前处理过导致的？)：

![image](https://cloud.githubusercontent.com/assets/559179/17698971/b8624f7c-63f0-11e6-8703-1ab001872f7b.png)

![image](https://cloud.githubusercontent.com/assets/559179/17698976/c0255a1a-63f0-11e6-9b4a-669975a78099.png)

**Comment by BearJ** [comment]
请参考我们的wiki哈。

**Comment by airyland** [comment]
? 不明白，为什么官方wiki链接错了不改一下。
![image](https://cloud.githubusercontent.com/assets/559179/19231640/b85e65ae-8f0d-11e6-8715-be0026ea190b.png)

**Comment by progrape** [comment]
一个文档放在2个地方的确不好维护，我们改一下 MP 的链接
