### ISSUE TITLE
package.json script脚本名称不一致

### ISSUE THREAD

**Issue by p2227** [weui/weui#447]
https://github.com/weui/weui/blob/00d068bc3e68c29cae517a30b2a22b10864767fc/package.json#L18

npm test的结果居然是release，命名不一致不太好吧

**Comment by progrape** [comment]
@p2227 目前暂时没有什么好办法用工具来测 UI，所以这里测 test 只是运行一下编译，保证没有最基本的语法错误。UI 的测试目前还是人工来看。

**Comment by p2227** [comment]
😂好吧
