### ISSUE TITLE
求tabbar实现tab切换的demo

### ISSUE THREAD

**Issue by daishuyi** [weui/weui#448]
下载下来的没有tabbar切换页面的功能，望大神们给一份demo

**Comment by logoove** [comment]
http://weixin.yoby123.cn/weui/ 非常棒的

**Comment by logoove** [comment]
http://weixin.yoby123.cn/weui/c/tab.html

**Comment by BearJ** [comment]
嗯嗯，可以参考楼上的实现

**Comment by BearJ** [comment]
嗯嗯，可以参考楼上的实现
