### ISSUE TITLE
打开页面一阵子不理它，再滑动页面，偶尔会出现滑不动的情况，这是什么情况呢？

### ISSUE THREAD

**Issue by longboy** [weui/weui#451]
打开页面一阵子不理它，再滑动页面，偶尔会出现滑不动的情况。这是什么情况呢？
像这种有滚动条的页面：https://weui.io/#/cell

**Comment by airyland** [comment]
大概是iOS webview的缺陷，在页面上上下滑动，可能还会出现按钮无法点击的情况。

**Comment by longboy** [comment]
为什么其他页的H5页面就不会有这种问题呢？

**Comment by logoove** [comment]
估计睡着了

**Comment by BearJ** [comment]
@longboy 再看看现在是否存在？在.page下加了z-index:1来fix了
