### ISSUE TITLE
谁有向左滑动出现删除这种效果组件

### ISSUE THREAD

**Issue by logoove** [weui/weui#454]
微信自带的都有这种效果,但是weui并没有,有的贴出个地址,在做微信端管理时候,非常常用,目前只能用弹出菜单解决,效果不是很理想

**Comment by logoove** [comment]
我是weui的忠实粉丝,抛弃一切其他移动端框架,weui是唯一选择

**Comment by suhaotian** [comment]
你自己监听滑动事件，向左滑，显示，向右滑，如果是显示删除按钮的就隐藏。
难点在于如何判断向左滑和向右滑，，可以参考这个：https://github.com/suhaotian/react-swiper。

虽说是用 react 写的，但是核心代码是不变的...

**Comment by BearJ** [comment]
@logoove 是的，这个自己手动写即可，实现并不复杂。因为提出的人不多，所以暂不列入公共库，抱歉哈

**Comment by admin00001** [comment]
我来提出  请列入公共库  这是常用的移动端功能 好吧

**Comment by logoove** [comment]
2017-4-21新增左滑动删除 http://weixin.yoby123.cn/weui/c/cell11.html

**Comment by Yunfei1982** [comment]
这么基础的功能，绝对应该加入公共库

**Comment by charliehower** [comment]
应该加入
