### ISSUE TITLE
为什么没有table

### ISSUE THREAD

**Issue by duanjj** [weui/weui#455]
我想做一个类似的table
![image](https://cloud.githubusercontent.com/assets/6260038/18501442/119310a6-7a83-11e6-95bf-b3a4646aa1b4.png)

**Comment by biu0w0** [comment]
很多网页、插件等用的也是table做layout，不便于全局重定义table样式。
如果类似Bootstrap单独拆分出.table也可行，但是毕竟轻量框架，table还是自己设计吧，或者找第三方库。
