### ISSUE TITLE
为什么body font-family如此设置

### ISSUE THREAD

**Issue by morgan0329** [weui/weui#456]
为什么在boy font-family设置为
font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;

而我觉得更好一点的设置可能是： 
font-family: -apple-system, "San Francisco", "Helvetica Neue", Helvetica, "Droid Sans", Arial, "PingFang SC", "Droid Sans Fallback", sans-serif;

理由：
1 如果是苹果系统，有限由 -apple-system 来决定使用什么字体
2 如果是IOS9或以上，需要决定的话，应该会直接用 "San Francisco",
3 如果是IOS8就用 "Helvetica Neue", Helvetica 
4 如果是IOS中的 中文就用 "PingFang SC"
5 如果Android  英文字  "Droid Sans"
6 如果Android  中文字  "Droid Sans Fallback"

请问这样合适不？

**Comment by biu0w0** [comment]
有同感，支持一下

**Comment by BearJ** [comment]
您好，morgan，我们后面做了修改，是font-family: -apple-system-font, Helvetica Neue ,Helvetica, sans-serif;
而中文字体不作规定。

**Comment by cnyyk** [comment]
不错。
