### ISSUE TITLE
版本跨越太大，0.4.3项目完全不能用了

### ISSUE THREAD

**Issue by aiyuchen** [weui/weui#460]
全部都是乱码，还得还原回去。。。。要升级，这个线上的项目都要改一遍，太难了。。。。

**Comment by hcw2175** [comment]
就是。这帮人在搞什么鬼！！！无语！！！

**Comment by BearJ** [comment]
@airyland @hcw2175 您好，请息怒。
是这样的，因为相比以前的命名规范，新命名规范更利于代码的开发与维护，而且BEM也是广受开发者的接受，我们便采纳了大家提出的建议。
一开始我们内部也是做了很大改动才用上了BEM，过程的确是比较艰辛。对于0.4.3，我们也新建了一条0.4.x的分支作为维护，但可能新组件就要遵循BEM命名了

**Comment by airyland** [comment]
@BearJ 似乎@错人了。不过这个版本真的导致升级困难了。

**Comment by jiuqiang** [comment]
@BearJ 能不能出一个更新差异说明以及新旧对照表（便于统一的查找替换）

**Comment by BearJ** [comment]
@jiuqiang 谢谢你提出这个建议，我将尽快给出

**Comment by justqyx** [comment]
楼主可以用我这个，需要修改的就比较少

https://github.com/justqyx/weui

```css
.weui-cell__bd {
}
.weui-cell_primary {
}

/* 分别被替换成 */

.weui-cell-bd {
}
.weui-cell-primary {
}
```

**Comment by aiyuchen** [comment]
@justqyx 好的

**Comment by shiny** [comment]
@BearJ 请同时提供 0.4.x 的在线文档，文档全更新到 1.x了，老用户感觉到了背叛……

**Comment by HanSon** [comment]
同求0.4.x文档

**Comment by BearJ** [comment]
@shiny @HanSon 可以checkout0.4.x的分支，里面的dist下有对应的DEMO

**Comment by HanSon** [comment]
@BearJ 那也只是DEMO啊。。。就只能看着DEMO来开发？

**Comment by BearJ** [comment]
@HanSon 文档里的内容主要是命名规范变了，思想等是和老版本一致的

**Comment by aiyuchen** [comment]
我听了上面的话，用了2天时间才修改好，见了鬼了，一个项目文件多到吓死你，还有JS也要对应调整。。。。。
