### ISSUE TITLE
1.0.0的preview中，button/input与a标签的样式不一致

### ISSUE THREAD

**Issue by yikuo123** [weui/weui#462]
![qq 20160926111324](https://cloud.githubusercontent.com/assets/13978174/18821596/44472b6c-83da-11e6-8f47-955c0b061e67.png)

浏览器：安卓微信内置浏览器

**Comment by BearJ** [comment]
@yikuo123 您好，的确有这个问题，我们下个小版本修复，你可以先用<a>或者像下面那样修复一下：
button.weui-form-preview__btn{
        background-color: transparent;
        border: 0;
        outline: 0;
        font-size: inherit;
    }

**Comment by BearJ** [comment]
现在1.0.1已经fix了哈

**Comment by yikuo123** [comment]
@BearJ 请问cdn什么时候更新

**Comment by yikuo123** [comment]
@BearJ 我发现这个问题没有彻底解决。
1.demo中两个按钮的情况，第一个是a，第二个是button，显示正常；如果第一个不是a而是button，高度就有问题
2.如果是input type=button或者submit样式仍然不正确，weui-btn weui-btn_primary样式在这几种情况下都是ok的

**Comment by BearJ** [comment]
@yikuo123 你好，第一个问题的确存在，目前你可以手动加上：button.weui-form-preview__btn{line-height: inherit;;}来修复。第二个问题则更建议用button来实现，input type=button或者submit我们是没有适配样式的。

**Comment by BearJ** [comment]
1.1.0 已fixed
