### ISSUE TITLE
咨询命名的问题

### ISSUE THREAD

**Issue by justqyx** [weui/weui#463]
![image](https://cloud.githubusercontent.com/assets/1448539/18822333/45f7ad36-83e1-11e6-8082-92cacb667603.png)

请问这一类命名法是什么哲学？让人使用时猜都猜不到，究竟是要 `_` 还是 `__`。我见过所有的开源项目都是统一地采用 dash case，实在不理解一个项目里混合着 `-`、`_`、`__` 究竟是想要表达什么样的理念。

**Comment by BearJ** [comment]
@justqyx 您好，可以理解为BEM的命名规则，横杠是连词符，双下划线区分B与E，单下划线后面跟Modify.

**Comment by justqyx** [comment]
原来是这样，那可以理解了。

但我还是不喜欢 😭 ，[自己折腾了一下](https://github.com/justqyx/weui/commit/74b24050ccf871431c15f768a62123928eae280d)，不然已存在的项目要改许多地方。
