### ISSUE TITLE
这个库怎么用于微信小程序

### ISSUE THREAD

**Issue by gl5512968** [weui/weui#464]
如题，小程序里虽然自带了一些基础样式，但是和weui相比还差很多。既然weui是为微信网页应用和小应用打造的，应该是可以适用于小程序的。但是改掉后缀（css->wxss）导入后，编译报错。请问将weui用于小程序项目时是否需要转换步骤？如何使用？

**Comment by BearJ** [comment]
@gl5512968 您好，目前还不能直接用到小程序里面，望谅解。

**Comment by zhangqifan** [comment]
会给小程序的设计规范进行统一吗？
希望能尽快将这套ui应用于小程序中。

**Comment by BearJ** [comment]
@zhangqifan 会有规范，但时间点不确定
