### ISSUE TITLE
WeUI 1.0.0在代码层面上做了哪些改变

### ISSUE THREAD

**Issue by BearJ** [weui/weui#466]
[关于1.0.0在代码层面上做了哪些改变](https://github.com/weui/weui/wiki/%E5%9C%A81.0.0%E5%9C%A8%E4%BB%A3%E7%A0%81%E5%B1%82%E9%9D%A2%E4%B8%8A%E5%81%9A%E4%BA%86%E5%93%AA%E4%BA%9B%E6%94%B9%E5%8F%98)

**Comment by machao1990** [comment]
css改了，但是js里的css没改过来呢。。

**Comment by wwhyes** [comment]
命名规则也没有说明 _ 和 __ 、 -  的用法具体是什么

**Comment by BearJ** [comment]
@machao1990 你好，weui.js上的dev分支已经改了哈

**Comment by flashtd1** [comment]
weui-btn_area是不是取消了呀？我在新的文档里没有看见这个，那是不是inline也不能用了？是都改用flex布局来实现了吗？

**Comment by wwhyes** [comment]
@flashtd1 .weui-btn-area .weui-btn_inline
