### ISSUE TITLE
关于 .actionsheet__mask

### ISSUE THREAD

**Issue by chunzi** [weui/weui#467]
.actionsheet__mask{display:none;-webkit-transition:background .3s;transition:background .3s}
.actionsheet__mask_show{background:rgba(0,0,0,.6)}

这两行在 example.css 中，而非 weui.css 中。
于是 actionsheet 的示例代码移到项目中，便失效了。坑啊。

另外，个人觉得新的命名方式太折腾，忽高忽低。倒不如一律短横线连接更清晰。

**Comment by justqyx** [comment]
https://github.com/weui/weui/issues/463

官方解释因为采用了 BEM 命名的方法，这没什么问题，只是不习惯用起来的确很操蛋，于是我折腾了一下，全部换成 dash case 的形式 https://github.com/justqyx/weui  利用 postcss 在编译时修改了命名，用我自己写的 [postcss-selector-style](https://www.npmjs.com/package/postcss-selector-style) 实现

**Comment by chunzi** [comment]
Awesome! Will have a try, thanks!

**Comment by BearJ** [comment]
嗯嗯，其实可以自己替换的
