### ISSUE TITLE
能不能单独提供组件的js文件，example.js直接引用186报错

### ISSUE THREAD

**Issue by godseo** [weui/weui#469]
单独调用组件的时候，需要一个单独的组件js。

**Comment by BearJ** [comment]
如果你指的是路由的话可以看这里：https://github.com/progrape/router

**Comment by godseo** [comment]
我指的是把例子里js代码抽离出来，封装成组件js 。只要单独的js就能使用。

**Comment by sandmanman** [comment]
@godseo  官方好像并没有单独做JS组件。你可以瞅瞅这个：https://github.com/lihongxun945/jquery-weui

**Comment by logoove** [comment]
看看我的<weixin.yoby123.cn/weui>
