### ISSUE TITLE
[bug]can't add people to wechat group on osx when there are more than 50 people in a group

### ISSUE THREAD

**Issue by zzz6519003** [weui/weui#47]

**Comment by progrape** [comment]
谢谢反馈，已转给相关开发同事跟进

**Comment by zzz6519003** [comment]
cheers!

2015-10-26 14:56 GMT+08:00 jf <notifications@github.com>:

> Closed #47 <https://github.com/weui/weui/issues/47>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/weui/weui/issues/47#event-445194428>.
>



-- 

yours,

正中赵
about.me/zzz6519003
[image: 正中赵 on about.me]
  <http://about.me/zzz6519003>
