### ISSUE TITLE
1.0.0的cdn 是不是一直在修改

### ISSUE THREAD

**Issue by qq71151461** [weui/weui#470]
//res.wx.qq.com/open/libs/weui/1.0.0/weui.min.css
里面的样式名，
一会儿是 weui-media-box__thumb 一会儿是 weui-media__thumb
导致我们项目一会正常一会不正常~~~你们是不是还在纠结怎么命名啊~~~
老的方式多好！！！
我很奇怪，cdn上的文件，还会经常在变？

**Comment by pengliang159** [comment]
是啊！不只是这里啊，一会weui.css里有weui-media__title这个类，一会又跑到weui.min.css里了，一会weui.min.css里没有了。换成weui.css，又有了这个类，我去，刷新一下页面，样式就突然变了。而且weui.css和weui.min.css内容居然不一样，导致我一会换weui.css，一会换weui.min.css。看来要下载保存到本地了

**Comment by BearJ** [comment]
@qq71151461 @pengliang159 这里应该统一是叫media-box的，CDN的问题我们跟进一下。

**Comment by icodegame** [comment]
我试了下，原 weui-media__ 都改为了 weui-media-box__
