### ISSUE TITLE
dialog的opacity不为1时，button会出现在dialog上方

### ISSUE THREAD

**Issue by SCUT-hao** [weui/weui#479]
新版本弹出dialog从show()变成fadeIn(100)了，但如果页面上有button，在fadeIn的过程中button并不会被mask挡住。
![image](https://cloud.githubusercontent.com/assets/15966914/18979232/a712bb5c-86fb-11e6-966c-85548958e6d1.png)

**Comment by BearJ** [comment]
@SCUT-hao 你好，我这里没有重现哦。请问有测试链接吗？

**Comment by yeliex** [comment]
https://www.qianduan.net/that-thing-on-the-z-index/
