### ISSUE TITLE
[BUG]不知道算不算bug，样式有点问题请看截图

### ISSUE THREAD

**Issue by Markxuxiao** [weui/weui#48]
![image](https://cloud.githubusercontent.com/assets/9879038/10683809/89d77af0-7978-11e5-890d-5ed85282eed1.png)

我用mx3手机测试过，用chrom iPhone4也是这样。

**Comment by Markxuxiao** [comment]
查看详情和取消按钮挤到一块了

**Comment by progrape** [comment]
因为demo的缘故，我们在顶部加了“Msg”的文字，正常使用下是没有的，所以在大部分手机“查看详情”不会盖在按钮上面。

![c315cd44-8113-4c38-adde-022628caf0f2](https://cloud.githubusercontent.com/assets/4652816/10684121/67785b2e-797c-11e5-8f13-4848da828a84.png)

如果描述的文字有很多行（不推荐太多文字），或者手机屏幕太短，又需要底部的“查看详情”小链接，确实有可能出现这种盖在按钮的情况。
