### ISSUE TITLE
1.0.1 weui-media__info 样式木有

### ISSUE THREAD

**Issue by 2doous** [weui/weui#482]
1.0.1 weui-media__info 样式木有，1.0.0有，导致panel样式出现问题

**Comment by BearJ** [comment]
@2doous 你好，在1.0.1weui-media已更名为weui-media-box，因为只是media会有歧义。所以weui-media__info也随之更名为weui-media-box__info。

**Comment by 2doous** [comment]
oh yeah！3Q u~ 官方的demo确实也慢了一步跟进，拿到手的demo代码，都是基于老版本的，所以问题还是蛮多的。
