### ISSUE TITLE
grids使用时发现UI bug

### ISSUE THREAD

**Issue by mzzq** [weui/weui#483]
[我使用weui-grids类，就是上面给出的例子，如果单元格中的文字中有中文逗号，每个单元格之间的衔接会出问题]
![qq 20161006144934](https://cloud.githubusercontent.com/assets/12298528/19143090/34bf8462-8bd4-11e6-931c-1cbc442f5433.png)

**Comment by progrape** [comment]
收到，我们排查一下~

**Comment by progrape** [comment]
@mzzq 文字过多会导致这个问题，我们限制一下，文字过多的时候自动用“...”代替

![image](https://cloud.githubusercontent.com/assets/4652816/19218781/43d353d0-8e35-11e6-8501-92734db47837.png)
