### ISSUE TITLE
我发现文档和实际的css样式命名有错

### ISSUE THREAD

**Issue by frank-young** [weui/weui#484]
文档：weui_btn
实际应该是：weui-btn
很多地方有类似的错误

**Comment by logoove** [comment]
文档没改过来 这种命名 虽说有优点 缺点也很明显 容易混乱 不好记忆

**Comment by BearJ** [comment]
@frank-young 你好，是哪里的文档？方便贴一下url吗？

**Comment by frank-young** [comment]
https://mp.weixin.qq.com/wiki/2/ae9782fb42e47ad79eb7b361c2149d16.html
`weui_btn_primary、weui_btn_default、weui_btn_warn`
这些都有错误

**Comment by logoove** [comment]
人家没有错误  上边只是老文档 0.44的  1.01还没有贴上去

**Comment by frank-young** [comment]
了解了，
