### ISSUE TITLE
Bower 上面的 weui 版本没有更新，还是 0.4.1

### ISSUE THREAD

**Issue by YaoaY** [weui/weui#492]
没有 1.0.1 。

**Comment by progrape** [comment]
@YaoaY bower 是读取 github 上的 tag 来安装的，1.0.1 已经打过 tag了。刚才试了运行 `bower install weui` 下安装，可以安装到最新版本。你试试看？

**Comment by YaoaY** [comment]
好的，是VS的问题，现在有了，谢谢。
