### ISSUE TITLE
1.0.1版本release修复的media-box缺失box问题在文档中未更新

### ISSUE THREAD

**Issue by YokiMing** [weui/weui#493]
官方文档weui.io

**Comment by BearJ** [comment]
@YokiMing 你好，已做出说明：[在1.0.0在代码层面上做了哪些改变#panel](https://github.com/weui/weui/wiki/%E5%9C%A81.0.0%E5%9C%A8%E4%BB%A3%E7%A0%81%E5%B1%82%E9%9D%A2%E4%B8%8A%E5%81%9A%E4%BA%86%E5%93%AA%E4%BA%9B%E6%94%B9%E5%8F%98#panel)

**Comment by xanahopper** [comment]
@BearJ 但是官方的代码中，似乎还在沿用weui-media__thumb这种用法

**Comment by BearJ** [comment]
@xanahopper weui.io的现在都是改成weui-media-box了哈，统一了。
