### ISSUE TITLE
左右滑动删除

### ISSUE THREAD

**Issue by jivaklong** [weui/weui#496]
怎么没有找到左右滑动删除功能 ？

**Comment by BearJ** [comment]
你好，这个目前是没有的

**Comment by code-artisan** [comment]
@BearJ 未来的版本中是否会添加？

**Comment by BearJ** [comment]
因为安卓用户没有这种习惯，所以不添加的可能性较大。

**Comment by logoove** [comment]
这个真是太需要了 很多人求这个  目前只有react版本 js能力有限  想改成普通的 没成功

**Comment by code-artisan** [comment]
React 不也是 JS 写的么。。。Framework 7 这些其实都是已经集成了的，网上找了几个感觉不怎么好，我主要是想用在微信小程序里面 😃

**Comment by logoove** [comment]
react有个写的非常好 <https://github.com/dancormier/react-native-swipeout>能改写成普通js吗

**Comment by yhhwpp** [comment]
@logoove  当然可以 研究研究他的源码

**Comment by jivaklong** [comment]
目前我使用的是 https://git.oschina.net/nandy007/agile-lite  这个跟weui结合实现了自己想在的功能
weui的界面做得非常简洁，非常不错。

**Comment by BearJ** [comment]
合并 #559

**Comment by logoove** [comment]
2017-4-21新增左滑动删除 http://weixin.yoby123.cn/weui/c/cell11.html

**Comment by code-artisan** [comment]
💯 100 分，不怕你骄傲
