### ISSUE TITLE
样式库中button的实际css和教程的不一致

### ISSUE THREAD

**Issue by cinbo-github** [weui/weui#497]
weui.css中 button的class 是 weui-btn
而教程中 写的是 weui_btn
完全误导别人啊。

**Comment by cinbo-github** [comment]
进一步查找，发现好多都不一致。
而且，有的下划线居然是2个的。文档和实际出入太大了。

**Comment by BearJ** [comment]
你好，请问是看了哪里的文档？github的文档：https://github.com/weui/weui/wiki
