### ISSUE TITLE
是否有图片轮播组件？

### ISSUE THREAD

**Issue by yunbookf** [weui/weui#498]
这个组件确实很重要，流畅且丝滑柔顺，现在有吗

**Comment by BearJ** [comment]
你好，现在是没有的，可以去gitbhub上搜，这类组件很多

**Comment by 601774135** [comment]
swiper,就是专门做轮播的，你可以去看一下中文文档

**Comment by zhangwei900808** [comment]
@BearJ 轮播的时候也可以删除，就像微信添加照片那种功能，或者说有没有类似这种功能的插件呢，求推荐

**Comment by BearJ** [comment]
@zhangwei900808 这个可以做一个元素fix在底部就可以了，插件倒是没有这么细的功能
