### ISSUE TITLE
请问1.0每次进入页面的事件是怎获得的？

### ISSUE THREAD

**Issue by lufreezz** [weui/weui#499]
之后0.4是用render,bind.现在这两个不能用了。要怎解决？

**Comment by BearJ** [comment]
你好，现在1.0是针对example写的js，要用router.js，请下载0.4.x的分支看以前的运用方法

**Comment by lufreezz** [comment]
那新版，想监控页面进入事件，应怎写？

**Comment by BearJ** [comment]
调用setPageAppend，参考example.js 269行
