### ISSUE TITLE
有没有计划提供scss版？

### ISSUE THREAD

**Issue by haibinyu** [weui/weui#5]

**Comment by progrape** [comment]
暂时没有这个计划

**Comment by xierenyuan** [comment]
0.0  如果能提供sass 版本 就美美哒

**Comment by kevyu** [comment]
@xierenyuan 我提交了一个sass版本的weui，https://github.com/kevyu/weui-sass，可供参考， :smile: 。

**Comment by xierenyuan** [comment]
@kevyu   太好呢 -。- 先去star

**Comment by navcat** [comment]
@kevyu 可否考虑在原仓库下建一个分支，专门支持SASS?

**Comment by kevyu** [comment]
@navcat 分支的话感觉不好找，不知道能不能在weiui下面新建一个weui-sass的repo？@progrape
