### ISSUE TITLE
为什么没有标准文档呢？weui-cells__title 和 weui_cells_title的差异？

### ISSUE THREAD

**Issue by qiulu** [weui/weui#500]
https://github.com/weui/weui/wiki/ 里面的样式 都是 weui-cells__title 这样的结构（前面一个中划线，后面两个下划线），但实际css文件中的样式全都是单个下划线的（如weui_cells_title）。
为什么会有这样的差异？
有没有最新的完整文档？

**Comment by qiulu** [comment]
我明白了，是版本的问题，一个是0.x版本，一个是1.x版本。
那么是不是将 weui_cells_title 改成 weui-cells__title 就可以在不同版本间切换。
两个之前还有哪些差异？

**Comment by BearJ** [comment]
你好，详情可以看这里：[差异]https://github.com/weui/weui/wiki/%E5%9C%A81.0.0%E5%9C%A8%E4%BB%A3%E7%A0%81%E5%B1%82%E9%9D%A2%E4%B8%8A%E5%81%9A%E4%BA%86%E5%93%AA%E4%BA%9B%E6%94%B9%E5%8F%98
