### ISSUE TITLE
建议把元素选择器改成类选择

### ISSUE THREAD

**Issue by code-artisan** [weui/weui#501]
建议把元素选择器改成类选择，这样的话在微信小程序里面（微信小程序里面的标签并非和 HTML 标签一致）也能尽情的玩耍了。。。

![image](https://cloud.githubusercontent.com/assets/5195218/19336882/c48b67ce-9141-11e6-87fc-5b018dd67579.png)
--->
![image](https://cloud.githubusercontent.com/assets/5195218/19336888/d719febe-9141-11e6-860f-14e25558ff6c.png)

**Comment by BearJ** [comment]
这样的话不是小程序的用户就可能会抓狂，未来考虑出个小程序对应的版本。

**Comment by code-artisan** [comment]
哈哈，确实如此，单独出版本可行是可行，就是维护起来有点。。。辛苦辛苦 🍰 ❤️
