### ISSUE TITLE
能不能把https://mp.weixin.qq.com/wiki?action=doc&id=mp1455784134&t=0.7470451662471673&token=&lang=zh_CN#https://github.com/weui/weui 页面的例子改一下，坑人啊

### ISSUE THREAD

**Issue by jsspace** [weui/weui#503]
**https://mp.weixin.qq.com/wiki?action=doc&id=mp1455784134&t=0.7470451662471673&token=&lang=zh_CN#https://github.com/weui/weui** 页面里的例子，用的class都是错的，错的，错的。。。。。。。

**Comment by BearJ** [comment]
你好，已向相关同事反映，等他们更新哈。
