### ISSUE TITLE
iput标签在chrome里面，不能连续输入

### ISSUE THREAD

**Issue by tong3jie** [weui/weui#507]
iput标签在chrome里面，不能连续输入

`

<div class="weui-cells weui-cells_form" id="phoneNum">
            <form name="user" novalidate>
                <div class="weui-cell">
                    <div class="weui_cell_hd"><label class="weui_label" style="width: 75px">手机</label></div>
                    <div class="weui-cell__bd">
                        <input class="weui-input" name="phoneNum" ng-model="phoneNum" type="tel"
                               ng-pattern="/^1[3|4|5|7|8]\d{9}$/"
                               maxlength="11" placeholder="请输入您的手机号"
                               ng-bind="formatPhoneNum = user.phoneNum.$viewValue"/>
                    </div>
                </div>
            <span class="text-warning" ng-show="user.phoneNum.$dirty && user.phoneNum.$invalid"
                  style="margin-left: 5px">请输入正确的手机号码</span>
            </form>
 </div>
`

**Comment by tong3jie** [comment]
<div class="weui-cells weui-cells_form" id="phoneNum">
            <form name="user" novalidate>
                <div class="weui-cell">
                    
                    <div class="weui-cell__bd">
                        <input class="weui-input" name="phoneNum" ng-model="phoneNum" type="tel"
                               ng-pattern="/^1[3|4|5|7|8]\d{9}$/"
                               maxlength="11" placeholder="请输入您的手机号"
                               ng-bind="formatPhoneNum = user.phoneNum.$viewValue"/>
                    </div>
                </div>
            <span class="text-warning" ng-show="user.phoneNum.$dirty && user.phoneNum.$invalid"
                  style="margin-left: 5px">请输入正确的手机号码</span>
            </form>
        </div>

**Comment by BearJ** [comment]
你好，导致这个问题貌似不是weui。。。
