### ISSUE TITLE
手势返回时，动画显示两遍

### ISSUE THREAD

**Issue by sutra** [weui/weui#509]
OS: iOS 10.0.2
Browser: Safari

**Comment by BearJ** [comment]
你好，请问是指哪个动画？

**Comment by sutra** [comment]
第一遍是跟随手指的，可以来回动的，应该是Safari浏览器自己的那个动画；
第二遍似乎是weui模拟出来的一闪而过的动画。

**Comment by BearJ** [comment]
你好，这个应该是webview本身的bug，我直接点左上角的返回是没问题的。

**Comment by sutra** [comment]
点击返回按钮只有“第二遍”的那个动画。

**Comment by BearJ** [comment]
是的，那个才是我们想要的效果

**Comment by sutra** [comment]
但是手势返回时就很难受。像有一只鸟儿从眼前飞过。

**Comment by BearJ** [comment]
那这里你可以不用example的飞入飞出的动画，或改用其它的。这样体验会好一点。

**Comment by YangJianFei** [comment]
请问一下https://weui.io/0.4.x/#/这里面的动画效果。我怎么都没有呢。

**Comment by BearJ** [comment]
@YangJianFei 你有把css也带上吗？

**Comment by YangJianFei** [comment]
@BearJ <link rel="stylesheet" href="../../css/common/weui.min.css">

**Comment by YangJianFei** [comment]
"../../css/common/weui.min.css"

**Comment by BearJ** [comment]
@YangJianFei 动画效果是通过.cell.enter和.cell.leave来控制的，你看看有没有生效？

**Comment by YangJianFei** [comment]
![animateexample](https://cloud.githubusercontent.com/assets/16703333/20258441/ab08b9ca-aa8a-11e6-8bbb-1ffd76001e09.gif)
是这种动画没有@BearJ

**Comment by BearJ** [comment]
@YangJianFei 你把你引用的css文件发一下？

**Comment by YangJianFei** [comment]
[common.txt](https://github.com/weui/weui/files/588976/common.txt)
不支持css我换成了txt。
版本低了吗

**Comment by BearJ** [comment]
@YangJianFei 嗯嗯，那你引用的weui呢？也发一下？

**Comment by YangJianFei** [comment]
class="weui_actionsheet weui_actionsheet_toggle";理解了是我动态添加class有问题。我是先把toggle加上去了。然后用display=none 来让他们显示不显示
