### ISSUE TITLE
可以提供颜色规范吗

### ISSUE THREAD

**Issue by whjspdi** [weui/weui#512]
想知道微信web页面/小程序 系列的颜色。懒得从css里去找啊。谢谢

**Comment by progrape** [comment]
@whjspdi 系列颜色请问是指哪些颜色？视觉稿在这里  https://github.com/weui/weui-design，有 PSD 和 Sketch 版本的，或者可以看 less 中定义的变量 ？https://github.com/weui/weui/blob/master/src/style/base/variable/color.less

**Comment by whjspdi** [comment]
比如按钮 绿色啊（激活、禁用等）、灰色（边框、背景等）啊。color.less 不全。做开发的可能更希望一个快捷的颜色代码查询列表。 close吧。
http://www.bootcss.com/p/flat-ui/
