### ISSUE TITLE
最新weui项目中less版本没有更新

### ISSUE THREAD

**Issue by YokiMing** [weui/weui#516]
![image](https://cloud.githubusercontent.com/assets/8777339/19549575/aa3e479c-96d7-11e6-805b-6aec87f20001.png)
![image](https://cloud.githubusercontent.com/assets/8777339/19549589/ba349dea-96d7-11e6-8417-f2f21da2b910.png)
**如图 缺少许多兼容**

![image](https://cloud.githubusercontent.com/assets/8777339/19549615/e2bc92c2-96d7-11e6-84fa-ee9e50524306.png)

**标出的区域为缺少的属性**

**Comment by YokiMing** [comment]
@BearJ

**Comment by BearJ** [comment]
你好，添加前缀我们是交给编译脚本去完成的：https://github.com/weui/weui/blob/master/gulpfile.js line34
