### ISSUE TITLE
class 命名规则能不能统一用一种？难理解啊？

### ISSUE THREAD

**Issue by CN-984XN** [weui/weui#517]
**证据：**
    1、weui-btn_plain-default
    2、weui-cells__title
**说明：**
有 - 还有 _ 还有 __ **太难记了**，不能统一用 _ 或者统一用 - 或者驼峰？ 
**示例：**
这样不挺好的吗：
    1、weui-btn-plain-default
    2、weui-cells-title

**Comment by czy0729** [comment]
weui把class改成这样实在太好了, 你觉得不好证明是你不理解, 这语法比纯一杆的意义多了很多

**Comment by YokiMing** [comment]
横杠为连词符，双下划线区分Block和Element（BEM），单下划线连接Modify。
觉得不好是因为你没有理解这样命名的理由。

**Comment by BearJ** [comment]
@CN-984XN 我们是使用了BEM的方式，希望这篇文章对你有帮助：http://www.w3cplus.com/css/bem-definitions.html

**Comment by CN-984XN** [comment]
@BearJ @YokiMing 是我知道的太少了，学习了，让大伙见笑了，^_^
