### ISSUE TITLE
button使用weui-vcode-btn样式错误

### ISSUE THREAD

**Issue by yikuo123** [weui/weui#519]
![qq 20161025174849](https://cloud.githubusercontent.com/assets/13978174/19681340/a1e1698c-9adb-11e6-8d7a-eeb5f3823c77.png)

demo中使用的a，样式是正确的。如果换成button，样式不正确。

**Comment by BearJ** [comment]
@yikuo123 谢谢，的确存在这个问题，下个版本fix

**Comment by yikuo123** [comment]
@Bearj 另外，建议为这个增加一个禁用的样式

**Comment by BearJ** [comment]
@yikuo123 这里是建议用户点击了之后给出提示（没填/位数不正确），而不是disabled。所以我们没有加disabled

**Comment by BearJ** [comment]
1.1.0 已fixed

**Comment by BearJ** [comment]
1.1.0 已fixed
