### ISSUE TITLE
可否发布一个兼容微信小程序WXSS的版本

### ISSUE THREAD

**Issue by ThorbJ** [weui/weui#520]
你好，由于微信小程序的样式语言WXSS样式语言不兼容部分CSS特性，可否发布一个兼容WXSS的版本？

**Comment by BearJ** [comment]
@ThorbJ 你好，正在筹划中

**Comment by FlorCava** [comment]
同支持此提议，比如navBar，小程序官方组件中没有，如果有官方样式也可以

**Comment by BearJ** [comment]
@ThorbJ @FlorCava 发布了，请看：https://github.com/weui/weui-wxss/
