### ISSUE TITLE
datetime-local  的 step 属性不生效

### ISSUE THREAD

**Issue by JoeShi** [weui/weui#521]
`<input class="weui-input" type="datetime-local" step="1800"></input>`

以上这段代码，为甚么不生效，我写了step步长，但是时间选择器依然可以选 1分钟的时间。

**Comment by BearJ** [comment]
@JoeShi step不是那个意思：http://www.w3schools.com/jsref/prop_datetime-local_step.asp

**Comment by JoeShi** [comment]
额，请问一下，我应该在吗做到啊。 就是间隔只允许 15 分钟那种。谢谢

**Comment by BearJ** [comment]
step=900试试

**Comment by JoeShi** [comment]
@BearJ 一样的，真机上没有用。

**Comment by madre** [comment]
@JoeShi step 现在主流的浏览器都没支持，无论设置什么都没用的

**Comment by BearJ** [comment]
@JoeShi 这里建议你可以使用picker

**Comment by JoeShi** [comment]
多谢 @BearJ
