### ISSUE TITLE
type：date的日期控件在ios无法显示怎么办？

### ISSUE THREAD

**Issue by lqmd** [weui/weui#525]

**Comment by BearJ** [comment]
是否代码有问题？被遮挡什么的？你试试直接简单写个input type="date"在一个空页面，看能否显示。实在不行就采用第三方库吧。

**Comment by izyh** [comment]
这是因为datePicker的start和end格式没写对，ios会导致整个页面崩溃，正确格式应该是xxxx-xx-xx，即年4位，月4位，日4位.

**Comment by BearJ** [comment]
@izyh 最新版允许传date对象了~ ^_^
