### ISSUE TITLE
建议添加一个 Slider 控件

### ISSUE THREAD

**Issue by ItsFated** [weui/weui#530]

**Comment by BearJ** [comment]
@NewdBe Slider是指滑动器吗？

**Comment by jwjgauss** [comment]
嗯，slider组件现在用得这么多啊，应该添加一个slider组件

**Comment by BearJ** [comment]
好的，敬请期待

**Comment by NewdBe** [comment]
对是滑动器。拭目以待

**Comment by BearJ** [comment]
更新一下，我指的是滑块。。可能不是那个滑动器的意思。是类似input[type="range"]的：http://www.w3school.com.cn/tiy/t.asp?f=jsref_range_get

**Comment by NewdBe** [comment]
http://jqueryui.com/slider/#multiple-vertical
我说的是这个。。。

**Comment by BearJ** [comment]
这里在v1.1.0已增加~

**Comment by OYsun** [comment]
是否能更新一下slider的wiki

**Comment by BearJ** [comment]
@OYsun 已加
