### ISSUE TITLE
你们的开发文档有点问题啊

### ISSUE THREAD

**Issue by DavidGongHongShen** [weui/weui#532]
https://mp.weixin.qq.com/wiki/2/ae9782fb42e47ad79eb7b361c2149d16.html#.E6.A6.82.E8.BF.B0
我在网页上看的
![image](https://cloud.githubusercontent.com/assets/23496002/20340023/72dededa-ac1a-11e6-9c53-c2c8a37a8d29.png)
weui-btn weui-btn_disabled weui-btn_primary
在你们文档上是"weui_btn weui_btn_plain_primary
一个 "-" 一个'_'

**Comment by BearJ** [comment]
@DavidGongHongShen 你的链接是保存下来的吧，现在的已经改了很久了。。。请看：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1455784134&token=&lang=zh_CN

**Comment by yyecust** [comment]
真的是有问题啊 今天也被啃了几分钟
就是这个
https://mp.weixin.qq.com/wiki/2/ae9782fb42e47ad79eb7b361c2149d16.html
从这里点进去的
https://mp.weixin.qq.com/wiki/home/index.html
建议修改

**Comment by BearJ** [comment]
@yyecust 已反馈给相关同事，谢谢你的提醒。最新文档请看我们的wiki。

**Comment by wskeee** [comment]
我也被坑过，老是看到旧版本的。
文档不清析，差评

**Comment by BearJ** [comment]
@wskeee 你是把老地址保存下来了不？如果是，要更新一下：https://mp.weixin.qq.com/wiki

**Comment by Macsgl** [comment]
github上的wiki是对的,但是微信公众平台上的文档还是有问题的

**Comment by BearJ** [comment]
@Macsgl 公众平台现在的链接是对了的。如果是有问题，可能你是保存了以前的链接，这个是最新的https://mp.weixin.qq.com/wiki
