### ISSUE TITLE
建议调整 weui-cell_access

### ISSUE THREAD

**Issue by ZoomZhao** [weui/weui#533]
weui-cell_access 的目标应该是可以点击跳转的项目。

1. 现状
  通过  .weui-cell_access .weui-cell__ft::after 的方式提供了右向箭头提示可点击
2. 给你带来了什么问题
  如果只是需要箭头的话，需要增加一个空白节点 .weui-cell__ft。并且从语义上，应该是 .weui-cell_access::after 比较贴切。
3. 你的期望结果
  调整 .weui-cell_access 的实现，将 arrow 从 .weui-cell_access .weui-cell__ft 移动到 .weui-cell_access

可能的问题：

会不会存在需要点击，又不需要右向箭头指示的地方，如果存在的话，需要考虑怎么处理。（当前 Demo 中的搜索下面实时搜索文本就没有右向箭头）

**Comment by uxsi** [comment]
@ZoomZhao  关于cell的跳转状态在weui的设计里面包括点击态和可选的箭头说明，一开始箭头是一个独立的`i`标签，weui-cell_access只做点击态的样式，倒是符合你提到的场景。

迭代过程，我们发现组件里面需要去记住的接口太多，这样对于开发者来说存在一定的使用成本，特别是一些需要紧急处理的场景下成本会扩大。所以我们简化了这里的实现，在cell跳转这里只对外暴露weui-cell_access。如果把箭头样式附加在了这个class上，像你提到的，会遇到需要点击，但不需要箭头的场景，这时候组件层面不得不增加多一个扩展类来隐藏箭头，类似的做法我们也用了一段时间，这种结果还是没有解决简化接口的目的。

最后折中采用现在的方案，在实现上，需要箭头就带上ft，另外语义上也有另一种思路，箭头当做是跳转项的补充说明，这时候ft的存在也是合理的。

倒是可能会遇到需要点击、不需要箭头、但是还有其它图标例如详情放在ft的情况，但是跟设计师沟通暂时不会出现这种场景。
