### ISSUE TITLE
安卓下  Actionsheet打开后  在webView中后退链接， actionsheet一直遮罩

### ISSUE THREAD

**Issue by jianmo123** [weui/weui#534]

**Comment by BearJ** [comment]
@jianmo123 你好，example在一些老式机上是可能会出现这个问题。解决方法是，检测页面后退时，把mask隐藏掉。example只是个实例代码，所以就不加入太多的逻辑了。

**Comment by jianmo123** [comment]
多谢，已经解决了 和你这个思路一样

________________________________
jianmolala@outlook.com

发件人： bear<mailto:notifications@github.com>
发送时间： 2016-11-17 17:17
收件人： weui/weui<mailto:weui@noreply.github.com>
抄送： GengPu<mailto:jianmolala@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题： Re: [weui/weui] 安卓下 Actionsheet打开后 在webView中后退链接， actionsheet一直遮罩 (#534)

@jianmo123<https://github.com/jianmo123> 你好，example在一些老式机上是可能会出现这个问题。解决方法是，检测页面后退时，把mask隐藏掉。example只是个实例代码，所以就不加入太多的逻辑了。
