### ISSUE TITLE
关于黑色图片的icon变灰的问题

### ISSUE THREAD

**Issue by mingjiu** [weui/weui#535]
在官方事例中，home页面，每一项点击后，会展开当前的小选项，如：表单点击展开button, input, list, uploader这四项，原先【表单】这里有个icon，这个icon的颜色本身是黑色的，是什么原理改成灰色。

我看了源码，点击事件仅仅是在父元素添加js_show以及一些高度计算，没有看到相关处理，less里边也没有filter之类的样式，真心请教实现原理（好奇心爆发不可收拾）

**Comment by kevyu** [comment]
通过chrome看一下就知道是通过动态添加class的方式修改 opacity: 0.4

**Comment by mingjiu** [comment]
@kevyu 谢谢，我也看到了！！！
