### ISSUE TITLE
微信开发者工具最新版鼠标飘逸

### ISSUE THREAD

**Issue by justinyaoqi** [weui/weui#536]
不知道在哪能提交。在这发一下
Windows 10 x64
1080p下ok。
4k下鼠标漂移。

**Comment by BearJ** [comment]
好的，我反馈一下给相关开发同事。

**Comment by BearJ** [comment]
@justinyaoqi 对了，这里有个官方的小程序开发者社区：http://developers.weixin.qq.com/

**Comment by ydq** [comment]
![image](https://cloud.githubusercontent.com/assets/8097340/20475565/7e083824-b007-11e6-93f0-1a2f79b4e65e.png)

@BearJ 开发者社区登录不了呀，明明已经是三个公众号的开发者了，却还提示**请用管理员或开发者微信号扫描二维码登录**，这个权限应该允许开放吧。

**Comment by BearJ** [comment]
@ydq 是的，你的微信号发一下？

**Comment by justinyaoqi** [comment]
@BearJ 我微信 dolly_17

**Comment by BearJ** [comment]
@justinyaoqi 你也不能进入开发者社区吗？

**Comment by justinyaoqi** [comment]
@BearJ 进不去。麻烦把我拉进去

**Comment by ZhangYangDev** [comment]
我也进不去，求拉一下

**Comment by BearJ** [comment]
楼上各位，的确做了权限控制，请大家等候小程序的公开发布。
