### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by scscms** [weui/weui#538]
首先demo里源代码里出现</script></script>错误标签。
for (var i = 0, len = this._configs.length; i < len; i++) 之类的建议写for (var i = this._configs.length; i --;) 甚至使用forEach。
 `      _find: function (key, value) {
            for (var i = this._configs.length; i --; ) {
                if (this._configs[i][key] === value) {
                    return this._configs[i];
                }
            }
            return null;
        },`
基于zeptojs库就不防尽可能使用库已经封装好的方法。

**Comment by BearJ** [comment]
@scscms 谢谢您的建议。这里：
- </script></script>一个是属于template的，一个是普通的script。之所以这样写是为了方便开发者查看代码。
- `i--`这个是倒序循环，我们用的是顺序循环，所以这里不一样
- forEach，因为不支持break，所以没采用。
