### ISSUE TITLE
建议添加一个日期控件

### ISSUE THREAD

**Issue by andy1028** [weui/weui#540]
建议添加一个日期控件

**Comment by BearJ** [comment]
你好，你可以用picker来实现，详情请看：https://weui.io/#picker

**Comment by andy1028** [comment]
picker 依赖了wxui.min.js  但是这个js，你们好像还没有开源出来对吧

**Comment by BearJ** [comment]
已经开源了，请看 https://github.com/weui/weui.js

**Comment by polyrabbit** [comment]
赞，已star
