### ISSUE TITLE
方便公开https://team.weui.io/jfeng/weui-wechat/的源码吗？

### ISSUE THREAD

**Issue by imicer** [weui/weui#542]
很想参考一下 https://team.weui.io/jfeng/weui-wechat  的源码，方便公开吗？

**Comment by progrape** [comment]
@imicer 可以，都是用 weui 的组件拼装的，我找时间写一下简单的说明公开~

**Comment by imicer** [comment]
@progrape  太感谢你了！有没有确定的时间节点？这么优秀的框架和示例，让我迫不及待……

**Comment by progrape** [comment]
@imicer 你好，这里 https://github.com/progrape/weui-wechat
