### ISSUE TITLE
[feature request] 步骤条 steps

### ISSUE THREAD

**Issue by jhdxr** [weui/weui#545]
参考 https://mobile.ant.design/kitchen-sink/steps/

![qq 20161202155639](https://cloud.githubusercontent.com/assets/1993373/20826729/01e9f2ce-b8a8-11e6-8266-485c62526ca8.png)

**Comment by logoove** [comment]
我们的weui+已提供啦

**Comment by BearJ** [comment]
@jhdxr 这个我们目前没有，可能需要自己实现，或参考别人（如楼上的weui+）的实现方式。

**Comment by logoove** [comment]
@jhdxr <https://github.com/logoove/weui>

**Comment by jhdxr** [comment]
多谢@logoove 。
@BearJ 正因为没有所以这才是一个feature request，我只是想指出weui在这种场景下的缺失而已_(:з」∠)_

**Comment by BearJ** [comment]
@jhdxr weui的产出起码我们自己内部使用过的，才会推广出来哟。但现在我们内部类似这样的组件还没定论，所以就没有。。。
