### ISSUE TITLE
picker没有文档吗，想用多列的选择器，但是不是现在issues里面那种级联的

### ISSUE THREAD

**Issue by ZH4L** [weui/weui#546]
多列的picker怎么使用呢，没有找到相关文档，而且看了一下另一个issues，提供的方法貌似是级联选择的，现在想做一个多列的，但是不需要级联的

**Comment by BearJ** [comment]
@ZH4L 如果是多列却又不是级联的话，建议用两个picker

**Comment by ZH4L** [comment]
@BearJ 有些需求里面如果用多个picker的话体验不好，建议可以参考一下jquery weui等其他实现里面的多列picker

**Comment by BearJ** [comment]
@ZH4L 是这样的，不是实现不了，而是我们理解的picker就应该是级联选择器的，如果你想实现并级的效果，可以传相同的children即可（同一数组）。 https://github.com/weui/weui.js/blob/master/docs/component/picker.md

**Comment by ZH4L** [comment]
@BearJ 用相同的children倒是能够解决一些问题，但是一旦数据稍微多一点就不太适用了

**Comment by BearJ** [comment]
@ZH4L 嗯嗯，等我们再探讨一下

**Comment by ZH4L** [comment]
@BearJ nice

**Comment by progrape** [comment]
@ZH4L 现在支持多列选择了，不用级联 https://github.com/weui/weui.js/blob/master/docs/component/picker.md
