### ISSUE TITLE
[SearchBar Enhancement]针对SearchBar

### ISSUE THREAD

**Issue by imicer** [weui/weui#547]
Hi 敬爱的**weui team**：

最近一直在体验weui这套让人欲罢不能的组件，但是对比微信本身的某些功能还是有一些小差异的，所以前来提个请求，请求能丰富当前SearchBar的功能。

由于怕描述有问题，所以直接上图了，如下图所示：

![image](https://cloud.githubusercontent.com/assets/17045801/20880372/be4e9fb6-bb12-11e6-9e90-01890be15a5a.png)

**Comment by sklthegoodman** [comment]
某些功能上的差异是指哪个地方呢？

你是想要一个语音输入的按钮吗？

**Comment by imicer** [comment]
额……不是，我是想要点了SearchBar的录入框之后，弹出可以支持其他操作的区域，譬如下图红框区域内的操作：
![image](https://cloud.githubusercontent.com/assets/17045801/20880964/0e784be8-bb15-11e6-95e5-8efecdd459cf.png)

**Comment by logoove** [comment]
这种属于组合 自己写进去即可
