### ISSUE TITLE
不一致

### ISSUE THREAD

**Issue by fakership** [weui/weui#550]
你们npm install下来的weui 与 直接download下来的类名写法不一样

一个是 .weui_cell_hd

另一个是.weui-cell__hd

**Comment by fakership** [comment]
这很让人抓狂啊

**Comment by BearJ** [comment]
@fakership npm install 最新版试试？

**Comment by ONEBOYS** [comment]
很坑啊，这命名全局改了也就算了，很多又没改全，难道下次再改一遍啊

**Comment by logoove** [comment]
BEM命名而已 需要适应过程
