### ISSUE TITLE
在微信客户端中，weui-checkd, weui-radio有300ms延迟，且增加fastclick后css失效

### ISSUE THREAD

**Issue by 2doous** [weui/weui#553]
基于css的checkbox，radio。在微信客户端中有300ms的延迟触发（ios10，Safari无延迟）。如果增加fastclick，则整个label元素会失效。无法点击整行触发选中。

期待weui有统一的解决方案~~ 
暂时把weui-label放在内部，不让其包裹块级元素可以有效。
<div class="weui-cell__bd">
      <label class="weui-check__label" for="x1">label</label>
</div>

**Comment by BearJ** [comment]
这个可以加个style
