### ISSUE TITLE
picker 可以在pc上访问吗?

### ISSUE THREAD

**Issue by sidealice** [weui/weui#554]
我在pc上访问发现无法触发js的选中效果?

虽然weui是mobile first,但是我还是想有没有办法js触发判断,退化响应支持pc

**Comment by BearJ** [comment]
嗯，目前只是针对手机端的，pc端用mouse事件也是可以的。

**Comment by sidealice** [comment]
我点了没用选中,弹起来的框无法关闭了, 是什么原因?

**Comment by logoove** [comment]
支持的

**Comment by sidealice** [comment]
是官方范例就支持吗?https://weui.io/#picker  还是要改配置或代码适配

**Comment by yikuo123** [comment]
电脑上鼠标不能选择，试过ie11、edge和chrome

**Comment by BearJ** [comment]
@sidealice @yikuo123 是需要自己手动改代码的。因为picker就是为手机端而设计的，如果在pc端，应该使用select。没有适配也是为了达到代码最小化，请谅解哈。

**Comment by sidealice** [comment]
好的谢谢。 目前只需要改touch到click或select这样的事件对吗？ 还有其他需要注意的吗。

**Comment by BearJ** [comment]
这样：
touchstart -> mousedown
touchmove -> mousemove
touchend -> mouseup

事件的参数也有点变化

**Comment by BearJ** [comment]
@sidealice 现在weui.js的develop分支支持了PC，详情：https://github.com/weui/weui.js/issues/29
