### ISSUE TITLE
添加下拉或上拉页面刷新

### ISSUE THREAD

**Issue by panpiter** [weui/weui#555]
添加下拉或上拉页面刷新页面

**Comment by BearJ** [comment]
@panpiter 你好，这个已经有人实现了，而且也不属于weui的范畴，所以我们就不重复造轮子了。

**Comment by Yunfeng** [comment]
@BearJ 能给个具体的项目名称或链接嘛？

**Comment by logoove** [comment]
我weui+里面的 可以参考代例子<http://weixin.yoby123.cn/weui/c/cell4.html>

**Comment by logoove** [comment]
@Yunfeng 搜weui+

**Comment by YangJianFei** [comment]
@BearJ 有什么方法去掉微信网页里面的body下拉弹出网页来源信息事件又不影响页面其他元素的click，touch等事件？

**Comment by logoove** [comment]
这样就可以   document.querySelector('body').addEventListener('touchmove', function(e) {
    e.preventDefault();
})

演示<http://weixin.yoby123.cn/weui/>

**Comment by YangJianFei** [comment]
恩可以实现，但是页面整个都滚动不了了。（最好是有解绑事件。微信这样做太暴力了）

**Comment by progrape** [comment]
@panpiter 下拉刷新可以试试这个项目 https://github.com/BoxFactura/pulltorefresh.js
