### ISSUE TITLE
weui.css问题

### ISSUE THREAD

**Issue by HandsomeButterball** [weui/weui#558]
文档中给的是这样的class="weui_btn weui_btn_primary，实际weui.css中是weui-btn、weui-btn_primary这种的，这让怎么用？？？？

**Comment by logoove** [comment]
文档是旧的 以演示为标准

**Comment by BearJ** [comment]
@HandsomeButterball 你的文档可能是保存下来老的地址，这个是最新的：https://github.com/weui/weui/wiki
