### ISSUE TITLE
picker date控件怎么设置默认时间

### ISSUE THREAD

**Issue by lrwbaron** [weui/weui#566]
weui.min.js有没有未压缩的版本

**Comment by techistoner** [comment]
我也想知道怎么设置的。

**Comment by liaoliaokl** [comment]
onchange的时候怎么设置默认选中当前日期

**Comment by BearJ** [comment]
@lrwbaron 未压缩版本：https://res.wx.qq.com/open/libs/weuijs/1.0.0/weui.js
@techistoner @liaoliaokl 可以通过defaultValue设置，详情请看：https://github.com/weui/weui.js/blob/master/docs/component/picker.md
