### ISSUE TITLE
picker基本没有api可用啊，文档也没有，未压缩的代码也没有，完全没法个性化设置啊，唉

### ISSUE THREAD

**Issue by gaoqiang19514** [weui/weui#569]

**Comment by sklthegoodman** [comment]
请参考一下这里：
https://github.com/weui/weui.js/blob/master/docs/component/picker.md

**Comment by gaoqiang19514** [comment]
请问有没有方法在onChange事件触发时，更新items的值啊，我需要在滚动时，根据条件重置掉items，

**Comment by BearJ** [comment]
@gaoqiang19514 目前不支持 实时改变选项 哦。类似这种情况，我建议使用级联的picker
