### ISSUE TITLE
安卓机子上键盘弹出会遮住input

### ISSUE THREAD

**Issue by fay04** [weui/weui#571]
安卓机子上键盘弹起遮住input

**Comment by fay04** [comment]
已经使用example.js中那段代码了，但是还是无效。weui中的例子中input也会被遮住

**Comment by BearJ** [comment]
@fay04 是什么输入法？

**Comment by fay04** [comment]
小米5的自带输入法，已经试过了，搜狗和百度输入法同样会遮住input

**Comment by Refactoring** [comment]
我了个擦，这么坑爹，我觉得还是弃坑比较好...
这一堆基础问题，要调整到什么时候

**Comment by BearJ** [comment]
@fay04 试试用document.activeElement.scrollIntoView() ？
