### ISSUE TITLE
更多上手示例那里的例子已经过期

### ISSUE THREAD

**Issue by billschen** [weui/weui#574]
[在1.0.0在代码层面上做了哪些改变](https://github.com/weui/weui/wiki/%E5%9C%A81.0.0%E5%9C%A8%E4%BB%A3%E7%A0%81%E5%B1%82%E9%9D%A2%E4%B8%8A%E5%81%9A%E4%BA%86%E5%93%AA%E4%BA%9B%E6%94%B9%E5%8F%98)
里面说1.0有命名更改，但在[更多上手示例](http://codepen.io/progrape/pens/tags/2/?selected_tag=weui)
中，使用的还是旧版来做的。

**Comment by BearJ** [comment]
@billschen 现在已经更换了，谢谢提醒~

**Comment by billschen** [comment]
@BearJ 你确定已经更新了，我现在看到的还是旧的版本。
[一个示例还是旧的版本](http://codepen.io/progrape/pen/VaejgB)
有图为证：
![g2036](https://cloud.githubusercontent.com/assets/19528399/21628412/47879eb4-d25a-11e6-9a4e-e1d2383063c9.png)

**Comment by BearJ** [comment]
@billschen 我更新的意思是，那里的入口换成weui.io了~~
