### ISSUE TITLE
如何使用cell实现 label + select + button 的横排效果

### ISSUE THREAD

**Issue by billschen** [weui/weui#576]
想做一个图片上传工具，其中有一个选项需要用户选择图片的分类，这个分类是可以添加的。
想把添加按钮放在右边，尝试了一下，截图如下图所示，小箭头的位置没有相应地发生变化。
不知在weui中还有什么方法可以做。
![f250](https://cloud.githubusercontent.com/assets/19528399/21630410/d7a6c586-d26b-11e6-92a3-b115eca08d44.png)

**Comment by logoove** [comment]
需要提供示例页面 一般删除 weui-cell__ft类即可 1.0以下版本weui_cell_ft类

**Comment by BearJ** [comment]
@billschen 是这个效果吗？http://codepen.io/bearyan/pen/vgEmQL

**Comment by billschen** [comment]
![g203](https://cloud.githubusercontent.com/assets/19528399/21706803/b5952628-d404-11e6-9fe7-fd97778cc480.png)
@BearJ ,OK差不多了，多谢！
