### ISSUE TITLE
weui.js的版本还是旧版本啊

### ISSUE THREAD

**Issue by liu951919064** [weui/weui#578]

**Comment by BearJ** [comment]
@liu951919064 是的，新版本请看：https://github.com/weui/weui.js/。后期我们会更换上去。

**Comment by xdrblog** [comment]
1.1.0设置默认选中值功能不能用，压缩的代码中没有相关逻辑

**Comment by Refactoring** [comment]
我了个擦，这么坑爹，我觉得还是弃坑比较好...
这一堆基础问题，要调整到什么时候

**Comment by BearJ** [comment]
@liu951919064 已更新了

**Comment by BearJ** [comment]
@xdrblog 请看这里：https://github.com/weui/weui.js/blob/master/docs/component/picker.md
