### ISSUE TITLE
jssdk对于SPA使用html5 history的问题

### ISSUE THREAD

**Issue by luckyyyyy** [weui/weui#580]
在新的6.5.x版本中应该是修复了双端history的问题。

但是，入口页不一样导致无法支付的问题怎么解决，安卓可以每次config解决支付问题，但是IOS只锁定了Landing Page，安全支付uri只能设置3个，入口有千万个啊，所以这种情况怎么解决，不想使用hash和跳转...
IOS：Landing Page
安卓：Current Page

**Comment by BearJ** [comment]
@Webster-jx3 这个问题更建议你去 公众平台开发者社区 提出：https://developers.weixin.qq.com
