### ISSUE TITLE
示例文档代码是错误的

### ISSUE THREAD

**Issue by snailbinich** [weui/weui#583]
https://mp.weixin.qq.com/wiki/2/ae9782fb42e47ad79eb7b361c2149d16.html
举例：
文档中的这段代码
`<a href="#" class="weui_btn weui_btn_primary">按钮</a>`

应该是
`<a href="#" class="weui-btn weui-btn_primary">按钮</a>`

**Comment by BearJ** [comment]
@snailbinich https://mp.weixin.qq.com/wiki  这个才是最新的开发者文档哈~

**Comment by avocadowang** [comment]
下划线0开头版本号写法,"-"是版本号1开头(也就是目前最新版本)

**Comment by BearJ** [comment]
楼上正解~~
