### ISSUE TITLE
没有"weui-btn_plain-warn"即没有type为warn的镂空按钮

### ISSUE THREAD

**Issue by OYsun** [weui/weui#585]

**Comment by OYsun** [comment]
看了文档和源码，发现没有"weui-btn_plain-warn"即没有type为warn的镂空按钮。请问这是故意这样设计的吗？

**Comment by BearJ** [comment]
@OYsun 是的，设计上并不鼓励这种按钮。当然你也可以通过自己写一个扩展类来扩展。

**Comment by OYsun** [comment]
@BearJ 好的
