### ISSUE TITLE
请问如何防止下拉页面露黑底？

### ISSUE THREAD

**Issue by maomaoshuo** [weui/weui#587]
https://weui.io/ 
访问这个网址的时候，浏览器navbar会变灰锁定，然后页面就固定住了不会显示上下拖拽的黑底。
但是这个效果我在我的网址上都不能实现。请问是什么方法可以固定住页面不露黑底？ 

谢谢。

**Comment by BearJ** [comment]
@maomaoshuo 父层元素height:100%   要滚动的元素加上-webkit-overflow-scrolling: touch; (这是让ios可以流畅滚动)

**Comment by maomaoshuo** [comment]
谢谢回答，但是我这边测试还是没有解决问题，我在重复描述下情况

就是在微信中我下拉网页，会出现灰黑色的底色和文字：网页由xxxx提供。在有菜单footbar和下拉更新等效果时会造成很多交互干扰。
但是在微信中访问https://weui.io/ 网址时，就屏蔽了这个效果，整体网页是固定住的，不会出现网页由xxx提供和黑底，体验很好。

我复制了weiui.io的全部代码，也无法重现这个效果，很诚意向各位请教！谢谢

**Comment by BearJ** [comment]
@maomaoshuo 哦哦，是这个问题，这个需要用到jsAPI：https://github.com/weui/weui/blob/master/src/example/example.js Line 237

**Comment by qingdie** [comment]
你好，但是这个api我调了，但是并没什么变化，调试发现是执行了，没有产生变化

**Comment by maomaoshuo** [comment]
wx.invoke('setBounceBackground', {
                    'backgroundColor': '#F8F8F8',
                    'footerBounceColor' : '#F8F8F8'
                });

这个代码就是设置颜色，可以把整体页面固定住，不能拖动？

**Comment by BearJ** [comment]
@maomaoshuo 如果要不能拖动的话就要类似我第一次说到的那个实现才行。。

**Comment by maomaoshuo** [comment]
可能我还没说清楚问题，我再描述下，麻烦您看下
在微信的浏览器中下拉页面会出现微信自带的网页由xxx提供。这种效果很影响体验。在微信中打开weui.io这个网站中就关闭了这一功能。我复制了weui的代码也没能实现这个效果，试了您说的方法，也没成功瓶坯微信的下拉显示“网页由xxx提供”的功能。

一般情况是在webview中设置webView.scrollView.bounces = NO;
但是微信webview没有关闭页面拖拽下拉，请问是不是因为weui.io有一些特殊的设置方法？

**Comment by maomaoshuo** [comment]
我的qq 13058262 @BearJ  如果您有空希望占用您几分钟跟您交流下哈

**Comment by qingdie** [comment]
@maomaoshuo 设置代码就是：
 wx.invoke('setBounceBackground', {
                    'backgroundColor': '#F8F8F8',
                    'footerBounceColor' : '#F8F8F8'
                });

但是我们没有权限调用，我调用了没有什么变化，不知道官方做了什么限制

**Comment by ydq** [comment]
![image](https://cloud.githubusercontent.com/assets/8097340/22915176/528d13ae-f2b0-11e6-9a72-1e1399ae39e1.png)

LZ稍微分析一下 https://weui.io/example.js 这个js文件（213行开始）你就有所收获，但是不是你一个人有这个疑问，我们都尝试过了，没效果，可能是微信还没完全开放这个功能吧。

**Comment by maomaoshuo** [comment]
@ydq 谢谢。我也是看了很多资料解决不了才来官方问一下。

希望官方能尽早跟我们一种在微信中锁定页面不能滚动的方式，感谢。@BearJ

**Comment by lovemyliwu** [comment]
@maomaoshuo 
![image](https://cloud.githubusercontent.com/assets/2248369/22957526/c7ed1500-f363-11e6-9472-168023e05a12.png)

**Comment by maomaoshuo** [comment]
@lovemyliwu 我主要看的ios上的效果，安卓上还没测试。谢谢

**Comment by BearJ** [comment]
@maomaoshuo 的确就是和上面所说的，因为这个JSAPI没有对外开放，所以大家还暂时用不了。用了这个JSAPI并不是锁定了页面，而是后面的背景色和页面是一致的，所以看上去就是锁定了
