### ISSUE TITLE
使用weui的话，后端必须用nodejs吗？

### ISSUE THREAD

**Issue by rafw** [weui/weui#589]
如题。

**Comment by airyland** [comment]
理解清楚前端具体是什么内容。后端你用什么都行。

**Comment by BearJ** [comment]
@metalwood 不是的，后台可以是任何后台语言

**Comment by gaoqiang19514** [comment]
服了，这种问题都能问的出来？

**Comment by rafw** [comment]
我是想问这个框架是不是必须要搭配nodejs用，不是说整个网站的后端，怎么删帖。

**Comment by gaoqiang19514** [comment]
看来你还是没明白，这个是UI层，怎么都不会跟后台扯上关系，你还在那说 “我是想问这个框架是不是必须要搭配nodejs用”， 佩服！

**Comment by rafw** [comment]
就是问做UI系统，这个WEUI是不是必须搭配nodejs，还是说可以做静态页面只要浏览器就可以运行（因为首页安装都是通过npm来的，对于非前段人员，不理解这一点）。少挖苦人，不是所有开发都觉得前端的东西理所当然。

**Comment by airyland** [comment]
不做任何功课来问问题，就别怪别人挖苦你了。这个问题是二月份提的现在是四月份，你还没弄清楚，可以告别前端了。

**Comment by billschen** [comment]
分不清楚前后呀，React也不是必须搭 nodejs. 
基础，基础！

**Comment by rafw** [comment]
我不是做前端的，也没打算做前端，就是了解一下，以前聊过一个前端张口自己设计框架，今天又碰到个挑刺损人的，你觉得简单可以懒得回答，你觉得你懂你就讲清楚，什么忙都帮不上，反而搞得乌烟瘴气话里带刺的

**Comment by rafw** [comment]
@gaoqiang19514 你看看你的回答里有一个字是有意义的吗？除了损人你还讲清楚了啥？一个有意义的回答也没有。我不是做前端的，也没打算做前端，就是了解一下，以前聊过一个前端张口自己设计框架，今天又碰到个挑刺损人的，你觉得简单可以懒得回答，你觉得你懂你就讲清楚，什么忙都帮不上，也不想真心解答问题，反而搞得乌烟瘴气话里带刺的

**Comment by rafw** [comment]
@airyland 已经关闭问题了，没有邀请你来回答这么简单的问题

**Comment by rafw** [comment]
@billschen REACT代码可以直接通过浏览器渲染？这个还真不知道

**Comment by billschen** [comment]
@rafw ,当然，你可以参考：[https://reactjs.net/](https://reactjs.net/) ，这个偏离主题了。

**Comment by rafw** [comment]
@billschen 了解，这才是我的疑问所在，问题应该表述成“WEUI是否可以做纯静态页面” 哈哈

**Comment by progrape** [comment]
node.js 在 WeUI （不仅是WeUI，还有很多其他前端项目）只是作为构建工具，将源码（LESS）编译成CSS。

> 我是想问这个框架是不是必须要搭配nodejs用，不是说整个网站的后端

从开发 WeUI 的角度看，的确需要 node.js 环境，因为改了源码需要重新构建。

从使用 WeUI 的角度看，和 node.js 没有任何关系，后端用什么都可以，只要返回给浏览器 HTML、CSS、JavaScript 就行了。

**Comment by rafw** [comment]
@billschen weui的js不包括nodejs的后端JS，仅仅是浏览器端的前端JS，npm仅仅是为了项目管理方便、搭配node开发网站，才用npm下载weui的，是这样理解吧

**Comment by billschen** [comment]
@rafw  @progrape  已经很好的解答了你的问题。
可能是因为现在node.js流行了，很多框架都指示或推荐用npm进行安装，所在就会导致你这个问题。

**Comment by rafw** [comment]
@billschen @progrape 谢谢，很清晰了，前后端都是用了js而开发者往往觉得没必要解释node的用途，我想把web管理界面打包进二进制包便于分发，需要一个大气的前端框架，如果必须拖上node就不太方便，所以想到有此一问，谢谢二位的透彻解答。😄

**Comment by gaoqiang19514** [comment]
自己不打好基础，还不许人说了？这么玻璃心还学个屁啊


来自 魅族 PRO 6

-------- 原始邮件 --------
发件人：rafael w <notifications@github.com>
时间：周六 4月1日 10:42
收件人：weui/weui <weui@noreply.github.com>
抄送：gaoqiang19514 <gaoqiang19514@163.com>,Mention <mention@noreply.github.com>
主题：Re: [weui/weui] 使用weui的话，后端必须用nodejs吗？ (#589)

**Comment by rafw** [comment]
@gaoqiang19514 看错人了，所以删了，散了哈，无意义
