### ISSUE TITLE
Uploader控件在ios上出现的问题

### ISSUE THREAD

**Issue by chao891205** [weui/weui#592]
ios系统版本：9.3.5
微信版本：6.5.5
现象：页面使用Uploader控件调用系统相机，完成照相后返回页面会刷新本页面

**Comment by ywfwj2008** [comment]
测试了没有问题

**Comment by chao891205** [comment]
`<link rel="stylesheet" href="css/weui.css">`
`<input id="uploaderInput" name="uploaderInput" class="weui-uploader__input" type="file" accept="image/*" multiple />`
`<script type="text/javascript">`
`....`
` $uploaderInput.on("change", function(e){`
`            var src, url = window.URL || window.webkitURL || window.mozURL, files = e.target.files;`
`            for (var i = 0, len = files.length; i < len; ++i) {`
`                var file = files[i];`
`                if (url) {`
`                    src = url.createObjectURL(file);`
`                } else {`
`                    src = e.target.result;`
`                }`
`                $uploaderFiles.append($(tmpl.replace('#url#', src)));`
`            }`
`        });`
`....`
`</script>`
以上是我页面里的部分代码 按照demo写的

**Comment by BearJ** [comment]
@chao891205 可能是内存不够...试试清清后台进程？

**Comment by chao891205** [comment]
果然是内存的问题 测试机是iPhone4s 换为iPhone6就没有问题。。。。
