### ISSUE TITLE
请问下面这段代码中的hack是为了解决什么问题？

### ISSUE THREAD

**Issue by liuyunzhuge** [weui/weui#6]
.weui_btn_area.weui_btn_area_inline .weui_btn {
  ...
  display: inline-block \9;
  width: 48% \9;
  margin-left: 1% \9;
  margin-right: 1% \9;
}

**Comment by BearJ** [comment]
这个是为了hack IE9下不支持flex布局的情况，但默认只放两个按钮。若超出，需手动改width值。

**Comment by liuyunzhuge** [comment]
OK，懂了。我想的是既然是移动web的框架，不考虑IE应该没关系。

**Comment by BearJ** [comment]
当时是为了考虑WinPhone7（内置的IE9）
