### ISSUE TITLE
picker的日期组件在微信字体或系统字体改变的情况下无法选择

### ISSUE THREAD

**Issue by f39516046** [weui/weui#603]
目前有用户反映到手机在选择日期的时候无法正常的选择，主要情况为 选择项没有在那两条线框里，导致选择的选项不准确。。  目前暂无截图

是否有官方人员可以关注下，是系统字体问题导致的scroll位置出问题吗？ 还是哪种情况？

该问题使用 问题手机在官方的demo中同样复现出来

**Comment by BearJ** [comment]
@f39516046 试试按这个issue的改？#581

**Comment by f39516046** [comment]
已了解，是同一个问题。。
