### ISSUE TITLE
vux开发模板中使用weui

### ISSUE THREAD

**Issue by weitao901127** [weui/weui#611]
在项目中直接npm install --save weui 初始化了一个weui项目，我想在vux项目模板中使用weui的upload插件，要下载对应的js，css页面引用使用吗？

**Comment by BearJ** [comment]
@weitao901127 js的话需要看这里：https://github.com/weui/weui.js/
weui只是样式库，当然了，如果你只是要样式而不用js就不用看上面的链接~

**Comment by airyland** [comment]
样式引入参照 https://github.com/airyland/vux/blob/v2/src/demos/Uploader.vue

**Comment by ssshooter** [comment]
@airyland 借楼问一下，vux用theme.less改变样式之后，import 'weui' 覆盖回去了...怎么办？
