### ISSUE TITLE
picker能否像选省市区那样多级联动？

### ISSUE THREAD

**Issue by piscdong** [weui/weui#631]
picker能否实现像选省市区那样多级联动？可以自定义联动的内容

**Comment by spemoon** [comment]
貌似要用weui.js做多级联动
https://github.com/weui/weui.js/blob/master/docs/component/picker.md

**Comment by piscdong** [comment]
谢谢，我试试看

**Comment by progrape** [comment]
@piscdong weui.js 的 picker 实现可以级联选择，可以参考文档～

**Comment by yyh2219182230** [comment]
@progrape 但是好像只能2级呀，怎么做到三级的？
