### ISSUE TITLE
能否增加对话UI

### ISSUE THREAD

**Issue by herolee** [weui/weui#7]
对话列表UI，类似web版微信的UI（不过那套的样式已经比较古老了）

**Comment by progrape** [comment]
@herolee 你可能看到是旧版的Web微信，我们今年上线的新版Web微信对UI进行了全新设计， 可以在[https://wx.qq.com/](https://wx.qq.com/)体验，并不古老哦~~

![bubble](https://cloud.githubusercontent.com/assets/4652816/10421750/068d551a-70e1-11e5-8a1a-abf087bb9641.jpg)


另外，我们目前觉得对话列表组件应用场景比较少，暂时不考虑加入组件库。

如果后续有更多的同学提出这个需求，我们再进行规划~

**Comment by callmez** [comment]
赞 这个也很需要哟.

**Comment by callmez** [comment]
这个场景还是有的吧...对话模拟, 聊天记录.还是有需求的..希望能考虑

**Comment by yhhwpp** [comment]
这个确实需求不大

**Comment by jimhj** [comment]
+1

**Comment by callmez** [comment]
现在有出来类似模拟 微信场景的页面... 算是一种营销手段 

[微信案例](http://ca.lagou.com/programmer/index?from=singlemessage&isappinstalled=0) (微信打开)

需求是有的..就看大大们提供不提供了.....

**Comment by progrape** [comment]
需求是有，但是对于多数使用`WeUI`的开发者来说是不需要的，少数场景下才会用到，所以暂时不会集成到`WeUI`里面。不过可以考虑单独拎出来

**Comment by callmez** [comment]
赞  期待!

**Comment by my-god404** [comment]
+1
