### ISSUE TITLE
Action Sheet 位置错误

### ISSUE THREAD

**Issue by linkkingjay** [weui/weui#73]
`.weui_actionsheet` 的 `position` 值是 `absolute`，其位置受最近的 positioned 祖先元素位置影响。当最近的 positioned 祖先元素高度不为一屏或位置不在当前屏的时候，action sheet 的位置会错误。可以考虑将其改为 `fixed` 解决这个问题。
https://github.com/weui/weui/blob/master/src/style/widget/weui_tips/weui_actionsheet.less#L4

**Comment by sklthegoodman** [comment]
@linkkingjay 当时没有使用fixed是因为考虑到在iOS上，如果点击了input元素，再点击弹出`ActionSheet`的时候，会出现`ActionSheet`突然掉下来的动作。今天经过讨论之后，大家觉得可以接受，所以按照你的建议改成fixed。
感谢反馈。

**Comment by linkkingjay** [comment]
@sklthegoodman 明白了 👍
