### ISSUE TITLE
能否出一个完全模仿微信朋友圈的案例？

### ISSUE THREAD

**Issue by xmushi** [weui/weui#80]
1.发布
2.朋友圈回复
3.最重要的，相关照片的view

那就福利啊

**Comment by tinyhill** [comment]
这个主意不错

**Comment by mcdongWang** [comment]
福利啊........

**Comment by progrape** [comment]
@xmushi @tinyhill @mcdongWang 网友@n7best 做了一个demo
http://n7best.com/moment/

**Comment by Lucups** [comment]
Mark 一下，看起来不错。
TODO:   添加点赞、评论相关功能。

**Comment by n7best** [comment]
之前的空间有点问题，转移到https://momenttest.firebaseapp.com

**Comment by pkkgu** [comment]
@n7best DEMO为啥关闭了

**Comment by n7best** [comment]
@pkkgu 弄了微信登录 静态空间没法所以转到服务器上，整理下再放出来

**Comment by ambbg** [comment]
源码能提供下载吗？

**Comment by n7best** [comment]
把之前的分出来弄了一个简单的参考模版 http://codepen.io/n7best/pen/PZOzVW

**Comment by zbcdj2008** [comment]
frozenui看着确实不错，东西挺全和的
