### ISSUE TITLE
weui在vivo手机中样式乱掉了

### ISSUE THREAD

**Issue by 676496871** [weui/weui#81]
最近在微信开中写了几个页面，在iPhone 华为 小米 页面样式都是好的，唯独vivo手机5.5寸屏幕，样式乱掉了

**Comment by Jayin** [comment]
最好给上截图 手机系统版本 微信版本

**Comment by 676496871** [comment]
vivo x5 max Android4.4.4  微信6.3.5
![image](https://cloud.githubusercontent.com/assets/15355086/10988839/02845e7a-847b-11e5-904b-74512d6abb92.png)
小米手机正常
![image](https://cloud.githubusercontent.com/assets/15355086/10988867/56f3836e-847b-11e5-8e44-22c6ba0dc454.png)

**Comment by 676496871** [comment]
新手勿怪！感谢

**Comment by progrape** [comment]
@676496871 我们用VIVO看了这里[http://weui.github.io/weui/](http://weui.github.io/weui/)的demo，没有发现样式错乱的问题。你可否提供一下你的页面地址？或者你用VIVO看看`WeUI`的demo有没有样式错乱的情况？

**Comment by 676496871** [comment]
我也测试了weui的demo，确实是正常的，我自己写的样式的问题，我先试着排查问题，感谢

**Comment by progrape** [comment]
:+1:
