### ISSUE TITLE
使用fastclick时，checkbox的条目很难点中，需要在偏上方才能点中。

### ISSUE THREAD

**Issue by airyland** [weui/weui#85]
而不使用fastclick时，checkbox等控件对点击响应又比较慢。

**Comment by progrape** [comment]
可否提供可以访问的demo？看看是什么问题导致的

**Comment by progrape** [comment]
@airyland 使用fastclick时，checkbox很难点中的问题，fastclick的issue有讨论过，[https://github.com/ftlabs/fastclick/issues/60](https://github.com/ftlabs/fastclick/issues/60)

可以使用`pointer-events: none`处理点不中的问题。参考demo

![fastclick](https://cloud.githubusercontent.com/assets/4652816/11054783/19a2e436-87ab-11e5-8a52-779ea83eebb1.png)

[http://s.codepen.io/progrape/debug/vNQNyj](http://s.codepen.io/progrape/debug/vNQNyj)

**Comment by transtone** [comment]
不只是 checkbox ，cell也是要偏上方点击才有效。
