### ISSUE TITLE
WeUI新增组件需求

### ISSUE THREAD

**Issue by progrape** [weui/weui#9]
目前WeUI整理出来的组件有：

- button
- cell
- dialog
- toast
- article
- icon

使用场景是**移动端**，**微信内**。

我们知道，一套完整的`Wap`端UI库肯定不止以上这些组件，所以我们希望借助开源社区的力量，来丰富`WeUI`的组件库。

各位在开发微信内的Web应用时，希望使用哪些组件，可以提出建议，谢谢~

目前感谢@sinhe 同学提出“图片列表” #8， 将加入我们的开发计划。

**Comment by kevyu** [comment]
提一个，ActionSheet，类似iOS版微信中取消关注公众号时，底部弹出的确认界面。

**Comment by abellee** [comment]
日期组件 不要那种浮在触发位置边上的 适合移动端的 出现在屏幕底部的那种 感谢

**Comment by zxwinmain** [comment]
怎么没人说希望加入 bottomBar 菜单呢，在微信内访问一个网页的时候，微信已经在顶部有了一个 NavigationBar ，那么为了美观的情况下，我们并不希望在自己的网页内再加一个，所以页面上用来导航的菜单，只能放到底下弄个 bottomBar 了。

**Comment by gumutianqi** [comment]
希望可以提供这样的主见，参考http://demo.mobiscroll.com/calendar/basic/#?lang=zh&theme=mobiscroll&display=bottom

<img width="475" alt="2015-10-14 14 46 13" src="https://cloud.githubusercontent.com/assets/1057589/10476806/9b939c02-7283-11e5-96c9-22f28ce8a84a.png">

<img width="440" alt="2015-10-14 14 45 23" src="https://cloud.githubusercontent.com/assets/1057589/10476948/c0baf27c-7284-11e5-910c-342f888e8c97.png">

**Comment by ada87** [comment]
希望增加flex布局，适用于各种内容组合

**Comment by nwater** [comment]
希望能够加入图文列表组件，因为这个在各种各样的应用中比较常用。

**Comment by progrape** [comment]
@nwater 你说的是否左边缩略图，右边标题、描述以及时间等其他meta信息的列表？这个需求可以用现有的`Cell`来满足

**Comment by sklthegoodman** [comment]
@nwater 如果说的是缩略图，标题/描述之类的图文列表的话，使用Cell组件可以实现，你只需要往相应的头部或尾部塞图片/描述就好。如下：
![ptn 0dk5xa e 95h6h9 j i](https://cloud.githubusercontent.com/assets/4933537/10571121/6b517034-766e-11e5-80b1-2ce19ef77326.png)

**Comment by liniu** [comment]
希望有类似 bootstrap的网格系统，其次是多页面组件，类似 http://demos.jquerymobile.com/1.4.5/pages-multi-page/

**Comment by liniu** [comment]
还有就是卡片组件 ，参照 http://materializecss.com/cards.html 或者 bootstrap4 的Card 参照http://wiki.jikexueyuan.com/project/bootstrap4/components/card/

**Comment by nelsonkuang** [comment]
分享引导，经典的fix在bottom的nav菜单，上下拉刷新效果，点赞icon

**Comment by shenminjie** [comment]
其实我在看你们的UI的时候，我一直留意着你们跳转的这套框架，如果可以的话出一套适用于webApp的开发框架，对你们用script引入代码这样的方式点赞。不知是否会出一套OPOA这样的模式框架出来？

**Comment by jackyzonewen** [comment]
仿原生DatePicker

**Comment by cenxun** [comment]
tab控件

**Comment by Adrian0212** [comment]
手否是可以在cell上加按钮，因为做注册的时候需要发送手机验证码

**Comment by aidenzou** [comment]
基于 vue 的 weui版本：https://github.com/aidenzou/vue-weui 能否加个链接

**Comment by Larryljx** [comment]
我觉得可以，Vue是新生代精美前端框架，目标是Angular的替换者




------------------ 原始邮件 ------------------
发件人: "子凡";<notifications@github.com>;
发送时间: 2015年11月23日(星期一) 中午12:09
收件人: "weui/weui"<weui@noreply.github.com>; 

主题: Re: [weui] WeUI新增组件需求 (#9)




基于 vue 的 weui版本：https://github.com/aidenzou/vue-weui 能否加个链接

**Comment by pengtikui** [comment]
希望可以增加类似于微信钱包界面的九宫格样式

**Comment by mcdongWang** [comment]
@Larryljx  VUE现在各种加载啥的 还有问题 希望能完美替代啊

**Comment by Larryljx** [comment]
@mcdongWang Vue只是现在不够成熟，发展起来就快了！

**Comment by damichn** [comment]
路由器

**Comment by JoshuaChen** [comment]
需要一个http://cubiq.org/iscroll-5,我觉得这个应该是目前需求量最大的吧..基本上做页面都会用到

**Comment by gumutianqi** [comment]
希望emoji表情控件可以开源出来，支持嵌入div和tips浮动弹出两种。可使用微信原生，可设置一系列自定义表情，像下面这个，可以和多行输入框整合。
![img_0595](https://cloud.githubusercontent.com/assets/1057589/12469315/c577bde2-c025-11e5-9262-01baf3c666a2.PNG)

**Comment by JerroldLee** [comment]
这一套UI库挺完善的，http://m.sui.taobao.org/components/，如果这些都有了，那么开发一个webapp就很方便了，希望能够在weui也实现，这样将大大方便我们这些微信开发者

**Comment by jumboluo** [comment]
赞一下前面提到“路由”的同学，单页面应用逐渐成为主流了，用户体验好，我觉得这个可以有。另外，点击反馈可以更酷炫点，例如ripple效果。如果这些都太新潮了，card、tab、datepicker等组件那基本上是一套现代ui的必备组件，还是赶紧补上吧。

**Comment by jumboluo** [comment]
另外，明明你们做了grid（example的首页就有一个grid），却藏着掖着，这是为什么呢？

**Comment by huahua2** [comment]
用淘宝的sui吧，组件很齐全。

**Comment by baqihg** [comment]
想要一个下拉列表
