### ISSUE TITLE
居然只能输入3个汉字的label

### ISSUE THREAD

**Issue by wezhi** [weui/weui#92]
![1](https://cloud.githubusercontent.com/assets/14582620/11265742/c6acc86a-8ed9-11e5-87a5-47f31e43cee6.png)
这个表单左侧 的label，居然宽度只有3个汉字的位置，一旦超过3个汉字，就和右侧 的input重叠了。

好奇葩的设定，是为了什么呢？
或者说我还不太会用？

**Comment by BearJ** [comment]
@wezhi 你好，是这样的，label的目的是为了整体表单可以对齐，视觉规定默认是3个字，当你觉得不够的时候可以手动改。当然，如果你希望可以自适应，那么你可以：
*. 把.weui_label的width改为auto
*. 不使用.weui_label
*. 不使用label
