### ISSUE TITLE
选择时间插件，选择时间后，input中的日期和时间并非空格而是显示了T

### ISSUE THREAD

**Issue by Hanccc** [weui/weui#96]

**Comment by Hanccc** [comment]
看了一下，其实应该是微信的bug，不是框架的bug，微信检测input 的 type 为 datetime-local 时，显示时间多了个T

**Comment by BearJ** [comment]
你好，Hanccc，“显示了T”的意思是？能否提供一下截图？

**Comment by Hanccc** [comment]
了解了一下并不是框架的问题。。。而是HTML5的datetime-local这个属性自动带有T，例如 
  “2015-11-24T17:02”

**Comment by Hanccc** [comment]
不过还是想了解一下有什么方法能够去掉，毕竟在前端显示不太友好

**Comment by BearJ** [comment]
这个貌似是W3C规定的：http://www.w3.org/TR/html-markup/input.datetime.html#input.datetime.attrs.value
目前也没有什么较优的方案，我想到的解决办法有：
- 设置一个透明的datetime-local，等获得时间值后，用其他标签来显示在其下面
- 用type="date"和type="time"
- 用第三方时间选择器
- 不处理，默默地等大家习惯 "2015-11-25T15:44"。。。。。。

**Comment by Hanccc** [comment]
谢谢，你的回复给我了很多灵感，很有帮助

**Comment by dingjia** [comment]
不能直接返回时间戳么
